### ISSUE TITLE
Building `bitcoin-s-cli` fails in Scala 2.11.12  Error encountered while parsing org.bitcoins.cli.Cli$.<init>()

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1105]
`sbt ++2.11.12 cli/graalvm-native-image:packageBin`

This fails to build the `bitcoin-s-cli` with this error 

>
[error] Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.bitcoins.cli.Cli$.<init>()
[error] Parsing context:
[error]         parsing org.bitcoins.cli.Cli$.<clinit>(Cli.scala)
[error]         at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
[error]         at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:323)
[error]         at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
[error]         at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
[error]         at com.oracle.graal.pointsto.flow.SpecialInvokeTypeFlow.onObservedUpdate(InvokeTypeFlow.java:421)
[error]         at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:343)
[error]         at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:385)
[error]         at com.oracle.graal.pointsto.flow.SourceTypeFlowBase.update(SourceTypeFlowBase.java:121)
[error]         at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:511)
[error]         at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
[error]         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[error]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[error]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[error]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[error] Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.IncompatibleClassChangeError: org.bitcoins.cli.Cli and org.bitcoins.cli.Cli$delayedInit$body disagree on InnerClasses attribute
[error]         at parsing org.bitcoins.cli.Cli$.<init>(Cli.scala:7)
[error]         at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2475)
[error]         at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:93)
[error]         at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3291)
[error]         at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3093)
[error]         at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:977)
[error]         at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:871)
[error]         at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
[error]         at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
[error]         at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
[error]         at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
[error]         at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
[error]         at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:221)
[error]         at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
[error]         at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
[error]         ... 14 more
[error] Caused by: java.lang.IncompatibleClassChangeError: org.bitcoins.cli.Cli and org.bitcoins.cli.Cli$delayedInit$body disagree on InnerClasses attribute
[error]         at java.base/java.lang.Class.getDeclaringClass0(Native Method)
[error]         at java.base/java.lang.Class.getEnclosingClass(Class.java:1517)
[error]         at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJDKReflection.getEnclosingClass(HotSpotJDKReflection.java:106)
[error]         at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getEnclosingType(HotSpotResolvedObjectTypeImpl.java:943)
[error]         at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getEnclosingType(HotSpotResolvedObjectTypeImpl.java:60)
[error]         at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:296)
[error]         at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:205)
[error]         at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupType(WrappedConstantPool.java:155)
[error]         at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupType(BytecodeParser.java:4125)
[error]         at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4375)
[error]         at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5173)
[error]         at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3286)
[error]         ... 25 more
[error] Error: Image build request failed with exit status 1
[error] com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
[error]         at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1482)
[error]         at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1260)
[error]         at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1222)
[error]         at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1181)
[error]         at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1665)
[error] stack trace is suppressed; run last cli / Graalvm-native-image / packageBin for the full output
[error] (cli / Graalvm-native-image / packageBin) Failed to run List(native-image, --class-path, /home/suredbits/dev/bitcoin-s/app/cli/target/scala-2.11/bitcoin-s-cli_2.11-0.2.0+199-586fdaf3-SNAPSHOT.jar:/home/suredbits/dev/bitcoin-s/app/picklers/target/scala-2.11/bitcoin-s-app-picklers_2.11-0.2.0+199-586fdaf3-SNAPSHOT.jar:/home/suredbits/dev/bitcoin-s/core/target/scala-2.11/bitcoin-s-core_2.11-0.2.0+199-586fdaf3-SNAPSHOT.jar:/home/suredbits/dev/bitcoin-s/secp256k1jni/target/bitcoin-s-secp256k1jni-0.2.0+199-586fdaf3-SNAPSHOT.jar:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/upack_2.11/0.7.4/upack_2.11-0.7.4.jar:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.55/bcprov-jdk15on-1.55.jar:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/upickle_2.11/0.7.4/upickle_2.11-0.7.4.jar:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/com/softwaremill/sttp/core_2.11/1.7.2/core_2.11-1.7.2.jar:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scodec/scodec-bits_2.11/1.1.12/scodec-bits_2.11-1.1.12.jar:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.11/0.3.0/scala-collection-compat_2.11-0.3.0.jar:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/upickle-core_2.11/0.7.4/upickle-core_2.11-0.7.4.jar:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/ujson_2.11/0.7.4/ujson_2.11-0.7.4.jar:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/scopt/scopt_2.11/4.0.0-RC2/scopt_2.11-4.0.0-RC2.jar:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scijava/native-lib-loader/2.3.4/native-lib-loader-2.3.4.jar:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/upickle-implicits_2.11/0.7.4/upickle-implicits_2.11-0.7.4.jar:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/org/codehaus/janino/janino/3.1.0/janino-3.1.0.jar:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/org/codehaus/janino/commons-compiler/3.1.0/commons-compiler-3.1.0.jar:/home/suredbits/.cache/coursier/v1/https/repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar, -H:Name=bitcoin-s-cli, -H:EnableURLProtocols=http, -H:+ReportExceptionStackTraces, --no-fallback, --initialize-at-build-time=scala.Function3, --report-unsupported-elements-at-runtime, --verbose, --allow-incomplete-classpath, org.bitcoins.cli.Cli), exit status: 1
[error] Total time: 39 s, completed Feb 7, 2020, 4:29:45 AM

Similar to #1104 I believe this has something to do how the App trait has changed across Scala versions: 

Here is the `2.11.x` `App.scala` implementation:

https://github.com/scala/scala/blob/2.11.x/src/library/scala/App.scala

This may also be caused by the jdk/native-image I am using, here is the versions: 

```zsh
➜  ~ java -version && native-image --version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
GraalVM Version 19.3.1 CE
➜  ~ native-image --version
GraalVM Version 19.3.1 CE
```

**Comment by benthecarman** [comment]
scala 2.11 support was dropped in #1479
