### ISSUE TITLE
Look deeper in to key origin tracking, add ability to rotate keys

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1115]
Basically if we change master `xpriv`, or support multiple devices with different xprivs in a multisig scenario, how do we know which master `xpriv` is associated with this script?

See this excellent writeup by @achow101 for bitcoin core

https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md#key-origin-identification

**Comment by benthecarman** [comment]
This should be properly handled by #2345 since each wallet and thus xprv is given it's own database.

**Comment by benthecarman** [comment]
#2345 did resolve this.

A wallet is assiocated with a `walletName`. With the `walletName` you can get the encrypted seed by finding it in the seeds folder, it will be prefixed with the `walletName`.
