### ISSUE TITLE
Scala `2.11.x` is not able to compile on dlc branch on travis

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1119]
https://travis-ci.org/bitcoin-s/bitcoin-s/jobs/648972049#L360
```
[error] /home/travis/build/bitcoin-s/bitcoin-s/dlc/src/main/scala/org/bitcoins/dlc/BinaryOutcomeDLCClient.scala:365:57: not found: value Policy

[error]                               outputs.filter(_.value >= Policy.dustThreshold),

[error]                                                         ^

[error] /home/travis/build/bitcoin-s/bitcoin-s/dlc/src/main/scala/org/bitcoins/dlc/BinaryOutcomeDLCClient.scala:448:49: not found: value Policy

[error]                       outputs.filter(_.value >= Policy.dustThreshold),

[error]                                                 ^

[error] /home/travis/build/bitcoin-s/bitcoin-s/dlc/src/main/scala/org/bitcoins/dlc/BinaryOutcomeDLCClient.scala:522:33: not found: value Policy

[error]       outputs.filter(_.value >= Policy.dustThreshold),

[error]                                 ^

[error] /home/travis/build/bitcoin-s/bitcoin-s/dlc/src/main/scala/org/bitcoins/dlc/BinaryOutcomeDLCClient.scala:764:25: not found: value Policy

[error]       if (payoutValue < Policy.dustThreshold) {

[error]             
```

The obviously question is: Is `Policy` imported? The answer is yes. Strangely enough it appears that the linking between `core` and `dlc` is some how screwed up.

This seems to be introduced on #1088 -- despite the fact it doesn't touch build files at all. 

You can see that we compile all versions of Scala besides `2.11.x`. My guess is that this is related to `scalac`/`sbt` and the jdk that travis uses. 

https://travis-ci.org/bitcoin-s/bitcoin-s/jobs/648972049#L218

>$ java -Xmx32m -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
$ javac -J-Xmx32m -version
javac 11.0.2

I am unable to reprouce locally.

**Comment by benthecarman** [comment]
Scala 2.11 no longer supported
