### ISSUE TITLE
Implement `getBestBlockHash()` and `getBestFilterHeader()` correctly

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1211]
Currently our `ChainHandler.getBestBlockHash()` and `ChainHandler.getBestFilterHeader()` are not implemented correctly. We just do the dumb thing and return the first header we see at at the tallest height. 

We need to implement the ability to calculate the heaviest chain: 

https://github.com/bitcoin-s/bitcoin-s/blob/d9881dd1539b93982dc464243c6354408f9d0696/chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala#L111

https://github.com/bitcoin-s/bitcoin-s/pull/1209#discussion_r389825430

https://bitcoin.org/en/glossary/block-chain

**Comment by benthecarman** [comment]
I agree that we should be calculating the best based on heaviest chain, not tallest height. However, should we need to do this every `getBestBlockHash` call, if we are only storing one block per height then any given block from our database should be from the chain with the most work so we shouldn't need to do that calculation.
