### ISSUE TITLE
Handling of adding new foreign keys to the SpendingInfo Table

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-s/bitcoin-s#1275]
In #1197 we are adding a foreign key to the SpendingInfo table that will cause old spending infos to be invalid for not having a record for it's foreign key. The best way to handle this is would be to do a rescan on start up if there is a foreign key error on the table. However, a rescan can be expensive and time consuming. If you have other ideas how best ways to handle this and similar issues in the future, please share.

**Comment by Christewart** [comment]
I am definitely in the camp of just rescanning with a sane timestamp set by default, for instance 2019-06-01 to tip.
