### ISSUE TITLE
Reproducibility of property based test cases

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1339]
ScalaCheck gives us the abilility to reproduce test cases with a deterministic seed. (see #1336). However if we go outside of Scalacheck's random number generation for entropy we will not be able to fully reproduce the test case. 

Currently our `ECPrivateKey` generator  calls `ECPrivateKey()` which uses `SecureRandom` which calls out to the underlying OS for entropy. 

https://github.com/bitcoin-s/bitcoin-s/blob/512c6668ad7fa98ea101aee0cba6ed63e57dc725/testkit/src/main/scala/org/bitcoins/testkit/core/gen/CryptoGenerators.scala#L119

We want entropy to come from scalacheck itself to seed the ECPrivateKey so that we can be deterministic and reproduce test cases like #1336 for debugging.

**Comment by Christewart** [comment]
@nkohen does this same problem apply to generating digital signatures too?

**Comment by nkohen** [comment]
I believe so, I think we use the private key generator and then sign something to generate signatures

**Comment by nkohen** [comment]
it is also worth noting that we likely call `ECPrivateKey.freshPrivateKey` directly in many test files so that would have to be fixed (for property based tests) as well in order to get determinism
