### ISSUE TITLE
Add documentation of how to import a serialized root xpriv into key manager

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1420]
If I have a seed that is format of `xpriv...` how do i import this properly into the key-manager?

**Comment by Christewart** [comment]
What should we do with the old xpriv in this case??

1. Delete the old xpriv (bad!)
2. Cache the old xpriv in another file (???)
3. Support multiple concurrent xprvis (??? probably related to #1115)

**Comment by benthecarman** [comment]
This is not currently doable with our current key manager design. Currently, it saves the encrypted seed words, however, with an xprv you can't get it's corresponding mnemonic words. 

To be able to do this we would have to add another way to store the seed and serialize the xprv in the seed file instead. This is doable, however, we would then have 4 different ways to store seeds (encrypted mnemonic, unencrypted mnenomic, encrypted xprv, unencrypted xprv) which can get messy and a lot to maintain.
