### ISSUE TITLE
BytesPushOntoStack.zero is not a valid bytes to push onto stack

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1445]
This was found on #1435 

We currently construct a `BytesToPushOntoStack(0)` which is not a valid `BytesToPushOntoStack`:

https://github.com/bitcoin-s/bitcoin-s/blob/9a7b90c13283fbce34662838ea48282a7c662bc8/core/src/main/scala/org/bitcoins/core/script/constant/BytesToPushOntoStack.scala#L29

You see the valid ranges for `BytesToPushOntoStack` here: https://en.bitcoin.it/wiki/Script

>N/A | 1-75 | 0x01-0x4b | (special) | data | The next opcode bytes is data to be pushed onto the stack
-- | -- | -- | -- | -- | --

The key thing here is that the opcode range is `1-75` rather than `0-75`. I would have fixed this on #1435 but it seems that [`BitcoinScriptUtil.calcPushOp()`](https://github.com/bitcoin-s/bitcoin-s/blob/9a7b90c13283fbce34662838ea48282a7c662bc8/core/src/main/scala/org/bitcoins/core/util/BitcoinScriptUtil.scala#L230) depends on this quiet heavily. 

If we change the range too 

```scala
  override val operations: Vector[BytesToPushOntoStack] = {
    (for { i <- 1 to 75 } yield BytesToPushOntoStackImpl(i)).toVector
  }
```

We get a bunch of errors. This was found in #1435 because we key the `scriptOpMap` by `byte` which gives us duplicate keys for the `opcode=0`

1. `OP_0` 
2. `BytesToPushOntoStack(0)`

The work around is moving `ScriptNumberOperation` to the end of the `ScriptOperationFactory.operations` vector, which seems to put `OP_0` rather than `BytesToPushOntoStack()` in the `scriptOpMap`

**Comment by benthecarman** [comment]
This is actually indicative of a worse issue. `OP_0` is pushing `0x00` onto the stack, `BytesToPushOntoStack(0)` is pushing nothing onto the stack. Locally I was able to make a simple fix to make sure these aren't registered as the same. However, this causes things like our `isP2PKScriptSig` function to break, it checks if we have a `BytesToPushOntoStack` followed by a `ScriptConstant`, which was true beforehand for something like `P2PKScriptSignature(EmptyDigitalSignature)` which would go to `BytesToPushOntoStack(0) OP_0` before to now just is `OP_0` (Pushing `OP_0` for `ByteVector.empty` might be another error as well).

**Comment by benthecarman** [comment]
This brings up the question do we want to be able to have a ScriptSig with an `EmptyDigitalSignature`
