### ISSUE TITLE
NPE on PSBT construct and sign test case

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1536]
https://travis-ci.org/github/bitcoin-s/bitcoin-s/jobs/696429090#L1675

![Screenshot from 2020-06-09 07-42-36](https://user-images.githubusercontent.com/3514957/84148607-e114c200-aa24-11ea-8b00-1fb7038f78df.png)

**Comment by benthecarman** [comment]
The error stems from https://github.com/bitcoin-s/bitcoin-s/blob/master/testkit/src/main/scala/org/bitcoins/testkit/util/BitcoinSAsyncTest.scala#L100

looks like it is being caused by `testRunFs` being mutable
