### ISSUE TITLE
Update neutrino binary with latest bitcoin core code

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1629]
Our neutrino binary is out of date, we should update to the latest functionality and test it

https://github.com/bitcoin/bitcoin/pull/18876

**Comment by Christewart** [comment]
#1529 will need to be done first more than likely as the branch linked to is ontop of 0.20

**Comment by benthecarman** [comment]
Should build the taproot binaries as well https://github.com/bitcoin/bitcoin/pull/17977

**Comment by benthecarman** [comment]
Should be done in tandem with #1745
