### ISSUE TITLE
NodeCallbacks not being passed around correctly in Main.scala

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1687]
It seems in this refactor https://github.com/bitcoin-s/bitcoin-s/pull/1522 I managed to drop the callbacks being set in here:

https://github.com/bitcoin-s/bitcoin-s/blob/master/app/server/src/main/scala/org/bitcoins/server/Main.scala#L195-L212

You can reproduce this by trying to fund a regtest wallet with bitcoin-s

**Comment by benthecarman** [comment]
This can be proven by adding a `println` of the length of the callbacks in the `DataMessageHandler` right before any of the callbacks are executed.
