### ISSUE TITLE
Library Support in Bitcoin-S: secp256k1 vs. secp256k1-zkp

### ISSUE THREAD

**Issue by nkohen** [bitcoin-s/bitcoin-s#1692]
As schnorr and musig are being merged into secp256k1-zkp (see https://github.com/ElementsProject/secp256k1-zkp/pull/91) with ecdsa adaptor signatures following next (where notably there is no current plan or intention to support musig or ecdsa adaptor sigs in secp256k1 proper), it is time to figure out how we want to handle secp256k1 support in Bitcoin-S. In some sense it doesn't matter which repo we choose to have as a submodule as we can still use branches from either repo either way.

### Option 1: Make secp256k1-zkp the submodule instead of secp256k1
This seems to me to be the simplest solution. We get to use everything as it is introduced to zkp and conceptually speaking zkp is meant to be a superset of secp256k1, its "upstream". Practically speaking however zkp is not rebased nightly so there is some question as to whether we would want to fall behind in such a way. Counterpoint, bitcoin-s secp branches aren't rebased nightly either hehe. I will note that part of why I like this option is that there is no reason we can't still use secp256k1 (non-zkp) branches in such a submodule, they should just have the `upstream` prefix so no one gets confused.

### Option 2: Use secp256k1-zkp branches while keeping the secp256k1 submodule
I can imagine this becoming a little confusing, but it functions pretty much the same as option 1.

### Option 3: Have two submodules?
This seems like a terrible idea ... they would conflict

**Comment by tiero** [comment]
Hello! Not much experience with bitcoin-s, but want to add my past experience with support zkp lib.

I made bindings for Go and JS (https://github.com/vulpemventures/go-secp256k1-zkp and https://github.com/vulpemventures/secp256k1-zkp) but using the resulting library is a mess, especially when you need to cross-compile for a different arch.

If I could back in time I would have taken some time to port it natively to both js and go instead. 
BTCD did the same for this [reason](https://github.com/btcsuite/btcd/issues/1570#issuecomment-627550041)

Also, fork management of the zkp library doesn't seem to be the best (eg. https://github.com/ElementsProject/secp256k1-zkp/issues/68)

**Comment by Christewart** [comment]
We went with just supporting zkp due to needing ecdsa adaptor signatures
