### ISSUE TITLE
Add ability to watch arbitrary utxos

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1702]
This is needed for using bitcoin-s' neutrino node as a chain watcher in eclair. Perhaps we can expose this in `NodeApi`?

**Comment by benthecarman** [comment]
How we currently watch utxos is if the spk is in our `AddressTable`. What we could do is add a spk table and then make the `AddressTable` have a foreign key to it instead, this way we can add any spks to our watch list without having to add the address to our list resulting in effecting our balances and so on.
