### ISSUE TITLE
Logging is hacky and inefficient

### ISSUE THREAD

**Issue by nkohen** [bitcoin-s/bitcoin-s#1717]
Currently, every time a call is made to `logger.anything` a call is made to `AppLoggers.getLoggerImpl` which queries a logger context constructed from an implicit config and then queries the appender caches to find the file and console appenders for this logger and then these appenders are started. This happens every single time we log!

Ideally there would be some way to like ... just have a logger val lying around someplace in an object or at the very least in each instance of some class. Currently this is not done because for some reason the appenders keep getting stopped and also detached from their loggers, I have no clue why.

Likely whoever wants to try to fix this will have to go through a lot of documentation and figure out how logging is actually supposed to be setup because we most likely are not doing whatever it is we are supposed to be doing.

**Comment by benthecarman** [comment]
Could probably get an easy performance increase from using a [AsyncAppender](http://logback.qos.ch/manual/appenders.html#AsyncAppender)
