### ISSUE TITLE
Calculate chain_work on the fly as node is syncing

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1720]
According to @rorp we don't calculate chain_work as we call `ChainApi.processHeaders()`. This should be done

**Comment by benthecarman** [comment]
It is done here https://github.com/bitcoin-s/bitcoin-s/blob/master/chain/src/main/scala/org/bitcoins/chain/validation/TipValidation.scala#L50

It should be done anytime there is a new valid tip found
