### ISSUE TITLE
bitcoin-s-cli timing out when starting node

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1733]
It seems that the request is timing out, we should display a nicer error message than 

>expected json value got T (line 1, column 1) at index 0
 
I'm not sure what's going on, perhaps it's something to do with the fact we are syncing? It seems after ~5 minutes i'm able to send requests and get responses

>➜  bin git:(master) ✗ ./bitcoin-s-cli getbalance
0E-8 BTC
➜  bin git:(master) ✗ ./bitcoin-s-cli getnewaddress
tb1qp5dfd8dn0aq5fkm6m8z6m3hgpcp6z7rl0vkyeg
➜  bin git:(master) ✗ ./bitcoin-s-cli getblockcount
1781689

You can see my node logs in the upper right hand corner and the cli requests in the lower left hand corner:

![Screenshot from 2020-07-31 10-51-45](https://user-images.githubusercontent.com/3514957/89052881-f66ae600-d31b-11ea-9596-c601eaf61432.png)

Finally here is what visualvm looks like during this period of time:

![Screenshot from 2020-07-31 10-56-00](https://user-images.githubusercontent.com/3514957/89053171-709b6a80-d31c-11ea-9259-8cf96858e054.png)

I'm starting to suspect that this is related to #1724

**Comment by benthecarman** [comment]
The server doesn't bind until after the chainwork AFIAK

**Comment by Christewart** [comment]
> The server doesn't bind until after the chainwork AFIAK

This wasn't being run with `--force-recalc-chainwork`. I think this is fixed now with #1724 / #1737 being solved. However I want to leave this issue open so we can we give a better error message than 

>expected json value got T (line 1, column 1) at index 0

When we timeout on the server side for a request
