### ISSUE TITLE
akka logs are not added to bitcoin-s.log file

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1738]
Akka logs are critical for server/node operations. We should append these logs to bitcoin-s.log so we have all relevant information for debugging.

**Comment by nkohen** [comment]
https://doc.akka.io/docs/akka/current/logging.html#slf4j

**Comment by benthecarman** [comment]
This looks like akka isn't reading our config file. If I set my `akka.stdout-loglevel = "off"` I will still get logs in the console. So, akka probably doesn't know where to put the logs if it wanted to log to file
