### ISSUE TITLE
Figure out how to associate commit hashes with dev binary builds

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1755]
that will hopefully give us things like `./bitcoin-s-server-[commit-hash]` rather than just `./bitcoin-s-server` so we can pinpoint what we are exactly running off of. 

This is probably configurable in the native packager which is what we use for building now: 

https://github.com/sbt/sbt-native-packager

We do want to be mindful of our ci release plugin that publishes a SNAPSHOT everytime we merge into master. We don't want to break this:

https://github.com/olafurpg/sbt-ci-release

**Comment by benthecarman** [comment]
Maybe could just add a `./bitcoin-s-server --version` that outputs something like `0.4.0-1d324a` so we can see that commit hash that way

**Comment by benthecarman** [comment]
Looks like in build.sbt we can use `dynverAssertTagVersion.value` to get our version string
