### ISSUE TITLE
Divergent xpubs for account CI failure

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1794]
https://travis-ci.org/github/bitcoin-s/bitcoin-s/jobs/716203549#L683

This may be related to the postgres connection attempt failed below (#1581)

![Screenshot from 2020-08-10 08-11-58](https://user-images.githubusercontent.com/3514957/89786203-2dda4f00-dae1-11ea-82a4-3d3798690282.png)

**Comment by benthecarman** [comment]
My guess is the connection failed and the db didn't get properly dropped from the previous test run.

**Comment by Christewart** [comment]
Seen this again on #1790, and more importantly it wasn't in a postgres CI matrix

https://travis-ci.org/github/bitcoin-s/bitcoin-s/jobs/717081166#L536

![Screenshot from 2020-08-12 10-07-51](https://user-images.githubusercontent.com/3514957/90032176-b2fd6980-dc83-11ea-96db-afd3f17ca41c.png)

**Comment by benthecarman** [comment]
This might just be this line

https://github.com/bitcoin-s/bitcoin-s/blob/master/wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala#L687

which is expected because we test that the function fails correctly

**Comment by Christewart** [comment]
Failing again here: https://travis-ci.org/github/bitcoin-s/bitcoin-s/jobs/717630661#L786

**Comment by benthecarman** [comment]
> Failing again here: [travis-ci.org/github/bitcoin-s/bitcoin-s/jobs/717630661#L786](https://travis-ci.org/github/bitcoin-s/bitcoin-s/jobs/717630661#L786)

That is just the log of the expected failure, if you scroll down you can see that `WalletUnitTest` didn't fail
