### ISSUE TITLE
Things to test before release

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-s/bitcoin-s#1802]
A list of things we should test before a release

- [x] Initial Block Download

- [x] Rescanning chain

- [x] Receiving funds

- [x] Sending funds

- [x] All RPC commands

- [x] GUI

- [x] Creating a new wallet

- [x] Config options work as intended

- [ ] Logging

Please list more below

**Comment by Christewart** [comment]
We should probably add "bouncy castle" to the list. Basically starting everything and running with bouncy castle instead of secp. I don't think we necessarily need to duplicate everythign on the list, but basic RPC stuff makes sense to me.

**Comment by Christewart** [comment]
Test all of our different possible logging configs 

1. Logback and ignoring all `bitcoin-s.conf` logging
2. Just set logging in the `bitcoin-s.conf` and not use logback at all

**Comment by Christewart** [comment]
We should also figure out what java versions we work on, I run on java8 and haven't seen any problems. Does anyone run things on java11/java13?

**Comment by Christewart** [comment]
It looks like the "official" java version oracle directs people to is java 14, so perhaps we should test that too? :man_shrugging: 

![Screenshot from 2020-08-26 09-57-00](https://user-images.githubusercontent.com/3514957/91321861-b238fd00-e784-11ea-8d93-4e8dbf766390.png)

**Comment by Christewart** [comment]
We should recommend that people use at least java 11, GUI does not work with java 8. 

>[error] java.lang.UnsupportedClassVersionError: javafx/event/EventTarget has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[error]         at java.lang.ClassLoader.defineClass1(Native Method)
[error]         at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
[error]         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error]         at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
[error]         at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:363)


I think there is an issue for this somewhere, and it _really_ should be noted here on the website: 

https://bitcoin-s.org/docs/next/applications/gui#bitcoin-s-graphical-user-interface

**Comment by benthecarman** [comment]
> It looks like the "official" java version oracle directs people to is java 14, so perhaps we should test that too?

Was able to test with java 14, ran server, gui, and tests. All tests passed and node and gui seemed to work correctly.

**Comment by Christewart** [comment]
We should try testing a custom logback.xml file passed in via command line options, we should also test the "refresh" capabilities of logging so that logging levels can be adjusted at runtime

**Comment by Christewart** [comment]
So i ran full IBD with postgres last night and everything worked, I also tested rescanning a postgres wallet this morning and that seems to work. 

It's very nice when things just work :tm:

**Comment by benthecarman** [comment]
I also ran a full IBD with postgres!

**Comment by benthecarman** [comment]
> We should try testing a custom logback.xml file passed in via command line options, we should also test the "refresh" capabilities of logging so that logging levels can be adjusted at runtime

Tested this, works!!!!! Honestly surprised it does but glad that means not having to work on more logging stuff!
