### ISSUE TITLE
Log file getting deleted and not cached

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1809]
I was running 1ec10dd2cc and reporting to @benthecarman if my utxo states were updated and sent him my log file with nearly 2,000 logs in it. I came back and checked the log file later and there is now 2 lines of logs in it. This is probably related to #1805 

>2020-08-12T20:14:02 DEBUG [chain-verification] No prev found for BlockHeaderDb(1670872,DoubleSha256BDigestBE(000000000021240700150008da274d6555659069899854823f83f55e94ca39b6),Int32Impl(536870912),DoubleSha256BDigestBE(0000000000324f82435e02560aab6907c52ba059778afdac815f42d991eee9c2),DoubleSha256BDigestBE(478a1407f8333d77c148d186240e2c92b788420a96b0e0731c4076e4cef76b9f),UInt32Impl(1584970932),UInt32Impl(486604799),UInt32Impl(480148405),00000020c2e9ee91d9425f81acfd8a7759a02bc50769ab0a56025e43824f3200000000009f6bf7cee476401c73e0b0960a4288b7922c0e2486d148c1773d33f807148a47b4bc785effff001db57b9e1c,6060848556455348433979) hashBE=DoubleSha256BDigestBE(000000000021240700150008da274d6555659069899854823f83f55e94ca39b6)
2020-08-12T20:14:02 INFO [WALLET] 4 txos are now confirmed!

I've attached the original log file that I had before 
[bitcoin-s.log](https://github.com/bitcoin-s/bitcoin-s/files/5065569/bitcoin-s.log)

**Comment by benthecarman** [comment]
The logs taking a bit could be due to the fact our logging is very inefficient (#1717) + the addition of the async logger for akka logs.
