### ISSUE TITLE
bitcoin-s.logging.logback does not work

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1813]
I'm just trying to toggle settings inside of the [`testkit/reference.conf`](https://github.com/bitcoin-s/bitcoin-s/blob/master/testkit/src/main/resources/reference.conf#L6-L7) while using it with our test cases. 

For instance, if I set `bitcoin-s.logging.logback = false` and the configure `bitcoin-s.logging.level=OFF` I am still getting logs when running `coreTest/testOnly *TransactionTest*`

You can see an example of this here: https://github.com/Christewart/bitcoin-s-core/commit/8a803f1221a3e89bcf253ccc0ead1a2da00ba9b8 if you want to reproduce locally

**Comment by benthecarman** [comment]
I think that should be expected, nothing in `core` uses an `AppConfig` so it would never read the config file

**Comment by benthecarman** [comment]
However, if I do `println(conf.useLogbackConf)` it is always `false` even if I change it to `true` in the `reference.conf`
