### ISSUE TITLE
Optimize `BaseBlockchain.connectWalkBackwards` out of O(n^2) behavior

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1829]
https://github.com/bitcoin-s/bitcoin-s/issues/1780#issuecomment-674195866

One of the problems that is causing #1780 is [`BaseBlockchain.connectWalkBackwards()`](https://github.com/bitcoin-s/bitcoin-s/blob/master/chain/src/main/scala/org/bitcoins/chain/blockchain/BaseBlockChain.scala#L248) is a bottleneck.

Specifically this line: 

https://github.com/bitcoin-s/bitcoin-s/blob/86f68b3b622a4531748169cc475a5df52ac4c23e/chain/src/main/scala/org/bitcoins/chain/blockchain/BaseBlockChain.scala#L248

Some ideas of optimizing: 

1. Remove header from `ancestors` when it's in the chain (therefore are traversal gets shorter as we walk backwards)
2. Maybe avoid using `.find()` for just a raw while loop? 
3. Parallel search on the collection?

**Comment by benthecarman** [comment]
Can probably do something where we do `groupBy(_.height)` and then only search for the `previousBlockHashBE` at the expected height.
