### ISSUE TITLE
Failed to get driver instance for jdbcUrl=jdbc:sqlite:/tmp/bitcoin-s3607458955205098244/regtest/nodedb.sqlite

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1906]
Seen on #1897 but I believe it's unrelated since this PR just touches postgres

https://travis-ci.org/github/bitcoin-s/bitcoin-s/jobs/721381570#L863

![Screenshot from 2020-08-26 11-21-46](https://user-images.githubusercontent.com/3514957/91329976-7014b900-e78e-11ea-8fce-06b4f875ad8d.png)

**Comment by Christewart** [comment]
Another instance on #1897 related to `CoinSelectorTest` :thinking: 

https://travis-ci.org/github/bitcoin-s/bitcoin-s/jobs/721381571#L1816

![Screenshot from 2020-08-26 11-25-40](https://user-images.githubusercontent.com/3514957/91330404-fdf0a400-e78e-11ea-9bb4-6844acf3677a.png)

**Comment by benthecarman** [comment]
I'm guessing it has to do with that pr
