### ISSUE TITLE
Entering DLC with Ben ends up having Cannot have signers that do not sign for one of error

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1910]
Error executing command:
Request failed: requirement failed: Cannot have signers that do not sign for one of Vector(ECPublicKey(02eea4707c7f47eba5b95d9a57c3120fc85dbdeea408d6edd262403d2f5f5836e3))

I got when attempting to generate and offer for a DLC 

This occurred on #1899 and commit 3d7ffb5d1c6ee73ef894ed51bf417d0a0d28d6dc

**Comment by Christewart** [comment]
This occurred again on after doing a full rescan of the wallet on   61b2f443e30337acc45925a74f87eb1af3a006f1. Note that it's a _different_ public key that is causing the error this time which is even more concerning

```
Error executing command:
Request failed: requirement failed: Cannot have signers that do not sign for one of Vector(ECPublicKey(0220cc2033ec002d595dad4a9228b93eae658949747c0e3b63e6ea9aeee8d81a45))
```

Here are the logs

https://pastebin.com/EF8jiim9


EDIT:

This seems to apply to just normal "spends" from the wallet
````
[info] 2020-08-31T21:13:20 INFO [HTTP] Unhandled error in server:
[info] java.lang.IllegalArgumentException: requirement failed: Cannot have signers that do not sign for one of Vector(ECPublicKey(029c1ff414edd7b913f0822f26c72d56f195791636fcc0e8b5cae1c034051a8580))
[info]  at scala.Predef$.require(Predef.scala:340)
[info]  at org.bitcoins.core.wallet.utxo.InputSigningInfo.$init$(InputSigningInfo.scala:39)
[info]  at org.bitcoins.core.wallet.utxo.ScriptSignatureParams.<init>(InputSigningInfo.scala:65)
[info]  at org.bitcoins.core.api.wallet.db.SpendingInfoDb.toUTXOInfo(SpendingInfoDb.scala:200)
[info]  at org.bitcoins.core.api.wallet.db.SpendingInfoDb.toUTXOInfo$(SpendingInfoDb.scala:186)
[info]  at org.bitcoins.core.api.wallet.db.SegwitV0SpendingInfo.toUTXOInfo(SpendingInfoDb.scala:30)
[info]  at org.bitcoins.core.api.wallet.db.SpendingInfoDb.toUTXOInfo(SpendingInfoDb.scala:183)
[info]  at org.bitcoins.core.api.wallet.db.SpendingInfoDb.toUTXOInfo$(SpendingInfoDb.scala:177)
[info]  at org.bitcoins.core.api.wallet.db.SegwitV0SpendingInfo.toUTXOInfo(SpendingInfoDb.scala:30)
[info]  at org.bitcoins.wallet.internal.FundTransactionHandling.$anonfun$fundRawTransactionInternal$25(FundTransactionHandling.scala:143)
[info]  at scala.collection.immutable.Vector1.map(Vector.scala:1810)
[info]  at scala.collection.immutable.Vector1.map(Vector.scala:348)
[info]  at org.bitcoins.wallet.internal.FundTransactionHandling.$anonfun$fundRawTransactionInternal$24(FundTransactionHandling.scala:139)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
[info]  at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
[info]  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]  at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[error] java.lang.RuntimeException: Request failed: requirement failed: Cannot have signers that do not sign for one of Vector(ECPublicKey(029c1ff414edd7b913f0822f26c72d56f195791636fcc0e8b5cae1c034051a8580))
[error]         at org.bitcoins.cli.ConsoleCli$.error$1(ConsoleCli.scala:777)
[error]         at org.bitcoins.cli.ConsoleCli$.$anonfun$exec$1(ConsoleCli.scala:983)
[error]         at scala.util.Try$.apply(Try.scala:210)
[error]         at org.bitcoins.cli.ConsoleCli$.exec(ConsoleCli.scala:925)
[error]         at org.bitcoins.gui.WalletGUIModel.$anonfun$onSend$1(WalletGUIModel.scala:53)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error]         at org.bitcoins.gui.TaskRunner$$anon$1.call(TaskRunner.scala:43)
[error]         at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Christewart** [comment]
Here are the contents of `txo_spending_info`
```
sqlite> select * from txo_spending_info;
1|2ada5ad20661496580dfde529d0f7228db03728479f2fc8ef2306a4ca89ab80001000000|2|1815403|m/44'/1'/0'/0/1|||00b89aa84c6a30f28efcf279847203db28720f9d52dedf8065496106d25ada2a|000000000021240700150008da274d6555659069899854823f83f55e94ca39b6|ConfirmedReceived
6|0644f13e2623cd3020ca38ed97e10fbe54f5dbfa0022da90262b83bfe0b4f7c700000000|6|30000000|m/84'/1'/0'/0/3||0200210220cc2033ec002d595dad4a9228b93eae658949747c0e3b63e6ea9aeee8d81a45|c7f7b4e0bf832b2690da2200fadbf554be0fe197ed38ca2030cd23263ef14406|000000000000003ad317ba9632a5377f2a475c94d8f7ddc173aadcb0398c1d06|Reserved
7|b8a89c1c4bb9b744baf640199fa1bf25e1bedb9d6fc8d1102220801b805604d101000000|5|20000000|m/84'/1'/0'/0/2||020021029c1ff414edd7b913f0822f26c72d56f195791636fcc0e8b5cae1c034051a8580|d10456801b80202210d1c86f9ddbbee125bfa19f1940f6ba44b7b94b1c9ca8b8|000000000000003ad317ba9632a5377f2a475c94d8f7ddc173aadcb0398c1d06|ConfirmedReceived
8|c171dee042da941d568b1c516047d84a6e0aadb8d6d34fe2bf8f1b11ca2eee4d00000000|4|10000000|m/84'/1'/0'/0/1||02002103ef5746d4150897217028081d5c32ca0d5ce6bb17b6eb9868b1d31b6e2a6f638f|4dee2eca111b8fbfe24fd3d6b8ad0a6e4ad84760511c8b561d94da42e0de71c1|000000000000003ad317ba9632a5377f2a475c94d8f7ddc173aadcb0398c1d06|ConfirmedReceived
9|ea2f9f284e9d345f7fd1b7841903d0da2439172c1c535d1b9e0745bf17e462bb01000000|7|100000000|m/84'/1'/0'/0/4||02002102eea4707c7f47eba5b95d9a57c3120fc85dbdeea408d6edd262403d2f5f5836e3|bb62e417bf45079e1b5d531c2c173924dad0031984b7d17f5f349d4e289f2fea|0000000004557fb71b9e7aa83a13e6655de7a5d7c52c9a6da6fa3915d172e248|Reserved
```

**Comment by Christewart** [comment]
This occurs to me on master branch as well 4d6d96c9e791db35e14dbc2b5a97cedd122ca63c . This is the same wallet is I was using earlier in the issue.

>[info] 2020-09-01T11:29:44 DEBUG [WALLET] Processing AccountDb(vpub5YLxxXKmTVJKmmf3YNjjsaiVjbzZF7toU99LUvw2nGo9z4kvxh6NCpXd46KSpDNFohNoNuU1hPkdHs6Ngw3xs9et9EXyvJbq5FrBYRChjU2,m/84'/1'/0') External in our address request queue
[info] 2020-09-01T11:29:44 DEBUG [WALLET] Getting new External adddress for m/84'/1'/0'
[info] 2020-09-01T11:29:44 DEBUG [WALLET] Found previous address at path=m/84'/1'/0'/0/9, next=m/84'/1'/0'/0/10
[info] 2020-09-01T11:29:53 INFO [WALLET] Sending 0.01 BTC to tb1qksm93cfjgzfs2gaxe5u35q4463k4nevue59lvw at feerate SatoshisPerVirtualByte(89 sats)
[info] 2020-09-01T11:29:53 DEBUG [WALLET] Processing AccountDb(vpub5YLxxXKmTVJKmmf3YNjjsaiVjbzZF7toU99LUvw2nGo9z4kvxh6NCpXd46KSpDNFohNoNuU1hPkdHs6Ngw3xs9et9EXyvJbq5FrBYRChjU2,m/84'/1'/0') Change in our address request queue
[info] 2020-09-01T11:29:53 DEBUG [WALLET] Getting new Change adddress for m/84'/1'/0'
[info] 2020-09-01T11:29:53 DEBUG [WALLET] Found previous address at path=m/84'/1'/0'/1/3, next=m/84'/1'/0'/1/4
[info] 2020-09-01T11:29:53 INFO [HTTP] Unhandled error in server:
[info] java.lang.IllegalArgumentException: requirement failed: Cannot have signers that do not sign for one of Vector(ECPublicKey(029c1ff414edd7b913f0822f26c72d56f195791636fcc0e8b5cae1c034051a8580))
[info]  at scala.Predef$.require(Predef.scala:340)
[info]  at org.bitcoins.core.wallet.utxo.InputSigningInfo.$init$(InputSigningInfo.scala:39)
[info]  at org.bitcoins.core.wallet.utxo.ScriptSignatureParams.<init>(InputSigningInfo.scala:65)
[info]  at org.bitcoins.core.api.wallet.db.SpendingInfoDb.toUTXOInfo(SpendingInfoDb.scala:200)
[info]  at org.bitcoins.core.api.wallet.db.SpendingInfoDb.toUTXOInfo$(SpendingInfoDb.scala:186)
[info]  at org.bitcoins.core.api.wallet.db.SegwitV0SpendingInfo.toUTXOInfo(SpendingInfoDb.scala:30)
[info]  at org.bitcoins.core.api.wallet.db.SpendingInfoDb.toUTXOInfo(SpendingInfoDb.scala:183)
[info]  at org.bitcoins.core.api.wallet.db.SpendingInfoDb.toUTXOInfo$(SpendingInfoDb.scala:177)
[info]  at org.bitcoins.core.api.wallet.db.SegwitV0SpendingInfo.toUTXOInfo(SpendingInfoDb.scala:30)
[info]  at org.bitcoins.wallet.internal.FundTransactionHandling.$anonfun$fundRawTransactionInternal$25(FundTransactionHandling.scala:143)
[info]  at scala.collection.immutable.Vector1.map(Vector.scala:1810)
[info]  at scala.collection.immutable.Vector1.map(Vector.scala:348)
[info]  at org.bitcoins.wallet.internal.FundTransactionHandling.$anonfun$fundRawTransactionInternal$24(FundTransactionHandling.scala:139)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
[info]  at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
[info]  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]  at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[error] java.lang.RuntimeException: Request failed: requirement failed: Cannot have signers that do not sign for one of Vector(ECPublicKey(029c1ff414edd7b913f0822f26c72d56f195791636fcc0e8b5cae1c034051a8580))
[error]         at org.bitcoins.cli.ConsoleCli$.error$1(ConsoleCli.scala:949)
[error]         at org.bitcoins.cli.ConsoleCli$.$anonfun$exec$1(ConsoleCli.scala:1181)
[error]         at scala.util.Try$.apply(Try.scala:210)
[error]         at org.bitcoins.cli.ConsoleCli$.exec(ConsoleCli.scala:1123)
[error]         at org.bitcoins.gui.WalletGUIModel.$anonfun$onSend$1(WalletGUIModel.scala:55)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error]         at org.bitcoins.gui.TaskRunner$$anon$1.call(TaskRunner.scala:43)
[error]         at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)



![Screenshot from 2020-09-01 06-29-56](https://user-images.githubusercontent.com/3514957/91844223-aafa6f00-ec1c-11ea-942f-e019ac81737f.png)

**Comment by Christewart** [comment]
So i modified the error message here to add the public key and outpoint we are feeding into it, it does appear to be wrong

https://github.com/bitcoin-s/bitcoin-s/blob/bd94ff15f977ffe2ac087fae3d17c2a7167e332c/core/src/main/scala/org/bitcoins/core/wallet/utxo/InputSigningInfo.scala#L38

```
java.lang.IllegalArgumentException: requirement failed: Cannot have signers that do not sign for one of Vector(ECPublicKey(029c1ff414edd7b913f0822f26c72d56f195791636fcc0e8b5cae1c034051a8580)) , given keys=Vector(ECPublicKey(0327df77731d9ad9c9f41c83b714efc4086d9358916565aefbb14f43dde79064e8)), outPoint=TransactionOutPoint(d10456801b80202210d1c86f9ddbbee125bfa19f1940f6ba44b7b94b1c9ca8b8:1)
	at scala.Predef$.require(Predef.scala:340)
	at org.bitcoins.core.wallet.utxo.InputSigningInfo.$init$(InputSigningInfo.scala:40)
	at org.bitcoins.core.wallet.utxo.ScriptSignatureParams.<init>(InputSigningInfo.scala:68)
	at org.bitcoins.core.api.wallet.db.SpendingInfoDb.toUTXOInfo(SpendingInfoDb.scala:204)
	at org.bitcoins.core.api.wallet.db.SpendingInfoDb.toUTXOInfo$(SpendingInfoDb.scala:186)
	at org.bitcoins.core.api.wallet.db.SegwitV0SpendingInfo.toUTXOInfo(SpendingInfoDb.scala:30)
	at org.bitcoins.core.api.wallet.db.SpendingInfoDb.toUTXOInfo(SpendingInfoDb.scala:183)
	at org.bitcoins.core.api.wallet.db.SpendingInfoDb.toUTXOInfo$(SpendingInfoDb.scala:177)
	at org.bitcoins.core.api.wallet.db.SegwitV0SpendingInfo.toUTXOInfo(SpendingInfoDb.scala:30)
	at org.bitcoins.wallet.internal.FundTransactionHandling.$anonfun$fundRawTransactionInternal$24(FundTransactionHandling.scala:140)
	at scala.collection.immutable.Vector1.map(Vector.scala:1810)
	at scala.collection.immutable.Vector1.map(Vector.scala:348)
	at org.bitcoins.wallet.internal.FundTransactionHandling.$anonfun$fundRawTransactionInternal$23(FundTransactionHandling.scala:136)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)


```

**Comment by Christewart** [comment]
This exists as far back as  874a96eb1e0bfe75997d5152537fcfe8f0ded005 , but i can't go back further without screwing up migrations. 

Here is the `addresses` table entry as a path

>sqlite> select hd_purpose,hd_coin,account_index,hd_chain_type,address_index from addresses where "pubkey"='029c1ff414edd7b913f0822f26c72d56f195791636fcc0e8b5cae1c034051a8580';
84|1|0|0|2

in the addresses table, but if we look at `txo_spending_info` 

>7|b8a89c1c4bb9b744baf640199fa1bf25e1bedb9d6fc8d1102220801b805604d101000000|5|20000000|m/84'/1'/0'/0/2||020021029c1ff414edd7b913f0822f26c72d56f195791636fcc0e8b5cae1c034051a8580|d10456801b80202210d1c86f9ddbbee125bfa19f1940f6ba44b7b94b1c9ca8b8|000000000000003ad317ba9632a5377f2a475c94d8f7ddc173aadcb0398c1d06|ConfirmedReceived

You see we have `m/84'/1'/0'/0/2` 

Here is the path in the `addresses` table:

>sqlite> select hd_purpose,hd_coin,account_index,hd_chain_type,address_index from addresses where "pubkey"='029c1ff414edd7b913f0822f26c72d56f195791636fcc0e8b5cae1c034051a8580';
84|1|0|0|2

So is it to do with hardening?

**Comment by Christewart** [comment]
So added a `println()` here

https://github.com/bitcoin-s/bitcoin-s/blob/bd94ff15f977ffe2ac087fae3d17c2a7167e332c/core/src/main/scala/org/bitcoins/core/api/wallet/db/SpendingInfoDb.scala#L180

>Deriving path=m/84'/1'/0'/0/2

So it appears that the path we are passing into derive the pubkey is correct, is the public key stored in `addresses` wrong?

EDIT: Here is the p2wpkh script:

>sqlite> select * from pub_key_scripts where id=5;
5|16001484918eacb5f7e6cbfbfabe6cf1dc806f8c84c9a1|witness_v0_keyhash

and if you take the public keys in error messages above: 

```scala
scala> val pubKey1 = ECPublicKey.fromHex("029c1ff414edd7b913f0822f26c72d56f195791636fcc0e8b5cae1c0340
51a8580")
val pubKey1: org.bitcoins.crypto.ECPublicKey = ECPublicKey(029c1ff414edd7b913f0822f26c72d56f195791636fcc0e8b5cae1c034051a8580)

scala> val pubKey2 = ECPublicKey.fromHex("0327df77731d9ad9c9f41c83b714efc4086d9358916565aefbb14f43dde
79064e8")
val pubKey2: org.bitcoins.crypto.ECPublicKey = ECPublicKey(0327df77731d9ad9c9f41c83b714efc4086d9358916565aefbb14f43dde79064e8)

scala> val p2wpkh1 = P2WPKHWitnessSPKV0(pubKey1)
val p2wpkh1: org.bitcoins.core.protocol.script.P2WPKHWitnessSPKV0 = wpkh(84918eacb5f7e6cbfbfabe6cf1dc806f8c84c9a1)

scala> val p2wpkh2 = P2WPKHWitnessSPKV0(pubKey2)
val p2wpkh2: org.bitcoins.core.protocol.script.P2WPKHWitnessSPKV0 = wpkh(776acef716f529410fd3682388c53f0625ec0b80)

scala> p2wpkh1.asm
val res5: Seq[org.bitcoins.core.script.constant.ScriptToken] = Vector(OP_0, BytesToPushOntoStackImpl(20), ScriptConstantImpl(ByteVector(20 bytes, 0x84918eacb5f7e6cbfbfabe6cf1dc806f8c84c9a1)))

scala> p2wpkh2.asm
val res6: Seq[org.bitcoins.core.script.constant.ScriptToken] = Vector(OP_0, BytesToPushOntoStackImpl(20), ScriptConstantImpl(ByteVector(20 bytes, 0x776acef716f529410fd3682388c53f0625ec0b80)))
```

So it appears that `pubKey1` is correct that is in `addresses` (according to the utxo onchain), but that does not correspond to the key we are generating based off of information in `txo_spending_info`

**Comment by Christewart** [comment]
This is the address in question, for sanity checks: https://blockstream.info/testnet/address/tb1qsjgcat947lnvh7l6hek0rhyqd7xgfjdpyaf3tj

**Comment by benthecarman** [comment]
I am trying to figure out where the `0327df77731d9ad9c9f41c83b714efc4086d9358916565aefbb14f43dde79064e8` key is coming from. Locally I did
```
 val xpub = ExtKey.fromString(
      "vpub5YLxxXKmTVJKmmf3YNjjsaiVjbzZF7toU99LUvw2nGo9z4kvxh6NCpXd46KSpDNFohNoNuU1hPkdHs6Ngw3xs9et9EXyvJbq5FrBYRChjU2")

   
    0.until(100).map { i =>
      0.until(100).map { j =>
        val key =
          xpub.deriveChildPubKey(BIP32Path.fromString(s"m/$i/$j")).get.key
        if (
          key.hex == "0327df77731d9ad9c9f41c83b714efc4086d9358916565aefbb14f43dde79064e8"
        ) {
          println(i)
          println(j)
        }
      }
    }
```
which output nothing, maybe it is generating a key from the wrong purpose, coin type, or account?

**Comment by Christewart** [comment]
So my current thinking is there is a very weird relationship between `fromAccount` and the `keyManagerOpt` parameters inside of `fundRawTransactionInternal`. I'm still investigating though.

**Comment by Christewart** [comment]
Some more information, it apperas that my expected xpub (from `wallet_accounts`) is different than my actual xpub for the account i am getting from the key manager:

```scala
    val addrInfosWithUtxoF: Future[
      Vector[(SpendingInfoDb, Transaction, AddressInfo)]] = {
      for {
        selectedUtxos <- selectedUtxosF
        _ = selectedUtxosF.failed.foreach(err =>
          logger.error("Error selecting utxos to fund transaction ", err))
        _ = logger.error(s"Root xpub=${keyManagerOpt.get.getRootXPub}")
        _ = {
          val expectedAccountXpub = fromAccount.xpub
          val actualAccountXpub = {
            keyManager.deriveXPub(fromAccount.hdAccount).get
          }

          require(expectedAccountXpub == actualAccountXpub,
                  s"Expected xpub and actual xpub differ!" +
                    s"expected=${expectedAccountXpub}" +
                    s"actual=${actualAccountXpub}")
           //...
        }
```

outputs: 

> requirement failed: Expected xpub and actual xpub differ!
expected=vpub5YLxxXKmTVJKmmf3YNjjsaiVjbzZF7toU99LUvw2nGo9z4kvxh6NCpXd46KSpDNFohNoNuU1hPkdHs6Ngw3xs9et9EXyvJbq5FrBYRChjU2
actual=vpub5Yx748dAkXVXCdmBWhtWK9CFNnFKin2XrYHmLtFFTsWDUwjybrtcCHVDSAdqLHYLME7m4ToxWrwBYkN9SDisfv2J42QeW6Fw4HHBRd2h16R

```

**Comment by Christewart** [comment]
So the root cause of this seems to be that I had incorrectly cached xpubs

I deleted my entire `$HOME/.bitcoin-s/testnet3/walletdb.sqlite` and re-created the wallet from the _same_ encrypted seed

>2020-09-01T18:23:17 INFO [WALLET] Initializing key manager
2020-09-01T18:23:18 INFO [WALLET] Creating new wallet
2020-09-01T18:23:18 INFO [WALLET] Created account=AccountDb(tpubDCjb411SPoHwZSN1SouGhG9gZPKzVU8uKmFYitB43Tf5KTaDD3k319PTedrhYtdvafwpRyjc11kBTK9mBmy7TRDQFksk1BJCmU4U7ss7VAZ,m/44'/1'/0') to DB
2020-09-01T18:23:18 INFO [WALLET] Created account=AccountDb(vpub5Yx748dAkXVXCdmBWhtWK9CFNnFKin2XrYHmLtFFTsWDUwjybrtcCHVDSAdqLHYLME7m4ToxWrwBYkN9SDisfv2J42QeW6Fw4HHBRd2h16R,m/84'/1'/0') to DB
2020-09-01T18:23:18 INFO [WALLET] Created account=AccountDb(upub5ErrMuGSkqtBepf426agtLMWNR7VKs2uzxSnEDWxPDhtgtGoSTtfT65en3SwmxvXye9uAd8AVqkbAmQaqsNBbcCe2m62JXb2ek4eVdNfbh4,m/49'/1'/0') to DB
2020-09-01T18:23:18 DEBUG [WALLET] Created root level accounts for wallet

My previous wallet had these xpubs: 

>sqlite> select xpub from wallet_accounts;
tpubDDB7ZQP9KJvPHtJZ4EDeQUBYtj8xDSsgtrt68gFWybuqUYg1ve8uTsATBGznTyUuMtX2TmPQ9EobqTYjuW4B4wpnMdcQ8X8xKp4GyTwPR2j
vpub5YLxxXKmTVJKmmf3YNjjsaiVjbzZF7toU99LUvw2nGo9z4kvxh6NCpXd46KSpDNFohNoNuU1hPkdHs6Ngw3xs9et9EXyvJbq5FrBYRChjU2
upub5ERLukDj43Lhi9226XVpdDwpDMZsp1Gva6i26B3g9S8T3cznC3dmQXWwCZjCEZfhF3N1wvj5NEJh9986kWWfZGvARzDBTrdtPncsQFGCmjM

**Comment by Christewart** [comment]
I'm not sure how this happened, i'm closing the issue for now.
