### ISSUE TITLE
Wallet via bitcoind rpc rather than bitcoin-s p2p

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1918]
Talking with Nicolas Dorier this morning he said it would be _very_ nice to have way to use a DLC wallet with just a normal bitcoind rpc client _and_ a _pruned_ bitcoind rather than p2p neutrino stuff. We should investigate and comment here with what it will take to get this done

**Comment by NicolasDorier** [comment]
The way we deal with rescan with BTCPay Server is the following:

Our UTXO indexer, NBXPlorer only starts synching from the time the node is fully synched.
It does not attempt to scan past block, it only starts from where the node is.

If a user wants to rescan, we do it as a one time operation via scantxoutset
