### ISSUE TITLE
We are not validating accept message signatures?

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1970]
After setting up a CET with Nicolas Dorier this morning, he is claiming that he sent us an accept message with _invalid_ adapt signatures in it.

I did not get prompted that these signatures were invalid, so i generated valid funding transaction signatures which in theory could lead him to steal money? 

Start of the conversation here:

https://lightningdevkit.slack.com/archives/C012TKK8EJC/p1599148011257700?thread_ts=1599119705.235300&cid=C012TKK8EJC

**Comment by benthecarman** [comment]
Looks like we only validate as the acceptor

**Comment by Christewart** [comment]
We need to verify it here: https://github.com/bitcoin-s/bitcoin-s/blob/a5632a610b4b7f713ee7cb5d89fc6c4eac3d500d/dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala#L393
