### ISSUE TITLE
Outpoints debugging for chris/nicolas

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1980]
**Describe the bug**
It appears that we are adding outpoints to the funding transaction during the `sign` phase that aren't necessary.

Here is the message exchange going back and forth between me and @NicolasDorier

### Offer message

Here is _my_ offer message, note that there is exactly _one_ funding outpoint in my offer message (`965f737e78f1c568a93f13f62fc66df90e9b52d6b4761acce0a9e4da9f5e74f100000000`)

>{
  "contractInfo": [
    {
      "sha256": "74cee5d1545b6926816a8e857a4bedb279b3e97d72885a80fbc1cf37a0d10256",
      "sats": 0
    },
    {
      "sha256": "24e9998b3e3210751a3eee707923376a0fcfb1d28a43da0b02153d8880b9b22c",
      "sats": 100000
    },
    {
      "sha256": "d9298a10d1b0735837dc4bd85dac641b0f3cef27a47e5d53a54f2f3f5b2fcffa",
      "sats": 60000
    }
  ],
  "oracleInfo": "156c7d1c7922f0aa1168d9e21ac77ea88bbbe05e24e70a08bbe0519778f2e5daea3a68d8749b81682513b0479418d289d17e24d4820df2ce979f1a56a63ca525",
  "pubKeys": {
    "fundingKey": "03b0cf58eac2fecd14f99f6448baf6fd98c342a544fab268dcccd441fff84d6fb1",
    "payoutAddress": "tb1q5dzqdevpx5995kjllsjuqwmzw5zujl687zamxe"
  },
  "totalCollateral": 60000,
  "fundingInputs": [
    {
      "outpoint": "965f737e78f1c568a93f13f62fc66df90e9b52d6b4761acce0a9e4da9f5e74f100000000",
      "output": "a0860100000000001600143e7e7ba2f1b61013632c7be560210c710a82d077"
    }
  ],
  "changeAddress": "tb1qu2rlp5z27yjkr434e4ss3mxxmkhzp4samnzv5g",
  "feeRate": 5,
  "timeouts": {
    "contractMaturity": 0,
    "contractTimeout": 1
  },
  "eventId": "183ab209172aba1b263a94760e426d8fce6b7363caf9fa7da3c843312ec4a66e"
}

### Accept message

This is what nicolas sends back, he is funding with two outpoints 

`c80e6e868c36c48fa1f3d6f4f962d395a67de4ddde8a8cdafe9976f32b7f8eaa00000000`

>{
  "totalCollateral": 29998600,
  "pubKeys": {
    "fundingKey": "027ba4dd52ea38e18a59a4320540220340e487d7c996f37ebe8019d98138aba946",
    "payoutAddress": "tb1qt3zfhl30xgzjgkwrcez055fprc6xlkdvv8gs8a"
  },
  "fundingInputs": [
    {
      "outpoint": "c80e6e868c36c48fa1f3d6f4f962d395a67de4ddde8a8cdafe9976f32b7f8eaa00000000",
      "output": "604463020000000016001446d78fc82aed5cc20b80d59a5fdfcc3c528d9612"
    }
  ],
  "changeAddress": "tb1qscycs2y4h4mzfhapd5ajdpx2s4ypy049d3cu22",
  "cetSigs": {
    "outcomeSigs": [
      {
        "74cee5d1545b6926816a8e857a4bedb279b3e97d72885a80fbc1cf37a0d10256": "0057fbee416140a75bec2b08f085867739d0f80b8d0182c17868f7faeed69cfc36da2dfcbc660fc5efb563b400e7b7c9d50c49443057ac702f462f0cdcb2990e3f001ed03919818ca93ea8e662c131a1e2f29d6236511d6019126612d90be142314aa89f842a5da772b08bc0215233d94f693b619a9fe3e974a751510f1755a70635ca77b9005658ecc607df2281455f4576fb778bd4146491d107e403927143182c"
      },
      {
        "24e9998b3e3210751a3eee707923376a0fcfb1d28a43da0b02153d8880b9b22c": "017db218cfcb6a1774e80ef35d84d803952dc26147d4e534c678f0a181ebca2b8a698d3456acf0664c1ae965e366c9dc280688f2d27c3df72560f5b7059035232c019557da3e8ebb5c7b2047fa5f66e3dd748ae55163192739deb50ee485d96f3b0a06281c847744c6b7cb29130b2cbc3986afbd8578205f115df77071ce4046c9d982bea182cf9386900dcfc1fcfac93f44322e6c0ff4b0852704b1d6ef7f7ff835"
      },
      {
        "d9298a10d1b0735837dc4bd85dac641b0f3cef27a47e5d53a54f2f3f5b2fcffa": "0064fc3fa8a677d564b7d838548286960482fafc08dbe579b70ce71ecfc06d1717e0c7ddf140fa03a0879ceb1b52847c69df205d7500ffcf5bc771abc741e2fde00035fae49eb1306ad0428f59ada8cd1cf4399b76fef2cd5b91eada4079c1c1a5134b67fc5842a04688ad757b9b47bce9045d5df8da1889b9d0e13082d50d932593130f655fd36c1fe6f3755e7435d93797e3847789b5ef0970840ca95a55a06a1e"
      }
    ],
    "refundSig": "2202027ba4dd52ea38e18a59a4320540220340e487d7c996f37ebe8019d98138aba946473044022063495095bf9dad41e93f10209d1ae4c3671a60e772bb967416d201904c92d26c02204a06f3769c2a207dcd0caf26a44cb99a739579c31481c46dc25250629869c8a101"
  },
  "eventId": "14965dcd10a1f0464c4c5cf7f2e9c67b2bcc6f8a971ccc647d7fec1c885f3afe"
}

### Cet sigs message

This is the CET sigs message I send back to nicolas, i've added a new field called `fundingTx` that contains the raw funding tx. 

>{
  "cetSigs": {
    "outcomeSigs": [
      {
        "74cee5d1545b6926816a8e857a4bedb279b3e97d72885a80fbc1cf37a0d10256": "001a915570fa08f5ce72629a6973e7636d6c5ed7c5127ab9b3760a9a3fe5b8cdaccc35d4a0acaf7878318da52359407df7e17a86009294ec038bd0e5d3d9f62c990193e0d1ec9bb26811b3205342352dddb3b49c86e585ef587369492d9b4c8ec5ee1735a4b39a76067cc1e3160ec2e128d5a06f8542793dbb74612afb544c08dc7e8da468004dfe1e66eff38cc2766bf945822beff82604fedd7130e3fb4771da0b"
      },
      {
        "24e9998b3e3210751a3eee707923376a0fcfb1d28a43da0b02153d8880b9b22c": "00bd4ea64c3be54e8801930c300265e09ebdd4066b308c638ee0011b4da3a7b0819faaf7597618560ba9e4fb7b2bc51e7246213021eeb4670443b9cbbf53c7d5a7000c4075b6ca3c009808232125909d375d0a0636c59a891e372b86e3af2cc8fbcad317c07017c19a191f90f18afe100c2e3c06ff70c020530c5885de4bf1117f9b9c795eb905ff4842d805f6328b0d2bf9bf1b287643cd1ee14a55c74a7e8cc8e6"
      },
      {
        "d9298a10d1b0735837dc4bd85dac641b0f3cef27a47e5d53a54f2f3f5b2fcffa": "019c1d0dabf9350c858130a7e5914a7c371775a1316580213ce07349b290a25d5a4a705e845b9170cf565c951f3f327a68ddf437165400f48abcf79e835dfea3d501c494f9df4623ab9855598cbf5274d90dd46409e7a64232952ec142be3fbf1443a4df3ba9c9b6bcadcf49b93565a4d0fd2932cbac674cd02007f10b06c8648ea8c0d8b88bd1271d17eab5ca973e3858b59e8b178d204c752f0bca159ef9dd49a9"
      }
    ],
    "refundSig": "220203b0cf58eac2fecd14f99f6448baf6fd98c342a544fab268dcccd441fff84d6fb1473044022075bc375d375b9dbe5cd169967b744f30851306475ca07592839b862fe07d379b02201ef11f807736fa6687deefa318f5af75dc706ae776b21065c97aaa38def2acdf01"
  },
  "fundingSigs": {
    "965f737e78f1c568a93f13f62fc66df90e9b52d6b4761acce0a9e4da9f5e74f100000000": [
      "22020348608ae361c5a1aa67d31ba9bd7ee45d4e085c83dfc2e9b76f07551b909ca38148304502210089a334418ef6e67f295d286c26d45efb235462b2eb57d810bebd67e88d74cd48022063b3221fdde307d1ac0d646287bb354a201bef0b86ca9ebf664b015e914401d801"
    ]
  },
  "fundingTx": "0200000004965f737e78f1c568a93f13f62fc66df90e9b52d6b4761acce0a9e4da9f5e74f10000000000ffffffff1c9f8ac973412dd0e31b5a0956d22b3b578026e45c7beaa0dd1940f5702ed8910100000000ffffffffd2c5af3dd37cccc2255d66794cfd8b0a64b6b579f49aae49cbf1fe0ebdec55770000000000ffffffffc80e6e868c36c48fa1f3d6f4f962d395a67de4ddde8a8cdafe9976f32b7f8eaa0000000000ffffffff03b5abca01000000002200209761291b540f7376571772fc28d2c3fc86154f292e8c97f1e1bb62298e44baebc493000000000000160014e287f0d04af12561d635cd6108ecc6ddae20d61dd63f1c03000000001600148609882895bd7624dfa16d3b2684ca8548123ea500000000",
  "eventId": "183ab209172aba1b263a94760e426d8fce6b7363caf9fa7da3c843312ec4a66e"
}

This is what nicolas reports his funding tx to be:

>0200000002965f737e78f1c568a93f13f62fc66df90e9b52d6b4761acce0a9e4da9f5e74f10000000000ffffffffc80e6e868c36c48fa1f3d6f4f962d395a67de4ddde8a8cdafe9976f32b7f8eaa0000000000ffffffff03b5abca01000000002200209761291b540f7376571772fc28d2c3fc86154f292e8c97f1e1bb62298e44baebc393000000000000160014e287f0d04af12561d635cd6108ecc6ddae20d61ddb7d9900000000001600148609882895bd7624dfa16d3b2684ca8548123ea500000000

Here are the outpoints that are funding each tx 

#### Chris

```scala
 val chex2 = "0200000004965f737e78f1c568a93f13f62fc66df90e9b52d6b4761acce0a9e4da9f5e74f10000000000ffffffff1c9f8ac973412dd0e31b5a0956d22b3b578026e45c7beaa0dd1940f5702ed8910100000000ffffffffd2c5af3dd37cccc2255d66794cfd8b0a64b6b579f49aae49cbf1fe0ebdec55770000000000ffffffffc80e6e868c36c48fa1f3d6f4f962d395a67de4ddde8a8cdafe9976f32b7f8eaa0000000000ffffffff03b5abca01000000002200209761291b540f7376571772fc28d2c3fc86154f292e8c97f1e1bb62298e44baebc493000000000000160014e287f0d04af12561d635cd6108ecc6ddae20d61dd63f1c03000000001600148609882895bd7624dfa16d3b2684ca8548123ea500000000"

val ctx2 = Transaction.fromHex(chex2)

ctx2.inputs.foreach(i => println(i.previousOutput))
TransactionOutPoint(f1745e9fdae4a9e0cc1a76b4d6529b0ef96dc62ff6133fa968c5f1787e735f96:0)
TransactionOutPoint(91d82e70f54019dda0ea7b5ce42680573b2bd256095a1be3d02d4173c98a9f1c:1)
TransactionOutPoint(7755ecbd0efef1cb49ae9af479b5b6640a8bfd4c79665d25c2cc7cd33dafc5d2:0)
TransactionOutPoint(aa8e7f2bf37699feda8c8adedde47da695d362f9f4d6f3a18fc4368c866e0ec8:0)
```

#### Nicolas

```scala
 val nhex = "0200000002965f737e78f1c568a93f13f62fc66df90e9b52d6b4761acce0a9e4da9f5e74f10000000000ffffffffc80e6e868c36c48fa1f3d6f4f962d395a67de4ddde8a8cdafe9976f32b7f8eaa0000000000ffffffff03b5abca01000000002200209761291b540f7376571772fc28d2c3fc86154f292e8c97f1e1bb62298e44baebc393000000000000160014e287f0d04af12561d635cd6108ecc6ddae20d61ddb7d9900000000001600148609882895bd7624dfa16d3b2684ca8548123ea500000000"
 val ntx = Transaction.fromHex(nhex)
 ntx.inputs.foreach(i => println(i.previousOutput))
TransactionOutPoint(f1745e9fdae4a9e0cc1a76b4d6529b0ef96dc62ff6133fa968c5f1787e735f96:0)
TransactionOutPoint(aa8e7f2bf37699feda8c8adedde47da695d362f9f4d6f3a18fc4368c866e0ec8:0)
```

### Conclusion

it appears that @nicolasdorier funding transaction is correct, and ours in correct, probably due to an internal caching issue? There is no way we should have 4 outpoints funding the transaction.

**Comment by NicolasDorier** [comment]
It should be noted that my eventId is maybe the same of a previous test... might it be this?

**Comment by benthecarman** [comment]
If you're reusing an event id it will cause problems.

A temp fix you could do is drop the unwanted inputs from the funding inputs db
