### ISSUE TITLE
Make ChainApi.getHeadersBetween() return inclusive 'from' and 'to'

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1996]
Currently we _exclude_ the `from` parameter for `ChainApi.getHeadersBetween()` 

This makes it hard to use this method for cases of using the genesis block, as you can't specify a parent for the genesis block I'm running up against this in #1969 when attempting to sync filters for the genesis block. 

We should change the behavior of this method to _include_ the `from` _and_ `to` headers in range of block headers returned

https://github.com/bitcoin-s/bitcoin-s/blob/47fb9e0530d07105cdd1472246b5ef612a36a6ce/core/src/main/scala/org/bitcoins/core/api/chain/db/ChainApi.scala#L147-L150

Here is where i specifically need it: 

https://github.com/bitcoin-s/bitcoin-s/blob/47fb9e0530d07105cdd1472246b5ef612a36a6ce/chain/src/main/scala/org/bitcoins/chain/blockchain/sync/FilterSync.scala#L99

**Comment by benthecarman** [comment]
You should be able to just do `missing :+ ourBestHeader`

**Comment by Christewart** [comment]
> You should be able to just do `missing :+ ourBestHeader`

This is what I did, however it doesn't make sense to have to do this _everywhere_ in the codebase to account for genesis block quereies
