### ISSUE TITLE
Break dependency of node project on bitcoindRpc

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2004]
I don't think this is required? 

https://github.com/bitcoin-s/bitcoin-s/blob/79ca91029c3cc1eb35e9e18edee08c8f8c3347fc/build.sbt#L391

**Comment by Christewart** [comment]
I think there is going to need to be a new module made named `async-utils` or something like that. It seems that we dependened on `bitcoindRpc` in the `node` project because we needed access to `AsyncUtil` which current lives in the `bitcoindRpc` project.

**Comment by benthecarman** [comment]
Can probably just move that to commons?

**Comment by benthecarman** [comment]
Looks like it is also because of this

https://github.com/bitcoin-s/bitcoin-s/blob/master/node/src/main/scala/org/bitcoins/node/models/Peer.scala#L29

**Comment by benthecarman** [comment]
Maybe we can move `BitcoindInstance` to commons. We would need to move the whole `config` package however
