### ISSUE TITLE
bitcoin-s.keymanager.aespassword

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2012]
This proposes to add a new configuration option for specifying the password for decrypting your mnemonic seed on disk

This is related to #972 

This allows you to use environment variables as well to set the the password, for instance you can do 

```
bitcoin-s { 
  key-manager { 
    mnemonic-password=${MNEMONIC_PASSWORD}
  } 
}
```

Maybe this should be done for the BIP39 password too? :man_shrugging:

**Comment by benthecarman** [comment]
I think this should be something entered in on startup not a config file option

**Comment by Christewart** [comment]
> I think this should be something entered in on startup not a config file option

Hmm.. I'm conflicted on this. Do you have security concerns with it sitting on disk? Because that is the reason I added the environment variable in the config file `MNEMONIC_PASSWORD`

You can also pass it in on the command line when starting with 

>./bitcoin-s-server -Dbitcoin-s.keymanager.aespassword=....

I believe https://github.com/lightbend/config#overview

**Comment by benthecarman** [comment]
I think a lot of users use the same password for everything so if they use that password for their mnemonic then they could have it just sitting in a raw text file.

**Comment by Christewart** [comment]
> I think a lot of users use the same password for everything so if they use that password for their mnemonic then they could have it just sitting in a raw text file.

Ok i think this is our disagreement, I was imaging this being used in cloud environments were you already have this credential pre-configured, whereas you are thinking of individual users on a laptop. I see your point with individual users, but I'm not sure how this would work in a cloud environment. How would you pass in this password in a situation where the key-manager is remote?

**Comment by benthecarman** [comment]
> How would you pass in this password in a situation where the key-manager is remote?

That's a good point, maybe can alleviate with some middle ware but what you proposed is a lot more user friendly
