### ISSUE TITLE
Choosing a signing key for a `DLCOracle`

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-s/bitcoin-s#2096]
Currently, the `DLCOracle` is using an `ExtPrivateKeyHardened` for its seed. This makes it safer when getting nonces as they all need to be from hardened paths to be secure.

However, since we are using a `ExtPrivateKeyHardened` it makes it so we cannot use a standard derivation path for the signing key. This is a problem is the user wants to stake funds under this signing key. This problem arises because when they then want to be able to spend these funds. Ideally the user could enter their seed into a wallet and it can handle the spending, however using a `ExtPrivateKeyHardened` will not permit that because we will no longer be using a standard derivation path.

I see there are 4 options:

- Continue using `ExtPrivateKeyHardened` and have our signing key be on a non-standard path and provide a way to export the private key.
	- Many wallets support importing a private key so it wouldn't be a huge deal to spend it later

- Stop using `ExtPrivateKeyHardened` and trust that we implement it correctly to only use hardened paths.
	- On the PR there is already checks for this https://github.com/bitcoin-s/bitcoin-s/pull/2094/files#diff-7f6f022a7b4ab34bb53e4ae817becbe9R81

- Use a separate seed for signing
	- This makes backups harder and can confuse users

- Make the `DLCOracle` able to spend natively
	- imo this is the worst option as then the oracle needs to become chain aware and require a lot more overhead.

**Comment by benthecarman** [comment]
Imo, option 2 is the best from a UX perspective as users will expect to be able to take their seed an import it into a wallet to be able to spend it.

**Comment by nkohen** [comment]
I'm in favor of Option 1, all users wishing to spend staked funds (which is not normal) should be able to import a private key into another wallet (we just need to support exporting the key). There is no reason to prioritize making it easy to spend staked funds.

Also I'd like to comment that wrt the fourth option the oracle does not need to become chain aware or require any kind of overhead, just make an endpoint (if you want to) where you feed it a txid for the staked funds, and an address you'd like to spend to and it creates a transaction spending the staked funds and signs and returns this serialized tx.
