### ISSUE TITLE
[Question] Runtime error in java 

### ISSUE THREAD

**Issue by pedr0-fr** [bitcoin-s/bitcoin-s#2118]
I am trying to use bitcoin-s in a Java project and I am getting a runtime error. My code is:

```java
import org.bitcoins.core.protocol.transaction.Transaction;
import org.bitcoins.core.protocol.transaction.Transaction$;
import scodec.bits.ByteVector;
import scodec.bits.ByteVector$;
import javax.xml.bind.DatatypeConverter;

public class TransactinDecoding {

    public static void main(String[] args){
        String rawTx = "02000000000101762ebd86db44c998e8c55dfabbb6aa5faf0fdb0a90e3f98bbb968dc0339f7f0101000000171600146cb11acd9881d191a64c2d96515c1cf9df56ddc6feffffff029ae400000000000017a914886d7f57a39af53636290380a251ea3dd3a0c43287bae7ef000000000017a91444211c7b7bc0a569e15eb62bee84368098c8d9ed870247304402200514cf8d00571c0cbcf76269bd3d2f1fcaeb4a725e28e01da4125d30fc951ba402200595bb9441b4917386b6a71a8ef33a24bfa99d35230be61980442d479adcabf001210288ae983ed76a8336dcbcc31367d0b0436957b1272a46e958d906ef2ac525e0250ceb0900";
        byte[] serialized = DatatypeConverter.parseHexBinary(rawTx);
        ByteVector byteVector = ByteVector$.MODULE$.apply(serialized);
        Transaction scalaTx = Transaction$.MODULE$.fromBytes(byteVector); // <<< error here

        System.out.println(scalaTx.totalSize());
        System.out.println(scalaTx.vsize());
    }
}
```

The error is:

```java
Exception in thread "main" java.lang.NoSuchMethodError: scala.runtime.ScalaRunTime$.wrapByteArray([B)Lscala/collection/immutable/ArraySeq;
    at org.bitcoins.core.protocol.transaction.WitnessTransaction$.<clinit>(Transaction.scala:313)
    at org.bitcoins.core.protocol.transaction.Transaction$.fromBytes(Transaction.scala:118)
    at co.bitpost.api.TransactinDecoding.main(TransactinDecoding.java:22)
```

My maven dependencies include:

```
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <version>2.13.3</version>
    </dependency>
    <dependency>
      <groupId>org.bitcoin-s</groupId>
      <artifactId>bitcoin-s-core_2.13</artifactId>
      <version>0.4.0</version>
    </dependency>
```

I tried to several different versions of the scala library (mostly 2.12.x and 2.13.x) but the error is the same or gets worse with version 2.12.x (compilation error `Error:(21, 52) java: cannot access scala.collection.IterableOnce
  class file for scala.collection.IterableOnce not found`).

I'm fairly new to scala, any idea how I can solve this?

**Comment by Christewart** [comment]
What version of java are you running?

This seemed to work for me, here was my `pom.xml` 

><?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>bitcoin-s-java</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.8.1</version>
        </dependency>
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>2.13.3</version>
        </dependency>
        <dependency>
            <groupId>org.bitcoin-s</groupId>
            <artifactId>bitcoin-s-core_2.13</artifactId>
            <version>0.4.0</version>
        </dependency>
    </dependencies>

</project>

and here is the output of the code snippet you posted above:

>247
166

**Comment by pedr0-fr** [comment]
@Christewart Thanks for the quick answer! I am using Java 11. I reproduced your finding that it works in a new project and it was driving me crazy because the pom.xml was practically the same in both my projects but it was not working on my existing one. After some digging in the run command generated by IntelliJ I noticed it was passing an old java library in the classpath:

```
/home/pedro/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.4.jar
/home/pedro/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.12.4.jar
/home/pedro/.ivy2/cache/org.scala-lang/scala-library/srcs/scala-library-2.12.4-sources.jar
/home/pedro/.ivy2/cache/org.scala-lang/scala-reflect/srcs/scala-reflect-2.12.4-sources.jar
```

After deleting the folder `/home/pedro/.ivy2/cache/org.scala-lang`, it worked! Thank you!

**Comment by Christewart** [comment]
Glad to help :-)! Keep issues coming if you have them
