### ISSUE TITLE
Add secp256k1jni bindings for the schnorrsig module in libsecp256k1

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#212]
It looks like schnorr signature support is starting to be added to bitcoin-core/secp256k1. 

We need to modify our java interface to support schnorr signatures: 

https://github.com/bitcoin-s/bitcoin-s-core/tree/master/secp256k1jni

https://github.com/bitcoin-core/secp256k1/pull/558

**Comment by Christewart** [comment]
There is now jni bindings courtesey of @floreslorca and the bitcoin-abc team https://github.com/Bitcoin-ABC/bitcoin-abc/tree/master/src/secp256k1/src

**Comment by nkohen** [comment]
This binding is currently maintained on the `schnorr-dlc` branch on this commit: https://github.com/bitcoin-s/bitcoin-s/commit/4548dc045bbc2e931812b084402cabde6d684dcf
