### ISSUE TITLE
update rpc client to suport 0.17.0

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#213]
There is an open ended question of how we want to support multiple versions of bitcoind rpc client, open to suggestions

**Comment by torkelrogstad** [comment]
How do handle deprecated RPC calls? 

For example: 

```bash
$ bitcoind --version
Bitcoin Core Daemon version v0.17.0.1
...

$ bitcoin-cli listaccounts
error code: -32
error message:
listaccounts is deprecated and will be removed in V0.18. To use this command, start bitcoind with -deprecatedrpc=accounts.
```

That means 0.17 can handle `listaccounts`, but that it's probably not worth it to support the RPC call, IMO. If we were to support it we should also support starting `bitcoind` with different startup flags and all that, and that doesn't sound like fun.
