### ISSUE TITLE
Write configuration resolution test cases for AppConfig

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2147]
According to the [typesafe config docs](https://github.com/lightbend/config#standard-behavior), this is the order of 

>
    1. system properties
    2. application.conf (all resources on classpath with this name)
    3. application.json (all resources on classpath with this name)
    4. application.properties (all resources on classpath with this name)
    5. reference.conf (all resources on classpath with this name)

I don't think we honor this at the moment -- specifically with System properties. We should write sanity unit test cases in `dbCommonsTest` to make sure we behave as expected. 

Here is what I had in mind 

```scala
      //set system property
      System.setProperty("bitcoin-s.sqlite.profile",
                         "slick.jdbc.PostgresProfile$")
      val chainConfig = ChainAppConfig(dataDir)
      val assertF = for {
        //resolve the config
        _ <- chainConfig.start()
      } yield {
        //should be instance of postgresprofile as that is what i set the
        //system property to be
        assert(chainConfig.slickDbConfig.profile.isInstanceOf[PostgresProfile])
      }
```

Unfortunately we can't test this with `bitcoin-s.datadir` until #2114  is complete.

**Comment by benthecarman** [comment]
An easier check for the system properties would be to set something like `bitcoin-s.wallet.requiredConfirmations`
