### ISSUE TITLE
Add CI row to actually build and run binaries

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2161]
This is to prevent things like #2160 in the future. Regresions in actually running standalone servers because of easy to miss things like NullPointerExceptions on startup.

**Comment by Christewart** [comment]
Maybe we can actually already add this to rows that test things like `appServer` and `oracleServer` so we can not waste CI minutes on this? Perhaps we can even cache the binaries some how from the compile task?

**Comment by benthecarman** [comment]
When we add these we should verify that the log file is being created in the correct location

**Comment by Christewart** [comment]
We now have `appServerTest/test` that essentially does this
