### ISSUE TITLE
De-Futurify Sign Interface

### ISSUE THREAD

**Issue by nkohen** [bitcoin-s/bitcoin-s#2174]
Currently, any operation that requires signing (including mock/fake signing) returns a `Future` because this is what the `Sign` interface does (to support HWW and HSMs in the future).

I think everyone agrees that mock signing should not incur a `Future`.

Normal hot-key signing is a little trickier, as if we want the same code path to work for both hot keys and cold keys then we need the interface to be the same which either means adding `Future`s to hot-keys or Awaiting them for cold keys.

Alternatively there's an argument to be made that they should have different signing code paths as one is automated and the normal case (most common today anyway) so we don't want to add unnecessary complexity to it while the other is the special case where special, possibly manual, steps are being taken anyway.

**Comment by Christewart** [comment]
This was taken care of in #2652
