### ISSUE TITLE
Library publishing issues on CI

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2189]
This seems to be introduced in #2177 . I don't see how it can actually be this PR that introduced an issue though since it's docs only. 

Only 1 build has successfully published to sonatype since this PR was merged though. The reason the build usually fails is because of a timeout due to inactivity

![Screenshot from 2020-10-14 09-49-03](https://user-images.githubusercontent.com/3514957/96005871-83451c00-0e02-11eb-89aa-ddcc553560dd.png)

Here is a link to a failing build https://travis-ci.org/github/bitcoin-s/bitcoin-s/jobs/735714613

There seems to be one PR that did sucessfully publish if you look at commits into master: https://github.com/bitcoin-s/bitcoin-s/commits/master

This was on the merge of #2178 https://travis-ci.org/github/bitcoin-s/bitcoin-s/builds/735426634

If you look carefully at this merge though, it seems it took 36 minutes (!) 

https://travis-ci.org/github/bitcoin-s/bitcoin-s/jobs/735426635

### Slow regression over time

If you look over CI history to see how long our publish task runs, it seems it has been growing exponentially over the past few months. 

This merge occurred on #2048 (2020-09-22) and publishing the library took 24 minutes. 

https://travis-ci.org/github/bitcoin-s/bitcoin-s/builds/729693995

If we go back further to #1990 (2020-09-12) publishing the library took 17 minutes

https://travis-ci.org/github/bitcoin-s/bitcoin-s/builds/725899684

and if we go back to #1951 (2020-09-01) publishing the library took 14 minutes

https://travis-ci.org/github/bitcoin-s/bitcoin-s/builds/723285250

So as you can see there has been a slow regression going on for quite some time.

**Comment by Christewart** [comment]
This seems to have been fixed on #2190, the problem was that we were not caching new modules on CI.

**Comment by benthecarman** [comment]
We also cleared the cache of travis, might also be a fix

https://travis-ci.org/github/bitcoin-s/bitcoin-s/caches
