### ISSUE TITLE
Oracle Announcement signature needs to be checked

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2196]
It appears that we do not actually check [`OracleAnnoucementTlv`](https://github.com/bitcoin-s/bitcoin-s/blob/aca5e82bcd7cf8053db598dc818c9c62488d3fe6/core/src/main/scala/org/bitcoins/core/protocol/tlv/TLV.scala#L345) signatures anywhere. We need to do this similar to how we do it in `LnInvoice`: 

https://github.com/bitcoin-s/bitcoin-s/blob/a9ad927a9c9ce6ab9a26fde0762ae5b03ac4f530/core/src/main/scala/org/bitcoins/core/protocol/ln/LnInvoice.scala#L24

**Comment by benthecarman** [comment]
We first need to standardize the announcement signature

**Comment by Christewart** [comment]
> We first need to standardize the announcement signature

I'm not sure what you mean this? Isn't this specified in https://github.com/discreetlogcontracts/dlcspecs/pull/108 

 https://github.com/discreetlogcontracts/dlcspecs/blob/ee69d8dab1973cdc2dad95321bf2aa068387adaa/Messaging.md#version-0-oracle_announcement 

Are you just saying that it needs peer review and to be merged before it's considered final? Regardless, since we have it in bitcoin-s, it should be checked no? Shouldn't what we do in bitcoin-s be the first draft of the proposal?

**Comment by benthecarman** [comment]
Right now the announcement sig is just over the SHA256 of the `OracleEventTLV`, but we're gonna move it to a tagged hash likely in the future. So if we add the invariant old announcements won't be compatible once we implement the tagged hash

**Comment by Christewart** [comment]
> Right now the announcement sig is just over the SHA256 of the `OracleEventTLV`, but we're gonna move it to a tagged hash likely in the future. So if we add the invariant old announcements won't be compatible once we implement the tagged hash

From @nkohen 

>we could create a fictitious version that doesn't match the announcement in the spec just for our own internal dev purposes if we wanted?

**Comment by benthecarman** [comment]
Currenlty this is not enforced through an invariant, we still have the `validateSignature` function.

We could turn this on to enforce the signature validation, however, some will break when we fix the bug with the digit decomp serialization using `uint16` instead of `bigsize`

**Comment by Christewart** [comment]
So it seems to me this would be best added on the v1 announcements as an invariant, but won't be able to retroactively be applied to v0? 

If so, give me a :+1: and i'll move it to a different issue

**Comment by Christewart** [comment]
Cannot be done for v0 announcements
