### ISSUE TITLE
Allow the ability to update passwords

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2221]
Currently in the code base we have two passwords 

1. the aes password used to encrypt the wallet
2. the bip39 mnemonic password 

We need to allow users to change these passwords

Related to #972

**Comment by benthecarman** [comment]
Changing the bip39 password isn't really possible. If you change the bip 39 password it will change the resulting seed and the user won't have access to their funds, to safely change you would need to send all of the funds to new the seed. We could allow multiple wallets with different bip39 passwords (coldcard allows this).

Changing the aes password should be completely doable however.
