### ISSUE TITLE
wallet_dlcs table does not store full HDPath in database

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2223]
It stores the `account` and `address index`, but makes no mention of the `change`? 

https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#path-levels

here is what my db looks like 

>sqlite> select * from wallet_dlcs;
2a7cc0ebe8c418359751cf0e2770dfbcf4fdc9dc3882331262d6e36f3e26b48e|Signed|1|m/84'/0'/0'|6|||
aa56981bc08e71c6eb291797a77c7933b9ddd734b852411255c1e39d2a123671|Signed|1|m/84'/0'/0'|8|||

I'm guessing i just need to add `0` to the path as it isn't a change address? `0` is normal receiving funds

**Comment by benthecarman** [comment]
It is always 0 because these are keys we are receiving with, not for change. Could probably be changed to add it however
