### ISSUE TITLE
Received PSBT witness utxo that doesn't contain full funding transaction

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2224]
I'm trying to sign a PSBT that was given to me by a user. It's spending a P2WSH 2 of 2 multisig output. 

I'm using this shim code [here](https://github.com/Christewart/bitcoin-s-core/commit/0017500f80113758747823de6d76514ec42e5cf6) as we don't seem to have the ability to sign this with our `bitcoin-s-cli` (#2222)

The problem with this shim code is this line 

https://github.com/Christewart/bitcoin-s-core/commit/0017500f80113758747823de6d76514ec42e5cf6#diff-cb87f0cfe59881832f36fde84e19103e63c28a5e4d628abc193ab05d8e318250R51

if you follow this code, the problems start here: 

https://github.com/bitcoin-s/bitcoin-s/blob/57689a74433b893463876053d2dd0c824e46a76e/core/src/main/scala/org/bitcoins/core/psbt/PSBTMap.scala#L629-L645

Specifically the 

>val txVec = getRecords(NonWitnessUTXOKeyId)

Since the tx I received is a witness txo, we end up erroring on this line. I thought our witness txo problems (not having the full funding tx) were solved in #2204 

https://github.com/bitcoin-s/bitcoin-s/blob/57689a74433b893463876053d2dd0c824e46a76e/core/src/main/scala/org/bitcoins/core/psbt/PSBTMap.scala#L644

with error 

>[info] 2020-10-30T13:36:00UTC ERROR [PSBTMain$] Failed to sign PSBT
[info] java.util.NoSuchElementException: empty.head
[info]  at scala.collection.immutable.Vector.head(Vector.scala:277)
[info]  at org.bitcoins.core.psbt.InputPSBTMap.toUTXOSigningInfo(PSBTMap.scala:644)
[info]  at org.bitcoins.core.wallet.signer.BitcoinSigner$.sign(Signer.scala:287)
[info]  at org.bitcoins.core.psbt.PSBT.sign(PSBT.scala:158)
[info]  at org.bitcoins.server.PSBTMain$.$anonfun$startup$9(PSBTMain.scala:51)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
[info]  at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
[info]  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]  at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)

To get around this, I had to manually fetch teh funding transaction and then add it here

```scala
val hashType =
  if (hashTypeVec.size == 1) hashTypeVec.head.hashType
  else HashType.sigHashAll

val inputInfo = toInputInfo(txIn, conditionalPath, Vector(signer.publicKey))

val tx = Transaction.fromHex("020000000001052992286a3079207e73f621e89313a55f6ad087081c0b2cda0cf5d759b475b49a0000000000ffffffff694e2d0f6ba5aba4d89a037a6a67e601b1efafd638291ed4f3672fef407174824600000000ffffffff17efa6071258823ad1d288c6e3856d9a0e657804333878e853ca8b772243bea43700000000fffffffffe614bb5bcd56c0e6bc34a738f324f64fd9f15ff3e84770fc7f0ec526c3dcd275100000000ffffffffda1584f286a4350f9fb72b26212649433d5b0ced367972417e2a2d86091118e93c00000000ffffffff039ae7f50500000000220020faefdc90c854b79fb7926968ff78f0bfdcca86cbcfd37d7f3bcce6a35e577e2d2c6c21010000000016001432427ecb053a86c25c35611e1ccd6a88f7dc31364f4f2c00000000001600149a9f6d55af7d28fe61358895a2ac3d436d084ae902483045022100853ae8e248f508349f8f8205a2870ec0af9ec6ccc953bcaa4990f97888aa020302206bd7c7a890ab2528cb12da2e53d60cb2f14afe30479a6e39a9e5ceec6a1942ce012102576fa220636a325ce95f3964b71ed158514bdaece6709100739f9995d53a8e1c02473044022064cd2ce30155116d376df065bcda14f1130efbb9759c5d0da04c1e2c523e3baa022070ba55ea5791761e8cfd530086bd7b03a00f7812d454eb4a0218ea85cda3cd0b0121022bf2a6340f9869649b794f8cb5801973e5d342cd1f9f6603dad408dbb910a9c90247304402200a61174305b75bec338613cf71ecb269c5ecbf4c6eef46486497c4fe6874454d02206095ffac0d1d1567364fd9780766f0304285e87ab8a7614d43ab3cc18ad80c0c0121021b5180b1c1051aecb828d7a93b986db2d653248a8fe8e850f4a198af1a3ad8e502473044022011e7fbe0e6515fcce6d12d150851e50345aebe0a5b176e7a109ede35d559fd8402202de8ada72399448c4aa103aad772da3aa7d5332ef206b094cdf471bc5a888a720121039acd726ff5f089dde3c9e179aa488cae9ab76b00dd03974cdd5aa65fbd339cee0247304402203a8305c47f6a330b5011dceab52b31c1d77c8979f4fa41513ac3c08f74a6360202206b703e70ec89a473dc9475f27fca4a10f07a301f9ab9c5ea17ec993f5ef69c31012102280192a8d0b2ee4c12f1cb7b7acb857167338fe25dfc6193056eb5a4f9f0e71d00000000")
ECSignatureParams(inputInfo, tx, signer, hashType)
````

**Comment by benthecarman** [comment]
This is by design, you need the funding tx to be secure, maybe just need a better error message
