### ISSUE TITLE
Custom DLC based on volatility

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2251]
Things that need to happen to get this done 

1. A oracle to sign the price at the maturation time. This will be a [digit decomposition event](https://github.com/discreetlogcontracts/dlcspecs/blob/master/Oracle.md#digit-decomposition) (#2162 required) (@rorp)
2. Abillity to construct a [`ContractInfo`](https://github.com/bitcoin-s/bitcoin-s/blob/3be70f58554855096c3d20359ec8f033ac6d377f/app-commons/src/main/scala/org/bitcoins/commons/jsonmodels/dlc/DLCMessage.scala#L66-L65) that represents a wedge ([volatility](https://www.investopedia.com/terms/v/volatility.asp)). (@nkohen )
3. Wallet infrastructure to store multiple nonces and signatures. (@benthecarman )

The current proposed structure for the `ContractInfo` is 

1. the leftmost collar (x-coordinate)
2. the rightmost collar (x-coordinate)
3. inverted (boolean) 
4. the midpoint of the wedge (x-coordinate)

**Comment by benthecarman** [comment]
> The current proposed structure for the ContractInfo is

This isn't the structure of the `ContractInfo`, it is what is needed to build a `ContractInfo`
