### ISSUE TITLE
Make numeric outcome window take base10 rather than base2

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2282]
This is what we have currently 

![Screenshot from 2020-11-20 12-40-03](https://user-images.githubusercontent.com/3514957/99837700-a2d01280-2b2d-11eb-9f1b-6d5ff5d47ca7.png)

In my opinion `base` default to base 10 and we do the conversion to base2 behind the scenes for the protocol

**Comment by nkohen** [comment]
I disagree with this approach, rather, in the future this window should take in an oracle announcement and pick this information off of that.
