### ISSUE TITLE
Spice up README for bitcoin-s landing page

### ISSUE THREAD

**Issue by nkohen** [bitcoin-s/bitcoin-s#2297]
While our current README does link to bitcoin-s.org, I think it would be nice to give a high level quick rundown of the projects and modules going on in bitcoin-s with links out to code directories and/or docs.
Specifically:

- Crypto (bouncy and secp)
- Wallet
- PSBT
- Transaction Building and Signing
- Node
- RPC
- DLC
- CLI
- GUI
- Chain
- HD
- Neutrino
- testkit
- eclair integration
- anything else I've missed?

**Comment by Christewart** [comment]
Done by #3489
