### ISSUE TITLE
Multi-Wallet Support

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-s/bitcoin-s#2306]
We need multi-wallet support for adding things like #1419 & #1420, otherwise we would need to delete the current user wallet/seed.

Multi-wallet has some complications on how we should implement it, here are some questions:

- Do we want to re-use the same walletdb?
  - This would likely mean a large refactor as a lot of the wallet assumes everything in the walletdb belongs to the same wallet
- How do we handle/save multiple `encrypted-bitcoin-s-seed.json` files
- Do we allow multiple wallets to be used at once?

Should use this issue to discuss various options

**Comment by benthecarman** [comment]
In my opinion it would be easiest to have a `walletName: Option[String]` in the config that defines the current wallet being used. `None` would use the current wallet setup, if it is `Some(value)` then it would have a folder in the datadir with its own walletdb and seedfile. For postgres we could just concatenate the wallet name to the wallet db for separate dbs.

This also should allow for multiple wallets to be used at once with minimum refactors as well.

**Comment by Christewart** [comment]
So some thoughts: 

Let's make sure we don't start blurring the lines between the key-manager and wallet interface. I think a wallet is just a collection of information about utxos, transactions, etc. Using this information -- **_in conjunction with a key manager_** -- you can spend money from a utxo.

In my opinion the first step should be giving the [`KeyManagerApi`](https://github.com/bitcoin-s/bitcoin-s/blob/66ec89bcab0bdc1d5aed47e20049737af476861b/core/src/main/scala/org/bitcoins/core/api/keymanager/KeyManagerApi.scala#L10-L9) an `id` method. So something like this

```scala
trait KeyManagerApi {
  def id: UUID
}
``` 

If every `KeyManager` has an id, we can now start using that ID to associate ownership in the `walletdb`. The reason for choosing `UUID` is that this is a unique _internal_ id that we can use to associated owner between utxos <-> keys. If we also choose to use a UUID, we can re-use this abstraction for different key manager types (hopefully) like a hardware wallet, HSM, etc. 



I worry we have baked in assumptions on the wallet side about using BIP32/BIP44/etc specifically revolving anything with HD accounts, which makes our wallet non-functional for any sort of key manager that doesn't have support for that. 

I don't want to necessarily break all assumptions _now_ about using BIP32/BIP44 etc, but it would be nice to try and slowly move away from that. 

With a unique internal ID we can start associating utxos/transactions/etc with that UUID.

Thoughts?

**Comment by benthecarman** [comment]
Using a UUID could work but like I said in the OP, anything that uses the same walletdb will require a very large refactor. Currently the wallet does have a heavy assumption that we are using a BIP32 seed and that everything in the walletdb belongs to it.

**Comment by Christewart** [comment]
> In my opinion it would be easiest to have a `walletName: Option[String]` in the config that defines the current wallet being used. `None` would use the current wallet setup, if it is `Some(value)` then it would have a folder in the datadir with its own walletdb and seedfile. For postgres we could just concatenate the wallet name to the wallet db for separate dbs.
> 
> This also should allow for multiple wallets to be used at once with minimum refactors as well.

I think this would be a good start. 

> For postgres we could just concatenate the wallet name to the wallet db for separate dbs. 

Or perhaps use the wallet name as the schema? so if I wanted to create a new wallet `my-wallet-2021` the db representation would look like

`my-wallet-2021.wallet_accounts`
`my-wallet-2021.txo_spending_info` 

... etc

**Comment by Christewart** [comment]
One concern we talked about on our call is backing up seeds. 

There are a couple questions here: 

1. Should each independent wallet have an independent mnemonic seed?
2. If (1) is true, how do we backup these seeds up? 

A user could create a new wallet, with a new mnemonic seed, but forget to back it up. 

One possible mitigation to this is making all seeds live in the same directory. Seeds are not dependent on a network, so you could have a structure like this

![Screenshot from 2020-12-07 10-33-03](https://user-images.githubusercontent.com/3514957/101377576-9c54d100-3877-11eb-9057-4ca43abc5ea6.png)

However you _still_ need to create a new backup everytime the wallet is made because the seeds are independent :/

**Comment by Christewart** [comment]
I think @benthecarman and I agreed that this is probably the right approach, but we should make sure we add documentation to the website about safely backing up your wallet. Specifically you need to create a new backup every time you create a new wallet.

**Comment by benthecarman** [comment]
Closed by #2345
