### ISSUE TITLE
Split Generators from Testkit project

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-s/bitcoin-s#2313]
Currently, if you want to use the any of the bitcoin-s generators, you must depend on `testkit`. However, this can be annoying for projects as `testkit` depends on almost every module. It looks like all of our generators only depend on the `core` module, so it should be possible to make a generator module that is separate from `testkit`.

**Comment by benthecarman** [comment]
My main motivation for this is because a jar for [PSBT Toolkit](https://github.com/benthecarman/PSBT-Toolkit) is ~170 MB because it depends on testkit

**Comment by Christewart** [comment]
> My main motivation for this is because a jar for [PSBT Toolkit](https://github.com/benthecarman/PSBT-Toolkit) is ~170 MB because it depends on testkit

Yikes! Why do you need to include testkit (links always very helpful!)

Thanks for clarifying motivation though, it was my understanding from the OP that you are annoyed by compile times, which might be able to be debugged and helped out by a new scala intellij feature 

https://blog.jetbrains.com/scala/2020/12/01/intellij-scala-plugin-2020-3/

Specifically 'Compilation Charts'.

**Comment by benthecarman** [comment]
> Yikes! Why do you need to include testkit (links always very helpful!)

This is because I use the generators to let people randomly generate txs, pstbs, etc to test various things.

https://github.com/benthecarman/PSBT-Toolkit/blob/master/src/main/scala/org/psbttoolkit/gui/generators/GeneratorPaneModel.scala#L26

**Comment by Christewart** [comment]
So I guess I don't have a problem with this in theory, I do wonder how big the classpath will still be with scalatest/scalacheck though. Just doing `show dependencyTree` in the `testkit` project gives us this 

>[info]   +-org.scalacheck:scalacheck_2.13:1.15.1 [S]
[info]   | +-org.scala-sbt:test-interface:1.0
[info]   |
[info]   +-org.scalatest:scalatest_2.13:3.2.3 [S]
[info]   | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | +-org.scalatest:scalatest-core_2.13:3.2.3 [S]
[info]   | | +-org.scala-lang.modules:scala-xml_2.13:1.2.0 [S]
[info]   | | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | | +-org.scalactic:scalactic_2.13:3.2.3 [S]
[info]   | | | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | | |
[info]   | | +-org.scalatest:scalatest-compatible:3.2.3
[info]   | |
[info]   | +-org.scalatest:scalatest-diagrams_2.13:3.2.3 [S]
[info]   | | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | | +-org.scalatest:scalatest-core_2.13:3.2.3 [S]
[info]   | |   +-org.scala-lang.modules:scala-xml_2.13:1.2.0 [S]
[info]   | |   +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   +-org.scalactic:scalactic_2.13:3.2.3 [S]
[info]   | |   | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   |
[info]   | |   +-org.scalatest:scalatest-compatible:3.2.3
[info]   | |
[info]   | +-org.scalatest:scalatest-featurespec_2.13:3.2.3 [S]
[info]   | | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | | +-org.scalatest:scalatest-core_2.13:3.2.3 [S]
[info]   | |   +-org.scala-lang.modules:scala-xml_2.13:1.2.0 [S]
[info]   | |   +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   +-org.scalactic:scalactic_2.13:3.2.3 [S]
[info]   | |   | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   |
[info]   | |   +-org.scalatest:scalatest-compatible:3.2.3
[info]   | |
[info]   | +-org.scalatest:scalatest-flatspec_2.13:3.2.3 [S]
[info]   | | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | | +-org.scalatest:scalatest-core_2.13:3.2.3 [S]
[info]   | |   +-org.scala-lang.modules:scala-xml_2.13:1.2.0 [S]
[info]   | |   +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   +-org.scalactic:scalactic_2.13:3.2.3 [S]
[info]   | |   | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   |
[info]   | |   +-org.scalatest:scalatest-compatible:3.2.3
[info]   | |
[info]   | +-org.scalatest:scalatest-freespec_2.13:3.2.3 [S]
[info]   | | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | | +-org.scalatest:scalatest-core_2.13:3.2.3 [S]
[info]   | |   +-org.scala-lang.modules:scala-xml_2.13:1.2.0 [S]
[info]   | |   +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   +-org.scalactic:scalactic_2.13:3.2.3 [S]
[info]   | |   | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   |
[info]   | |   +-org.scalatest:scalatest-compatible:3.2.3
[info]   | |
[info]   | +-org.scalatest:scalatest-funspec_2.13:3.2.3 [S]
[info]   | | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | | +-org.scalatest:scalatest-core_2.13:3.2.3 [S]
[info]   | |   +-org.scala-lang.modules:scala-xml_2.13:1.2.0 [S]
[info]   | |   +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   +-org.scalactic:scalactic_2.13:3.2.3 [S]
[info]   | |   | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   |
[info]   | |   +-org.scalatest:scalatest-compatible:3.2.3
[info]   | |
[info]   | +-org.scalatest:scalatest-funsuite_2.13:3.2.3 [S]
[info]   | | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | | +-org.scalatest:scalatest-core_2.13:3.2.3 [S]
[info]   | |   +-org.scala-lang.modules:scala-xml_2.13:1.2.0 [S]
[info]   | |   +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   +-org.scalactic:scalactic_2.13:3.2.3 [S]
[info]   | |   | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   |
[info]   | |   +-org.scalatest:scalatest-compatible:3.2.3
[info]   | |
[info]   | +-org.scalatest:scalatest-matchers-core_2.13:3.2.3 [S]
[info]   | | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | | +-org.scalatest:scalatest-core_2.13:3.2.3 [S]
[info]   | |   +-org.scala-lang.modules:scala-xml_2.13:1.2.0 [S]
[info]   | |   +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   +-org.scalactic:scalactic_2.13:3.2.3 [S]
[info]   | |   | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   |
[info]   | |   +-org.scalatest:scalatest-compatible:3.2.3
[info]   | |
[info]   | +-org.scalatest:scalatest-mustmatchers_2.13:3.2.3 [S]
[info]   | | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | | +-org.scalatest:scalatest-matchers-core_2.13:3.2.3 [S]
[info]   | |   +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   +-org.scalatest:scalatest-core_2.13:3.2.3 [S]
[info]   | |     +-org.scala-lang.modules:scala-xml_2.13:1.2.0 [S]
[info]   | |     +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |     +-org.scalactic:scalactic_2.13:3.2.3 [S]
[info]   | |     | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |     |
[info]   | |     +-org.scalatest:scalatest-compatible:3.2.3
[info]   | |
[info]   | +-org.scalatest:scalatest-propspec_2.13:3.2.3 [S]
[info]   | | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | | +-org.scalatest:scalatest-core_2.13:3.2.3 [S]
[info]   | |   +-org.scala-lang.modules:scala-xml_2.13:1.2.0 [S]
[info]   | |   +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   +-org.scalactic:scalactic_2.13:3.2.3 [S]
[info]   | |   | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   |
[info]   | |   +-org.scalatest:scalatest-compatible:3.2.3
[info]   | |
[info]   | +-org.scalatest:scalatest-refspec_2.13:3.2.3 [S]
[info]   | | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | | +-org.scalatest:scalatest-core_2.13:3.2.3 [S]
[info]   | |   +-org.scala-lang.modules:scala-xml_2.13:1.2.0 [S]
[info]   | |   +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   +-org.scalactic:scalactic_2.13:3.2.3 [S]
[info]   | |   | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   |
[info]   | |   +-org.scalatest:scalatest-compatible:3.2.3
[info]   | |
[info]   | +-org.scalatest:scalatest-shouldmatchers_2.13:3.2.3 [S]
[info]   | | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | | +-org.scalatest:scalatest-matchers-core_2.13:3.2.3 [S]
[info]   | |   +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |   +-org.scalatest:scalatest-core_2.13:3.2.3 [S]
[info]   | |     +-org.scala-lang.modules:scala-xml_2.13:1.2.0 [S]
[info]   | |     +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |     +-org.scalactic:scalactic_2.13:3.2.3 [S]
[info]   | |     | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   | |     |
[info]   | |     +-org.scalatest:scalatest-compatible:3.2.3
[info]   | |
[info]   | +-org.scalatest:scalatest-wordspec_2.13:3.2.3 [S]
[info]   |   +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   |   +-org.scalatest:scalatest-core_2.13:3.2.3 [S]
[info]   |     +-org.scala-lang.modules:scala-xml_2.13:1.2.0 [S]
[info]   |     +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   |     +-org.scalactic:scalactic_2.13:3.2.3 [S]
[info]   |     | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]   |     |
[info]   |     +-org.scalatest:scalatest-compatible:3.2.3
[info]   |
[info]   +-org.scalatestplus:scalacheck-1-14_2.13:3.2.1.0 [S]
[info]     +-org.scalacheck:scalacheck_2.13:1.14.3 (evicted by: 1.15.1)
[info]     +-org.scalacheck:scalacheck_2.13:1.15.1 [S]
[info]     | +-org.scala-sbt:test-interface:1.0
[info]     |
[info]     +-org.scalatest:scalatest-core_2.13:3.2.1 (evicted by: 3.2.3)
[info]     +-org.scalatest:scalatest-core_2.13:3.2.3 [S]
[info]       +-org.scala-lang.modules:scala-xml_2.13:1.2.0 [S]
[info]       +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]       +-org.scalactic:scalactic_2.13:3.2.3 [S]
[info]       | +-org.scala-lang:scala-reflect:2.13.4 [S]
[info]       |
[info]       +-org.scalatest:scalatest-compatible:3.2.3
[info]
[info] ()

Maybe you can trim out scalatest totally, or just use `scalacheck` -- but i'm not sure what the story is with scalacheck depending on scalatest. My last understanding of this is they were trying to merge the two projects.

**Comment by Christewart** [comment]
If you do decide to embark on this, it might be worth tackling #2004 at the same time
