### ISSUE TITLE
Contract maturity not working in the GUI

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2359]
I am running on a0b60b2ebf954b4db185f09af95419b353794209

It appears we don't have contract maturity showing up. It would be nice if it was displayed in a nice format that makes it easy to determine when the contract matures

![Screenshot from 2020-12-15 07-18-31](https://user-images.githubusercontent.com/3514957/102220040-e2c4b400-3ea5-11eb-83ed-9d21234bcbd0.png)

**Comment by benthecarman** [comment]
This is just what you set as the contract maturity, I assume you guys just set it at 0 for simplicity

**Comment by Christewart** [comment]
Wait so we haven't got rid of contract maturity yet? I thought there was pretty widespread consensus that only a refund locktime makes sense?

**Comment by benthecarman** [comment]
> Wait so we haven't got rid of contract maturity yet? I thought there was pretty widespread consensus that only a refund locktime makes sense?

It's still something we need to negotiate, maybe can be renamed

**Comment by Christewart** [comment]
> > Wait so we haven't got rid of contract maturity yet? I thought there was pretty widespread consensus that only a refund locktime makes sense?
> 
> It's still something we need to negotiate, maybe can be renamed

@nkohen and you are right. But I think we have an agreement that this should be removed from the table as it isn't really relevant to show to users.
