### ISSUE TITLE
Prepopulate fee rate field and possibly locktime field for DLC

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2374]
![Screenshot from 2020-12-16 15-04-51](https://user-images.githubusercontent.com/3514957/102406403-1f7cd200-3fb0-11eb-8767-53be87d2f189.png)

It would be nice to have the fee field pre-populated with whatever your fee rate provider says for 6 blocks. Then you can adjust the fee rate to be higher or lower dependending on your timeline. This at least gives you a baseline of what fee rates currently are. 

Also as discussed in #2359 the `locktime` is required, but it might be nice to have a default value provided there too? I guess in general, we should provide sane defaults so we don't have as many options for users as it confuses people. 

They can of course adjust those default values in the text boxes, but I think it's good to provide sane defaults for those options.

**Comment by Christewart** [comment]
One other thing, I would be in support of re-ordering the text boxes in order of importance, something like 

1. contract info 
2. oracle announcement
3. Your collateral
4. refund locktime
5. fee rate
6. locktime

**Comment by benthecarman** [comment]
I would be in favor of just removing the `locktime` from the gui and just always defaulting it to 0
