### ISSUE TITLE
DLCPayoutCurveTest should agree on degenerate cubics and lines fails on CI

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2386]
Saw this on #2383

https://github.com/bitcoin-s/bitcoin-s/pull/2383/checks?check_run_id=1572524229#step:5:3216

![Screenshot from 2020-12-17 14-09-11](https://user-images.githubusercontent.com/3514957/102538082-73032480-4071-11eb-8b1d-e6cb76f67a42.png)

**Comment by benthecarman** [comment]
same as #2369
