### ISSUE TITLE
BlockHeaderDAO.chainTips doesn't actually retrieve all chainTips

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2437]
If you take a look at our current implementation of [`BlockHeaderDAO.chainTips`](https://github.com/bitcoin-s/bitcoin-s/blob/40f46d7c7a82a300bf2be2f1e3b957789a80df2d/chain/src/main/scala/org/bitcoins/chain/models/BlockHeaderDAO.scala#L304)

```scala
  def chainTips: Future[Vector[BlockHeaderDb]] = {
    logger.debug(s"Getting chain tips from database")
    val aggregate = {
      maxWorkQuery.flatMap { work =>
        logger.debug(s"Max block work: $work")
        val atChainWork = getAtChainWorkQuery(work)
        atChainWork.map { headers =>
          logger.debug(s"Headers at $work: $headers")
        }
        atChainWork
      }
    }

    safeDatabase.runVec(aggregate)
  }
```

As you can see, this _only_ fetches the chainTip with the most work (`maxWorkQuery`). What this method _really_ implements is `maxWorkChainTip`. 

The test case that is problematic for this is what I cited in https://github.com/bitcoin-s/bitcoin-s/pull/2436#issuecomment-751716365

https://github.com/bitcoin-s/bitcoin-s/blob/master/chain-test/src/test/scala/org/bitcoins/chain/blockchain/ChainHandlerTest.scala#L170

After applying the fixes in #2436, we now cannot connect a header that _is_ valid, to a chainTip that is not the heaviest one.

**Comment by benthecarman** [comment]
I think this is the correct behavior. If we have 2 blocks competing at height X, this will return both.

When connecting headers we shouldn't be using this function to find which headers to connect to, instead connect to the different chains in our in memory blockchains.

**Comment by Christewart** [comment]
Our cached chain handlers use this logic to construct themseleves (`BlockHeaderDAO.chainTips`)

https://github.com/bitcoin-s/bitcoin-s/blob/2de17bb4e47961fd3fe4e55d75909b42470e3c59/chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandlerCached.scala#L69

The way this is currently implemented, it will only find the best chain tip. Not _competing_ tips. This is because underneath the hood we are using `maxWorkQuery` to determine what the best tip is. 

https://github.com/bitcoin-s/bitcoin-s/blob/19c68b77b9736ac403e0730e949d1c7fa57468a0/chain/src/main/scala/org/bitcoins/chain/models/BlockHeaderDAO.scala#L307

**Comment by benthecarman** [comment]
It finds the max work but then calls `getAtChainWorkQuery` which returns all headers with that work. So if we have multiple competing tips it should return them because they will have the same work.

**Comment by Christewart** [comment]
Resource to claim above ^ 

https://bitcoin.stackexchange.com/questions/56855/chain-with-most-proof-of-work-hash-target-or-block-header-hash
