### ISSUE TITLE
Master will not stage binaries 

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2447]
This is on  7ad477fdaa20909bac316f82203f7f992a7b05e0 

I attempted to run `sbt universal:stage`

>[info] Main Scala API documentation to /home/suredbits/dev/bitcoin-s/app-commons/target/scala-2.13/api...
[error] /home/suredbits/dev/bitcoin-s/app-commons/src/main/scala/org/bitcoins/commons/serializers/JsonReaders.scala:776:43: reference to ShortChannelId is ambiguous;
[error] it is imported twice in the same scope by
[error] import org.bitcoins.core.protocol.ln.channel._
[error] and import org.bitcoins.core.protocol.ln._
[error]   implicit val shortChannelIdReads: Reads[ShortChannelId] = {
[error]                                           ^
[error] /home/suredbits/dev/bitcoin-s/app-commons/src/main/scala/org/bitcoins/commons/serializers/JsonReaders.scala:778:38: reference to ShortChannelId is ambiguous;
[error] it is imported twice in the same scope by
[error] import org.bitcoins.core.protocol.ln.channel._
[error] and import org.bitcoins.core.protocol.ln._
[error]       SerializerUtil.processJsString(ShortChannelId.fromHumanReadableString)(
[error]                                      ^
[error] /home/suredbits/dev/bitcoin-s/app-commons/src/main/scala/org/bitcoins/commons/serializers/JsonReaders.scala:819:15: No instance of play.api.libs.json.Reads is available for org.bitcoins.core.protocol.ln.ShortChannelId in the implicit scope (Hint: if declared in the same file, make sure it's declared before)
[error]     Json.reads[ChannelDesc]
[error]               ^
[error] /home/suredbits/dev/bitcoin-s/app-commons/src/main/scala/org/bitcoins/commons/serializers/JsonReaders.scala:847:19: reference to ShortChannelId is ambiguous;
[error] it is imported twice in the same scope by
[error] import org.bitcoins.core.protocol.ln.channel._
[error] and import org.bitcoins.core.protocol.ln._
[error]         .validate[ShortChannelId]
[error]                   ^
[error] /home/suredbits/dev/bitcoin-s/app-commons/src/main/scala/org/bitcoins/commons/serializers/JsonReaders.scala:904:36: reference to ShortChannelId is ambiguous;
[error] it is imported twice in the same scope by
[error] import org.bitcoins.core.protocol.ln.channel._
[error] and import org.bitcoins.core.protocol.ln._
[error] Error occurred in an application involving default arguments.
[error]           case Failure(_)  => Left(ShortChannelId.fromHumanReadableString(x._1))
[error]                                    ^
[error] /home/suredbits/dev/bitcoin-s/app-commons/src/main/scala/org/bitcoins/commons/serializers/JsonReaders.scala:918:65: reference to ShortChannelId is ambiguous;
[error] it is imported twice in the same scope by
[error] import org.bitcoins.core.protocol.ln.channel._
[error] and import org.bitcoins.core.protocol.ln._
[error]         shortChannelId <- (jsValue \ "shortChannelId").validate[ShortChannelId]
[error]                                                                 ^
[error] /home/suredbits/dev/bitcoin-s/app-commons/src/main/scala/org/bitcoins/commons/serializers/JsonReaders.scala:983:15: No instance of play.api.libs.json.Reads is available for scala.Option[org.bitcoins.core.protocol.ln.ShortChannelId] in the implicit scope (Hint: if declared in the same file, make sure it's declared before)
[error]     Json.reads[Hop]
[error]               ^
[error] /home/suredbits/dev/bitcoin-s/app-commons/src/main/scala/org/bitcoins/commons/serializers/JsonReaders.scala:1208:15: No instance of play.api.libs.json.Reads is available for org.bitcoins.core.protocol.ln.ShortChannelId in the implicit scope (Hint: if declared in the same file, make sure it's declared before)
[error]     Json.reads[UsableBalancesResult]
[error]               ^
[error] /home/suredbits/dev/bitcoin-s/app-commons/src/main/scala/org/bitcoins/commons/jsonmodels/eclair/EclairModels.scala:252:39: No Json deserializer found for type org.bitcoins.core.protocol.ln.ShortChannelId. Try to implement an implicit Reads or Format for this type.
[error]     (data \ "shortChannelId").validate[ShortChannelId].asOp

**Comment by benthecarman** [comment]
Works for me on 9bef444fe70
