### ISSUE TITLE
DataMessageHandler requests next batch of filters before we actually validate the previous ones

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2462]
I think these are out of order? 

Here is where we request the next batch of compact filters

https://github.com/christewart/bitcoin-s-core/blob/7172b4a049b8a18568e5e69d3f947ea6b32d4803/node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala#L111

and then here is where we actually process the previous batch and determine if it's valid
https://github.com/christewart/bitcoin-s-core/blob/7172b4a049b8a18568e5e69d3f947ea6b32d4803/node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala#L132

This seems wrong to me, shouldn't the order be flipped?

I'm beginning to think this might be related to bugs I'm seeing in #2461 , specifically this comment https://github.com/bitcoin-s/bitcoin-s/pull/2461#discussion_r551053917

**Comment by benthecarman** [comment]
Yeah these should be reversed. I think someone could send us fake filter headers which could cause us to send the wrong `sendNextGetCompactFilterCommand` message making peers disconnect from us.
