### ISSUE TITLE
RescanHandlingTest must be able to discover funds using multiple batches failing on CI intermittently 

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2484]
https://github.com/bitcoin-s/bitcoin-s/runs/1662610393#step:5:374

Not exactly sure what is going on here, this was seen on #2471 but it probably isn't related

**Comment by Christewart** [comment]
Seen again
![Screenshot from 2021-03-04 09-44-59](https://user-images.githubusercontent.com/3514957/109989819-79975480-7cce-11eb-9804-68dcf5bdcacf.png)

**Comment by benthecarman** [comment]
I think this happens because of the filter's false positve rate.

**Comment by Christewart** [comment]
Likely false positives on CI
