### ISSUE TITLE
Things to test before 0.5 release

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2531]
- [x] Import keys via `seeds/` directory (tested on 1dacb74edf75cd4529a35394736c63cc0f75b433)
- [x] Importing keys via rpc (tested on 8e799a4b245a43c9719373e0570746c4bb2f59f0)
- [x] multi wallet (tested on 1dacb74edf75cd4529a35394736c63cc0f75b433)
- [x] binding to unique network interface (https://github.com/bitcoin-s/bitcoin-s/pull/2409)
- [x] fee bumping (https://github.com/bitcoin-s/bitcoin-s/pull/2399)(tested on f849ba492f1475e97bc840864ab5f631b04f19d5)
- [x] out of box intellij support (tested on  f2172965221a8378cd4c2bcaa72aba976e36fa13) 
- [x] `getbestblockhash` ALWAYS has the latest block hash (https://github.com/bitcoin-s/bitcoin-s/issues/2258) (tested on 1dacb74edf75cd4529a35394736c63cc0f75b433)
- [x] signing psbts with wallet (https://github.com/bitcoin-s/bitcoin-s/pull/2236) (tested on f2172965221a8378cd4c2bcaa72aba976e36fa13)
- [x] `aesPassword` configuration works correctly (https://github.com/bitcoin-s/bitcoin-s/pull/2234) (tested on 8e799a4b245a43c9719373e0570746c4bb2f59f0)
- [x] changing `aesPassword` (tested on 8e799a4b245a43c9719373e0570746c4bb2f59f0)
- [x] `bip39Password` works correctly (https://github.com/bitcoin-s/bitcoin-s/pull/2234) (tested on 8e799a4b245a43c9719373e0570746c4bb2f59f0)
- [x]  ??? What should behavior be if we change bip39 password ??? error?
- [x] The two passwords above play nicely with each other (tested on 8e799a4b245a43c9719373e0570746c4bb2f59f0)
- [x] Test new features with postgres (multi wallet in particular) (tested on 1dacb74edf75cd4529a35394736c63cc0f75b433) 
- [x] bitcoind as a backend (tested on abfe0c56131)
- [x] Make sure the [chain dump](https://bitcoin-s.org/docs/next/getting-setup#step-6-optional-moving-to-testnet) we provide works
- [x] Make sure there are no reversions for various java versions (8,11,15) (java11 tested on 1dacb74edf75cd4529a35394736c63cc0f75b433, java8 tested on 3844ad73fdb83dfdb8a3f5a9ab19b5d99ae2a7bb , java15 tested on  db6cd10c2f125737caf2c48c7643d99a5f218ac6 )
- [x] Make sure slack links on site are valid

We should also look over the previous release issue and see if anything should be tested again https://github.com/bitcoin-s/bitcoin-s/issues/1802

**Comment by benthecarman** [comment]
This is what we had for 0.4 

https://github.com/bitcoin-s/bitcoin-s/issues/1802

**Comment by benthecarman** [comment]
> Make sure the chain dump we provide works

This is a pre-chainwork datadump, we should probbably update this to something that doesn't need a recalc

**Comment by benthecarman** [comment]
> ??? What should behavior be if we change bip39 password ??? error?

Currently we error which is what we should do. Example error message:

```
java.lang.RuntimeException: Divergent xpubs for account=AccountDb(zpub6s7Fh5HTYZxgScpq1vth8fAV1JAHFn85dPV9AYuGwrDbnyKXpT6jC5naqorS3ZjdZLfPRaA5cKcZqNy6LhaCKTRpTZt1CLnqKQYLACKHYQJ,m/84'/0'/0'). Existing database xpub=zpub6s7Fh5HTYZxgScpq1vth8fAV1JAHFn85dPV9AYuGwrDbnyKXpT6jC5naqorS3ZjdZLfPRaA5cKcZqNy6LhaCKTRpTZt1CLnqKQYLACKHYQJ, key manager's xpub=zpub6qcZ6WGcDhp8Dv4JnvqbqJUHQ7r13jxZVvNQyPx7Xz6N968w7C3i1NcFMeT26nKZFWSZqvk1HoTzPTQ9kuGxscRxv9J59rCCdvFZaVViicn. It is possible we have a different key manager being used than expected, key manager=org.bitcoins.keymanager.bip39.BIP39KeyManager@1df4a721
	at org.bitcoins.wallet.Wallet.$anonfun$checkRootAccount$1(Wallet.scala:134)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```
