### ISSUE TITLE
Check address checksums inside of invariants

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2574]
ooh wow, this isn't applied to _any_ of our address types. We probably want to add this in the super class possibly? 

I'm going to file an issue

https://github.com/bitcoin-s/bitcoin-s/blob/223be8057351017eb0d454b97b36a917f00fe1ac/core/src/main/scala/org/bitcoins/core/protocol/Address.scala#L215

_Originally posted by @Christewart in https://github.com/bitcoin-s/bitcoin-s/pull/2571#discussion_r565376658_

**Comment by benthecarman** [comment]
Thankfully, looks like we already do https://github.com/bitcoin-s/bitcoin-s/blob/master/core/src/main/scala/org/bitcoins/core/util/Base58.scala#L36
