### ISSUE TITLE
oracle server uses regtest datadir

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2663]
>021-02-15T14:11:02UTC INFO [OracleServerMain] version=0.5.0+17-89185338+20210215-0730-SNAPSHOT
2021-02-15T14:11:02UTC INFO [OracleServerMain] networkDatadir=/home/demiourgos728/.bitcoin-s/regtest
[DEBUG] [02/15/2021 14:11:02.477] [main] [EventStream] StandardOutLogger started

Is this what we want? if we change this in the future (say, we change the default network setting) will users have their oracle break because it isn't looking in the correct datadir?

**Comment by Christewart** [comment]
> > 021-02-15T14:11:02UTC INFO [OracleServerMain] version=0.5.0+17-89185338+20210215-0730-SNAPSHOT
> > 2021-02-15T14:11:02UTC INFO [OracleServerMain] networkDatadir=/home/demiourgos728/.bitcoin-s/regtest
> > [DEBUG] [02/15/2021 14:11:02.477] [main] [EventStream] StandardOutLogger started
> 
> Is this what we want? if we change this in the future (say, we change the default network setting) will users have their oracle break because it isn't looking in the correct datadir?

I'm also in favor of changing this just for semantics sake. 

When i see something is associated with a `regtest` datadir, i think it isnt important and am more likely to delete it. However if something is in a `mainnet` datadir i'm much more likely to treat it safer.

**Comment by benthecarman** [comment]
I think the best option would maybe to just move it out of a network folder all together, either putting it in the `.bitcoin-s` dir or giving it a folder like `.bitcoin-s/oracle`

**Comment by Christewart** [comment]
I think the latter makes the most sense. While it isn't a network, it is a stand alone application.
