### ISSUE TITLE
Add docs saying how to backup oracle db

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-s/bitcoin-s#2710]
Explain that the db has no sensitive information and is safe to backup in "public" locations (ie google drive)

**Comment by bicrxm** [comment]
Can I know more about the issue?

**Comment by Christewart** [comment]
> Can I know more about the issue?

If you backup your `oracle.sqlite` database, there is no sensitive information stored in the database such as private keys. This means it is safer to back up the database to a place that isn't as "secure". 

The [seed files](https://bitcoin-s.org/docs/next/key-manager/server-key-manager#backups)  are here. Those are super sensitive and you need to store them securely.

**Comment by Christewart** [comment]
What we need someone to do is add this to our website. You can create a new file in this directory to explain this: https://github.com/bitcoin-s/bitcoin-s/tree/master/docs/oracle
