### ISSUE TITLE
ConfirmedSpent vs PendingConfirmationsSpent TxoStates have no meaning

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-s/bitcoin-s#2736]
I discovered this while wokring on #2735

Currently there is no distinction between `ConfirmedSpent` and `PendingConfirmationsSpent` in the wallet.

We calculate which spent state to based off the the txo/`SpendingInfoDb`'s `blockHashOpt` param. However, this param is for the block that the tx the txo originates from, not the spending transaction so we are calcuating if it is confirmed based on an entirely different transaction and most likely block.

There are 2 solutions for this:

1) add a new column/param to `SpendingInfoDb` for the spending tx and its blockhash
2) Remove the distinction and just have a `Spent` `TxoState` (do we need to care if our spending tx is confirmed?)

**Comment by Christewart** [comment]
>     2\. (do we need to care if our spending tx is confirmed?)

Yes. For instance if you are dual funding a lightning channel or DLC, you want to know if your txo is fully confirmed or still is pending confirmations. 

I would also imagine for reorg logic (#2179) this can be useful for providing reorg safety.
