### ISSUE TITLE
Construct oracle private key with real types rather than a string

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2750]
https://github.com/bitcoin-s/bitcoin-s/blob/1d5b565abe3a7f9137e8bd2246215c0d32902b8a/dlc-oracle/src/main/scala/org/bitcoins/dlc/oracle/DLCOracle.scala#L54

It seems _very_ easy to make a typo by forgetting a `'`. This seems like a footgun waiting to happen. My understanding is this could have pretty dramatic security implications if this string is refactored / moved in the future and we lose a `'` along the way. 

I guess an alternative could be defining `BIP32.fromStringHardened()` that throws if the entire path isn't hardened.

**Comment by benthecarman** [comment]
We are using a `ExtPrivateKeyHardened` which enforces that the path must all be hardened so if we did accidentially delete one it would fail to do anything. However, I agree that it would still be better to not have to trust that.
