### ISSUE TITLE
signatures not being properly DER encoded

### ISSUE THREAD

**Issue by TomMcCabe** [bitcoin-s/bitcoin-s#28]
ECDigitalSignatures aren't returning as strictly DER encoded.

Values for example when building CLTV spend:
- Unsigned transaction hex: `0100000001afecbf9d3729cdfea287538d097bd58e6099a504a5464af9d4a221ad3f6015d7000000002b2a046202b257b1752102ed83fb33da52014f08497b61b73d3deefbc298728fccfcf3e0b6042c8363df51ac4d01000001c0e4022a010000001976a91466c6532c4f35619ca671286d407f2e39fe08fd7488ac2934b257`
- RedeemScript hex: `046202b257b1752102ed83fb33da52014f08497b61b73d3deefbc298728fccfcf3e0b6042c8363df51ac`
- RedeemScript asm: `1471283810 OP_CHECKLOCKTIMEVERIFY OP_DROP 02ed83fb33da52014f08497b61b73d3deefbc298728fccfcf3e0b6042c8363df51 OP_CHECKSIG`
- P2SHScriptPubKey hex: `a9140db4fe237cb30e7ee7a096dbc2033d93242435ed87`
- P2SH asm: `OP_HASH160 0db4fe237cb30e7ee7a096dbc2033d93242435ed OP_EQUAL`
- PrivateKey to spending redeemScript: `7939911e7d96660d8de84d7376f4a85bf72ba1b7e107815aa6c99076a14796e1`
- TransactionSignatureComponent: `TransactionSignatureComponent(unsignedTx, UInt32(0), p2sh, flags)`
- TransactionSignatureSerializer: `hashForSignature(txSigComponent, SIGHASH_ALL.defaultValue))`

What I returned:
- Hash: `a758727808e9e35b7f9388016cfa0fb604d558ccef3b169b469f952266c8e611)`
- ECDigitalSignature with privateKey: `3045022100c16c04aa9923472b0f2d796bc3360b4a4277c6377d1db3758bc06df88cec017f02200f43e0af839e59e68bd34b745ebd7e291a4ba548facf16146d13cf39c70b0717`
- sig.isDEREncoded: `false`

---

Also found this signature from a CLTV spend on bitcointalk that IS strictly DER encoded: 

`30440220429b09433f70c16b26021bd19f71a7d30087c3bbd7e1255cfda7c00fdc126bed02207219634bd0f66eee1b73e60552bbf177f278ba856b99100bdc610b5da720168501`

https://bitcointalk.org/index.php?topic=1300723.msg13433715#msg13433715

**Comment by Christewart** [comment]
Fixed in #29
