### ISSUE TITLE
Remove logs from core

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2809]
We cannot take pre-compiled jars and use them in a scalajs environment. This means we have to use a scalajs aware dependency (`%%%`) to support logging in core. One of the dependency we currently use in core is [`slf4j-api`](https://github.com/bitcoin-s/bitcoin-s/blob/master/project/Deps.scala#L259-L260). This dependency is meant to be a a logging interface that any logging implementation can use to implement their custom features for their logger (we use [`logback`](http://logback.qos.ch/), which implements the slf4j-api).

As of this writing, the current plan is just to get the `core` and `crypto` modules working with scalajs. AFAIK, `crypto` didn't have any logs to begin with. We might just want to remove all logs in core, as I don't think they are being used anywhere? Mostly we just have logs turned off. 

Is there any objections to doing this?

**Comment by benthecarman** [comment]
ACK
