### ISSUE TITLE
Compiling lnd rpc in intellij does not work

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2871]
This is probably something to do with grpc 

![Screenshot from 2021-04-07 08-43-18](https://user-images.githubusercontent.com/3514957/113876429-5c4a2000-977d-11eb-8bd4-32e1c048079b.png)

**Comment by benthecarman** [comment]
You need to run `compile` for the proto files to be generated into scala files, maybe do that in `sbt` then see if this works

**Comment by Christewart** [comment]
I think the most important thing is this:

For a newcomer coming to the project, they don't know how any of that works (and it gives a bad UX to have to look through docs to figure this out). Can we just get it to work out of the box?

**Comment by benthecarman** [comment]
Looks like this isn't possible currently without using the sbt shell for builds

https://github.com/akka/akka-grpc/issues/270

**Comment by Christewart** [comment]
Unfortunately i have tried to comment out `lndRpc`,`lndRpcTest` in both the root `aggregate()` and `dependsOn()`. 

It seems that this doesn't work since it is transitively depended on by other projects (like `testkit`). 

I'm not sure what the best way to work around this is :/

**Comment by Christewart** [comment]
This now works in intellij as of  07e1047f7423dfc2355cf93634ab6831b99200e0
