### ISSUE TITLE
Add ability to cancel an offer

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2965]
![Screenshot from 2021-04-25 16-10-10](https://user-images.githubusercontent.com/3514957/116009708-c1589f00-a5e0-11eb-9a45-f715e2e68fc7.png)

In your DLC wallet, you should be able to cancel an offer. As a by product of this, the utxo that is reserved by the offer should be unreserved 

https://github.com/bitcoin-s/bitcoin-s/blob/7189e99d775caa8b9c225524ee84085bee08370e/dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala#L484

**Comment by benthecarman** [comment]
We should add this before we release the client
