### ISSUE TITLE
Make bitcoind block polling logs more apparent

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3027]
> I think there may be some sort of syncing done in the background? Idk I get these logs consisently, but they aren't useful

This is the bitcoind polling every 10 seconds for new blocks

_Originally posted by @benthecarman in https://github.com/bitcoin-s/bitcoin-s/issues/3026#issuecomment-832049600_

We should make these logs more useful/apparent. All I see is 

```
[info]   Request : HttpRequest(HttpMethod(POST),http://localhost:9999/,List(Timeout-Access: <function1>, Accept-Encoding: gzip, deflate, User-Agent: Java/11.0.11, Host, Accept: text/html, image/gif, image/jpeg, */*;q=0.2, */*;q=0.2, Connection: keep-alive),HttpEntity.Strict(application/json,83 bytes total),HttpProtocol(HTTP/1.1))
[info]   Response: Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(application/json,40 bytes total),HttpProtocol(HTTP/1.1)))
[info] 2021-05-04T15:57:15UTC INFO [ActorSystemImpl] http-rpc-server: Response for
[info]   Request : HttpRequest(HttpMethod(POST),http://localhost:9999/,List(Timeout-Access: <function1>, Accept-Encoding: gzip, deflate, User-Agent: Java/11.0.11, Host, Accept: text/html, image/gif, image/jpeg, */*;q=0.2, */*;q=0.2, Connection: keep-alive),HttpEntity.Strict(application/json,83 bytes total),HttpProtocol(HTTP/1.1))
[info]   Response: Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(application/json,40 bytes total),HttpProtocol(HTTP/1.1)))
```

Which isn't useful

**Comment by benthecarman** [comment]
Looking into this, this is actually the GUI polling for the wallet balance every 10 seconds, not the bitcoind block polling

**Comment by benthecarman** [comment]
Looks like these logs are also off by default

https://github.com/bitcoin-s/bitcoin-s/blob/master/db-commons/src/main/resources/reference.conf#L167

**Comment by Christewart** [comment]
This was taken care of in #3141
