### ISSUE TITLE
bitcoin-s bundle doesn't honor command line parameters

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3064]
I've tried 

> ./bitcoin-s-bundle --datadir /tmp/bitcoin-s-demo

> ./bitcoin-s-bundle --conf /tmp/bitcoin-s-demo/bitcoin-s.conf

>./bitcoin-s-bundle --conf /tmp/bitcoin-s-demo/bitcoin-s.conf --datadir /tmp/bitcoin-s-demo

and none seem to work. it seems to keep reading `$HOME/.bitcoin-s/bitcoin-s.conf`

**Comment by benthecarman** [comment]
The bundle doesn't fully respect command line arguments, to do this we should really have it extend `BitcoinSRunner`
