### ISSUE TITLE
secp256k1jni/test never fail

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3074]
I tried to add this clause in one of hte test cases 

>        assertEquals(1,0,"false");

and it still passed. This means our assertions can never fail it seems.

**Comment by benthecarman** [comment]
Cannot reproduce, changed some values in the tests and they failed for me

**Comment by Christewart** [comment]
Yeah i just tried too and got the same results. No idea why I were experiencing that before :/
