### ISSUE TITLE
Add way to set config in GUI

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-s/bitcoin-s#3076]
Currently, in bundle, we set start the server and the gui, if we wanted the gui to be able to configure the server, we would need to do one of two things.

1. Have a separate gui that only launches if there is no config file present. This gui would allow you to set your config and then launch the actual bundle 

2. Make it so the gui launches the actual server. Doing this would require us to remove some functionality (I think) because we get information from the server when launching (ie setting the icon based on which network we're on).

**Comment by nkohen** [comment]
Another option is we could still do server then gui but then have functionality in the gui to reconfigure and then restart the server and then reconnect to it.

For the GUI starts the server option, I think that this might not require a reduction in functionality so much as conditional functionality that is only enabled once configuration is complete and the server is started (I don't think this is actually too strange as plenty of wallets won't let you do stuff until you are connected and/or synced to some kind of backend)

**Comment by Christewart** [comment]
I'm personally interested in seeing the startup sequence 

1. GUI
2. Server 

At least the very first time you start. Maybe subsequent times we just do what they configured last time.

**Comment by Christewart** [comment]
Done in #3142
