### ISSUE TITLE
Hostname cannot be null zmq nullpointerexception

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3078]
This was observed by @nkohen when he was setting up a bitcoind backend node by following the docs here: https://bitcoin-s.org/docs/getting-setup#bitcoind-backend

>[info] 2021-05-13T22:09:21UTC ERROR [BitcoinSServerMain] Failed to startup server!
[info] java.lang.IllegalArgumentException: hostname can't be null
[info]  at java.base/java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
[info]  at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
[info]  at org.bitcoins.server.BitcoindRpcAppConfig.$anonfun$zmqRawBlock$1(BitcoindRpcAppConfig.scala:107)
[info]  at scala.Option.map(Option.scala:242)
[info]  at org.bitcoins.server.BitcoindRpcAppConfig.zmqRawBlock$lzycompute(BitcoindRpcAppConfig.scala:105)
[info]  at org.bitcoins.server.BitcoindRpcAppConfig.zmqRawBlock(BitcoindRpcAppConfig.scala:104)
[info]  at org.bitcoins.server.BitcoindRpcAppConfig.zmqConfig$lzycompute(BitcoindRpcAppConfig.scala:129)
[info]  at org.bitcoins.server.BitcoindRpcAppConfig.zmqConfig(BitcoindRpcAppConfig.scala:128)
[info]  at org.bitcoins.server.BitcoindRpcAppConfig.bitcoindInstance$lzycompute(BitcoindRpcAppConfig.scala:140)
[info]  at org.bitcoins.server.BitcoindRpcAppConfig.bitcoindInstance(BitcoindRpcAppConfig.scala:131)
[info]  at org.bitcoins.server.BitcoindRpcAppConfig.client$lzycompute(BitcoindRpcAppConfig.scala:151)
[info]  at org.bitcoins.server.BitcoindRpcAppConfig.client(BitcoindRpcAppConfig.scala:147)
[info]  at org.bitcoins.server.BitcoinSServerMain.startBitcoindBackend(BitcoinSServerMain.scala:153)
[info]  at org.bitcoins.server.BitcoinSServerMain.$anonfun$start$4(BitcoinSServerMain.scala:58)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
[info]  at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
[info]  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]  at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)

**Comment by benthecarman** [comment]
This was the result of the changes in #2897 not be documented correctly, instead of setting a port in the zmq config, you need to set the actual URI, for example `tcp://127.0.0.1:28332`
