### ISSUE TITLE
Large enum events create too many text boxes with no scroll bar

### ISSUE THREAD

**Issue by nkohen** [bitcoin-s/bitcoin-s#3079]
<img width="489" alt="Screen Shot 2021-05-13 at 4 35 18 PM" src="https://user-images.githubusercontent.com/22485603/118195935-61982b80-b409-11eb-8292-ce9571df8ae0.png">
This announcement was used: https://oracle.suredbits.com/event/19cb7eb89e141ba1fa0db9f942c7b508528553055f97e1114d0a45887c642b5c

**Comment by Christewart** [comment]
Needs to be pulled up to adaptor-dlc i believe
