### ISSUE TITLE
akka http socks5 proxy

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3099]
Is this easy to do? If so we can trivially add tor support into bitcoind rpc client

**Comment by rorp** [comment]
There's a concept of plugable client transports in Akka HTTP:
https://doc.akka.io/docs/akka-http/current/client-side/client-transport.html

It seems we can define our own transport.

**Comment by rorp** [comment]
Here is an HTTPS transport implementation, it can be used as a temaplate for SOCKS5 transport:
https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/ClientTransport.scala#L109
https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/client/HttpsProxyGraphStage.scala

**Comment by Christewart** [comment]
#3396
