### ISSUE TITLE
Cannot add witness script to PSBT

### ISSUE THREAD

**Issue by guggero** [bitcoin-s/bitcoin-s#3103]
**Describe the bug**
I'm using https://github.com/benthecarman/PSBT-Toolkit to edit a PSBT. My goal is to add a witness script to a PSBT.

The GUI calls the method `addRedeemOrWitnessScriptToInput`.
If I'm reading this correctly, then a witness script is only added if there's already a redeem script present. If that's correct, then I think the condition (`!isWitScript`) should be inverted here:
https://github.com/bitcoin-s/bitcoin-s/blob/master/core/src/main/scala/org/bitcoins/core/psbt/PSBT.scala#L355

**Comment by benthecarman** [comment]
The `!isWitScript` is correct here, if you look [here](https://github.com/bitcoin-s/bitcoin-s/blob/78f4dfb8c66eedc9c5b758ae5880274bf74571d2/core/src/main/scala/org/bitcoins/core/protocol/script/ScriptPubKey.scala#L1185) you can see what a `WitnessScriptPubKey` is just defined as. It shouldn't be your witness script

**Comment by benthecarman** [comment]
If you have a script that you know is the witness script and don't want to be added to the redeem script on accident there is the `addScriptWitnessToInput` function.

In https://github.com/benthecarman/PSBT-Toolkit/commit/1e8830a027cb1d3440278be4a3d421beeb6c243a I added this to PSBT-Toolkit, hopefully that fixes it for you

**Comment by guggero** [comment]
Ah okay, I wasn't fully sure about this. Sorry if it's an incorrect bug report then.
@benthecarman thank you so much for adding that functionality, that's exactly what I was missing.
