### ISSUE TITLE
Review configuration defaults before releasing 1.7

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3113]
Currently our configuration defaults for `deb` and `dmg`s use the `assemblyMergeStrategy` included in #3104 which leads to our network default being regtest. We probably don't want this.

This is easy to get wrong, and it doesn't work as expected out of the box. I would expect us to connect to mainnet neutrino and start syncing (we can't do bitcoind, as that requires configuration). This was the real cause of #3112

**Comment by benthecarman** [comment]
This likely means we are setting [this](https://github.com/bitcoin-s/bitcoin-s/blob/master/app/bundle/bundle.sbt#L15) incorrectly and merging the configs wrong as it didn't pickup the app-server's `reference.conf` file

**Comment by Christewart** [comment]
> This likely means we are setting [this](https://github.com/bitcoin-s/bitcoin-s/blob/master/app/bundle/bundle.sbt#L15) incorrectly and merging the configs wrong as it didn't pickup the app-server's `reference.conf` file

Yes exactly, specifically this:

https://github.com/bitcoin-s/bitcoin-s/blob/c605a02c28f8f77ff2ac99a7fe4d480a0312876a/app/bundle/bundle.sbt#L17

This `concat` strategy will add both configs, but it appears the typesafe library starts with the inner most reference.conf (`db-commons/reference.conf` in our case) and uses that configuration first.
