### ISSUE TITLE
No date picker for refund locktime

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3130]
This is on  74f9d6bef79d590cb28449c0f24035c4ae9c3571 

My understanding is there should be a datepicker here to easily select refund locktime

![Screenshot from 2021-05-24 06-43-55](https://user-images.githubusercontent.com/3514957/119343011-77082380-bc5b-11eb-9536-cefdd190c9b7.png)

**Comment by benthecarman** [comment]
Closed by dlc Gui pull down
