### ISSUE TITLE
Add ability to double spend ("cancel") utxos from signed state in a DLC

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3169]
In #3159 we get the ability for a user to cancel a DLC from the signed state. This is useful for trusted counterparties when one of them has a corrupted database, or just isn't interested in the DLC anymore. 

Technically, this feature isn't safe. The only safe way to cancel a DLC from the signed state is double spending it. We should offer that as an option to users if they are dealing with untrusted counter parties to truly cancel the DLC.

**Comment by benthecarman** [comment]
related #3162

**Comment by Christewart** [comment]
oh didn't see that, closing
