### ISSUE TITLE
Wallet cannot use unconfirmed utxos to fund DLCs

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3178]
This is probably something we want to add. A user will probably deposit funds into the wallet, and then start a DLC. It appears that unconfirmed utxos cannot be used to fund a DLC at the moment. 

The way i encountered this was I wanted to do 2 DLCs back to back with @nkohen . The first one wasn't a problem, but the second one failed with this error after he sent me an offer 

>[info] 2021-05-27T17:03:09UTC INFO [DLCWallet$DLCWalletImpl] Creating DLC Accept for tempContractId 3aecb6c6229e8a6a399111f04987613571b86e668653acf2af477c190a7bc2fa
[info] 2021-05-27T17:03:09UTC INFO [Server] Unhandled error in server:
[info] java.lang.RuntimeException: Not enough value in given outputs (50000 sats) to make transaction spending 50000 sats plus fees 5775 sats
[info]  at org.bitcoins.core.api.wallet.CoinSelector.addUtxos$1(CoinSelector.scala:74)
[info]  at org.bitcoins.core.api.wallet.CoinSelector.accumulate(CoinSelector.scala:93)
[info]  at org.bitcoins.core.api.wallet.CoinSelector.accumulate$(CoinSelector.scala:55)
[info]  at org.bitcoins.core.api.wallet.CoinSelector$.accumulate(CoinSelector.scala:97)
[info]  at org.bitcoins.core.api.wallet.CoinSelector.accumulateLargest(CoinSelector.scala:37)
[info]  at org.bitcoins.core.api.wallet.CoinSelector.accumulateLargest$(CoinSelector.scala:30)
[info]  at org.bitcoins.core.api.wallet.CoinSelector$.accumulateLargest(CoinSelector.scala:97)
[info]  at org.bitcoins.core.api.wallet.CoinSelector$.selectByAlgo(CoinSelector.scala:123)
[info]  at org.bitcoins.wallet.internal.FundTransactionHandling.$anonfun$fundRawTransactionInternal$9(FundTransactionHandling.scala:88)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
[info]  at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
[info]  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]  at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[error] java.lang.RuntimeException: Request failed: Not enough value in given outputs (50000 sats) to make transaction spending 50000 sats plus fees 5775 sats
[error]         at org.bitcoins.cli.ConsoleCli$.error$1(ConsoleCli.scala:1421)
[error]         at org.bitcoins.cli.ConsoleCli$.$anonfun$exec$1(ConsoleCli.scala:1748)
[error]         at scala.util.Try$.apply(Try.scala:210)
[error]         at org.bitcoins.cli.ConsoleCli$.exec(ConsoleCli.scala:1690)
[error]         at org.bitcoins.gui.dlc.DLCPaneModel.$anonfun$onAccept$1(DLCPaneModel.scala:116)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error]         at org.bitcoins.gui.TaskRunner$$anon$1.call(TaskRunner.scala:41)
[error]         at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
e^

![Screenshot from 2021-05-27 12-11-20](https://user-images.githubusercontent.com/3514957/119868448-aa111800-bee4-11eb-8a13-bfe333a1d767.png)

**Comment by benthecarman** [comment]
Looks like your funds are reserved, that's why they can't be used

**Comment by benthecarman** [comment]
It is possible to do a DLC from an unconfirmed utxo, I think #3207 confused you
