### ISSUE TITLE
Accepting a complex offer twice does not display accept message

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3191]
I accepted this offer once, tried to paste it into a file to send nadav, but the pasting operation filed because the accept was so big.

I tried to restart the node and paste in the offer again to the accept flow, to retreieve the cached accept message, but it doesn't do anything

![Screenshot from 2021-05-28 13-21-17](https://user-images.githubusercontent.com/3514957/120026681-0c871880-bfb8-11eb-8285-8e62f74d892d.png)

The offer: 

>a71a006fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000fdd82efd4fcc000000000001869ffda720fd4cec0011fda726fd4cdc05200100000000000000c35000000164000000000000bcd5000001c8000000000000b65b000001fd012c000000000000afe6000001fd0190000000000000a976000001fd01f4000000000000a30d000001fd02580000000000009cae000001fd02bc0000000000009659000001fd03200000000000009011000001fd038400000000000089d7000001fd03e800000000000083ae000001fd044c0000000000007d96000001fd04b00000000000007792000001fd051400000000000071a4000001fd05780000000000006bcc000001fd05dc000000000000660e000001fd06400000000000006069000001fd06a40000000000005ae1000001fd07080000000000005575000001fd076c0000000000005029000001fd07d00000000000004afd000001fd083400000000000045f4000001fd0898000000000000410d000001fd08fc0000000000003c4b000001fd096000000000000037b0000001fd09c4000000000000333b000001fd0a280000000000002ef0000001fd0a8c0000000000002ace000001fd0af000000000000026d7000001fd0b54000000000000230c000001fd0bb80000000000001f6e000001fd0c1c0000000000001bff000001fd0c8000000000000018bf000001fd0ce400000000000015ae000001fd0d4800000000000012cf000001fd0dac0000000000001022000001fd0e100000000000000da7000001fd0e740000000000000b5f000001fd0ed8000000000000094b000001fd0f3c000000000000076c000001fd0fa000000000000005c1000001fd1004000000000000044c000001fd1068000000000000030d000001fd10cc0000000000000204000001fd11300000000000000131000001fd11940000000000000095000001fd11f80000000000000030000001fd125c0000000000000003000001fd12c0000000000000000c000001fd1324000000000000004c000001fd138800000000000000c3000001fd13ec0000000000000171000001fd14500000000000000256000001fd14b40000000000000371000001fd151800000000000004c2000001fd157c0000000000000649000001fd15e00000000000000805000001fd164400000000000009f6000001fd16a80000000000000c1b000001fd170c0000000000000e74000001fd17700000000000001100000001fd17d400000000000013be000001fd183800000000000016ad000001fd189c00000000000019ce000001fd19000000000000001d1e000001fd1964000000000000209c000001fd19c80000000000002449000001fd1a2c0000000000002823000001fd1a900000000000002c28000001fd1af40000000000003058000001fd1b5800000000000034b1000001fd1bbc0000000000003933000001fd1c200000000000003ddb000001fd1c8400000000000042a9000001fd1ce8000000000000479c000001fd1d4c0000000000004cb1000001fd1db000000000000051e8000001fd1e14000000000000573e000001fd1e780000000000005cb3000001fd1edc0000000000006246000001fd1f4000000000000067f3000001fd1fa40000000000006dba000001fd20080000000000007399000001fd206c000000000000798f000001fd20d00000000000007f9a000001fd213400000000000085b7000001fd21980000000000008be6000001fd21fc0000000000009225000001fd22600000000000009871000001fd22c40000000000009eca000001fd2328000000000000a52d000001fd238c000000000000ab98000001fd23f0000000000000b20a000001fd2454000000000000b881000001fd24b8000000000000befb000001fd251c000000000000c576000001fd2580000000000000cbf1000001fd25e4000000000000d269000001fd2648000000000000d8dd000001fd26ac000000000000df4a000001fd2710000000000000e5b0000001fd2774000000000000ec0d000001fd27d8000000000000f25d000001fd283c000000000000f8a1000001fd28a0000000000000fed5000001fd290400000000000104f9000001fd29680000000000010b0a000001fd29cc0000000000011107000001fd2a3000000000000116ee000001fd2a940000000000011cbd000001fd2af80000000000012274000001fd2b5c000000000001280f000001fd2bc00000000000012d8e000001fd2c2400000000000132ef000001fd2c880000000000013831000001fd2cec0000000000013d51000001fd2d500000000000014250000001fd2db4000000000001472a000001fd2e180000000000014bdf000001fd2e7c000000000001506e000001fd2ee000000000000154d5000001fd2f440000000000015913000001fd2fa80000000000015d27000001fd300c000000000001610f000001fd307000000000000164cb000001fd30d4000000000001685a000001fd31380000000000016bba000001fd319c0000000000016eea000001fd320000000000000171ea000001fd326400000000000174b9000001fd32c80000000000017756000001fd332c00000000000179c0000001fd33900000000000017bf6000001fd33f40000000000017df9000001fd34580000000000017fc7000001fd34bc0000000000018160000001fd352000000000000182c3000001fd358400000000000183f0000001fd35e800000000000184e7000001fd364c00000000000185a8000001fd36b00000000000018631000001fd37140000000000018684000001fd3778000000000001869f000001fd37dc0000000000018684000001fd38400000000000018632000001fd38a400000000000185a8000001fd390800000000000184e8000001fd396c00000000000183f1000001fd39d000000000000182c4000001fd3a340000000000018161000001fd3a980000000000017fc9000001fd3afc0000000000017dfb000001fd3b600000000000017bf9000001fd3bc400000000000179c2000001fd3c280000000000017759000001fd3c8c00000000000174bc000001fd3cf000000000000171ed000001fd3d540000000000016eee000001fd3db80000000000016bbd000001fd3e1c000000000001685e000001fd3e8000000000000164cf000001fd3ee40000000000016114000001fd3f480000000000015d2c000001fd3fac0000000000015918000001fd401000000000000154da000001fd40740000000000015073000001fd40d80000000000014be5000001fd413c0000000000014730000001fd41a00000000000014255000001fd42040000000000013d57000001fd42680000000000013837000001fd42cc00000000000132f5000001fd43300000000000012d94000001fd43940000000000012815000001fd43f8000000000001227a000001fd445c0000000000011cc4000001fd44c000000000000116f5000001fd4524000000000001110e000001fd45880000000000010b11000001fd45ec0000000000010500000001fd4650000000000000fedc000001fd46b4000000000000f8a8000001fd4718000000000000f265000001fd477c000000000000ec14000001fd47e0000000000000e5b8000001fd4844000000000000df52000001fd48a8000000000000d8e4000001fd490c000000000000d270000001fd4970000000000000cbf8000001fd49d4000000000000c57e000001fd4a38000000000000bf02000001fd4a9c000000000000b888000001fd4b00000000000000b212000001fd4b64000000000000aba0000001fd4bc8000000000000a534000001fd4c2c0000000000009ed1000001fd4c900000000000009879000001fd4cf4000000000000922c000001fd4d580000000000008bed000001fd4dbc00000000000085be000001fd4e200000000000007fa1000001fd4e840000000000007996000001fd4ee800000000000073a0000001fd4f4c0000000000006dc1000001fd4fb000000000000067fa000001fd5014000000000000624c000001fd50780000000000005cba000001fd50dc0000000000005745000001fd514000000000000051ee000001fd51a40000000000004cb7000001fd520800000000000047a2000001fd526c00000000000042af000001fd52d00000000000003de1000001fd53340000000000003938000001fd539800000000000034b6000001fd53fc000000000000305d000001fd54600000000000002c2d000001fd54c40000000000002827000001fd5528000000000000244e000001fd558c00000000000020a1000001fd55f00000000000001d21000001fd565400000000000019d1000001fd56b800000000000016b1000001fd571c00000000000013c1000001fd57800000000000001103000001fd57e40000000000000e77000001fd58480000000000000c1e000001fd58ac00000000000009f8000001fd59100000000000000807000001fd5974000000000000064b000001fd59d800000000000004c4000001fd5a3c0000000000000372000001fd5aa00000000000000257000001fd5b040000000000000172000001fd5b6800000000000000c4000001fd5bcc000000000000004c000001fd5c30000000000000000c000001fd5c940000000000000002000001fd5cf80000000000000030000001fd5d5c0000000000000095000001fd5dc00000000000000130000001fd5e240000000000000203000001fd5e88000000000000030b000001fd5eec000000000000044a000001fd5f5000000000000005bf000001fd5fb4000000000000076a000001fd60180000000000000949000001fd607c0000000000000b5c000001fd60e00000000000000da4000001fd6144000000000000101f000001fd61a800000000000012cc000001fd620c00000000000015ab000001fd627000000000000018bb000001fd62d40000000000001bfb000001fd63380000000000001f6a000001fd639c0000000000002308000001fd640000000000000026d2000001fd64640000000000002ac9000001fd64c80000000000002eeb000001fd652c0000000000003336000001fd659000000000000037aa000001fd65f40000000000003c46000001fd66580000000000004108000001fd66bc00000000000045ee000001fd67200000000000004af8000001fd67840000000000005023000001fd67e8000000000000556f000001fd684c0000000000005ada000001fd68b00000000000006063000001fd69140000000000006607000001fd69780000000000006bc6000001fd69dc000000000000719d000001fd6a40000000000000778b000001fd6aa40000000000007d8f000001fd6b0800000000000083a7000001fd6b6c00000000000089d0000001fd6bd00000000000009009000001fd6c340000000000009651000001fd6c980000000000009ca6000001fd6cfc000000000000a306000001fd6d60000000000000a96e000001fd6dc4000000000000afde000001fd6e28000000000000b654000001fd6e8c000000000000bccd000001fd6ef0000000000000c348000001fd6f54000000000000c9c3000001fd6fb8000000000000d03c000001fd701c000000000000d6b2000001fd7080000000000000dd22000001fd70e4000000000000e38a000001fd7148000000000000e9ea000001fd71ac000000000000f03f000001fd7210000000000000f687000001fd7274000000000000fcc1000001fd72d800000000000102ea000001fd733c0000000000010902000001fd73a00000000000010f06000001fd740400000000000114f4000001fd74680000000000011acc000001fd74cc000000000001208b000001fd7530000000000001262f000001fd75940000000000012bb8000001fd75f80000000000013123000001fd765c0000000000013670000001fd76c00000000000013b9c000001fd772400000000000140a6000001fd7788000000000001458c000001fd77ec0000000000014a4e000001fd78500000000000014eea000001fd78b4000000000001535f000001fd791800000000000157ab000001fd797c0000000000015bcd000001fd79e00000000000015fc4000001fd7a44000000000001638f000001fd7aa8000000000001672d000001fd7b0c0000000000016a9c000001fd7b700000000000016ddd000001fd7bd400000000000170ed000001fd7c3800000000000173cd000001fd7c9c000000000001767a000001fd7d0000000000000178f5000001fd7d640000000000017b3d000001fd7dc80000000000017d52000001fd7e2c0000000000017f31000001fd7e9000000000000180dc000001fd7ef40000000000018251000001fd7f580000000000018391000001fd7fbc000000000001849a000001fd8020000000000001856d000001fd80840000000000018609000001fd80e8000000000001866e000001fd814c000000000001869c000001fd81b00000000000018693000001fd82140000000000018654000001fd827800000000000185dd000001fd82dc000000000001852f000001fd8340000000000001844a000001fd83a40000000000018330000001fd840800000000000181df000001fd846c0000000000018058000001fd84d00000000000017e9c000001fd85340000000000017cac000001fd85980000000000017a87000001fd85fc000000000001782e000001fd866000000000000175a2000001fd86c400000000000172e5000001fd87280000000000016ff5000001fd878c0000000000016cd5000001fd87f00000000000016985000001fd88540000000000016607000001fd88b8000000000001625a000001fd891c0000000000015e81000001fd89800000000000015a7c000001fd89e4000000000001564c000001fd8a4800000000000151f3000001fd8aac0000000000014d71000001fd8b1000000000000148c9000001fd8b7400000000000143fb000001fd8bd80000000000013f09000001fd8c3c00000000000139f4000001fd8ca000000000000134bd000001fd8d040000000000012f67000001fd8d6800000000000129f2000001fd8dcc0000000000012460000001fd8e300000000000011eb3000001fd8e9400000000000118ec000001fd8ef8000000000001130d000001fd8f5c0000000000010d17000001fd8fc0000000000001070c000001fd902400000000000100ef000001fd9088000000000000fac0000001fd90ec000000000000f481000001fd9150000000000000ee35000001fd91b4000000000000e7dd000001fd9218000000000000e17a000001fd927c000000000000db0e000001fd92e0000000000000d49c000001fd9344000000000000ce26000001fd93a8000000000000c7ac000001fd940c000000000000c130000001fd9470000000000000bab6000001fd94d4000000000000b43e000001fd9538000000000000adca000001fd959c000000000000a75c000001fd9600000000000000a0f6000001fd96640000000000009a9a000001fd96c80000000000009449000001fd972c0000000000008e06000001fd979000000000000087d1000001fd97f400000000000081ad000001fd98580000000000007b9c000001fd98bc000000000000759f000001fd99200000000000006fb8000001fd998400000000000069e8000001fd99e80000000000006432000001fd9a4c0000000000005e96000001fd9ab00000000000005917000001fd9b1400000000000053b6000001fd9b780000000000004e74000001fd9bdc0000000000004954000001fd9c400000000000004455000001fd9ca40000000000003f7b000001fd9d080000000000003ac5000001fd9d6c0000000000003636000001fd9dd000000000000031cf000001fd9e340000000000002d91000001fd9e98000000000000297d000001fd9efc0000000000002594000001fd9f6000000000000021d8000001fd9fc40000000000001e49000001fda0280000000000001ae9000001fda08c00000000000017b9000001fda0f000000000000014b8000001fda15400000000000011e9000001fda1b80000000000000f4c000001fda21c0000000000000ce2000001fda2800000000000000aab000001fda2e400000000000008a8000001fda34800000000000006da000001fda3ac0000000000000541000001fda41000000000000003de000001fda47400000000000002b0000001fda4d800000000000001b9000001fda53c00000000000000f8000001fda5a0000000000000006e000001fda604000000000000001b000001fda6680000000000000000000001fda6cc000000000000001b000001fda730000000000000006d000001fda79400000000000000f6000001fda7f800000000000001b6000001fda85c00000000000002ac000001fda8c000000000000003d9000001fda924000000000000053c000001fda98800000000000006d4000001fda9ec00000000000008a2000001fdaa500000000000000aa4000001fdaab40000000000000cda000001fdab180000000000000f44000001fdab7c00000000000011e0000001fdabe000000000000014ae000001fdac4400000000000017ae000001fdaca80000000000001ade000001fdad0c0000000000001e3d000001fdad7000000000000021cb000001fdadd40000000000002587000001fdae38000000000000296f000001fdae9c0000000000002d82000001fdaf0000000000000031c0000001fdaf640000000000003626000001fdafc80000000000003ab5000001fdb02c0000000000003f6a000001fdb0900000000000004444

**Comment by benthecarman** [comment]
I don't think this is the full offer, I can't decode it
