### ISSUE TITLE
DLCWallet OracleOutcome computation for completed events too slow

### ISSUE THREAD

**Issue by nkohen** [bitcoin-s/bitcoin-s#3213]
This line is the culprit:
```
            contractInfo.sigPointMap(aggSig.sig.toPrivateKey.publicKey)
```
which takes a fresh (non-cached) `ContractInfo` and computes all adaptor points and all outcomes and then finds the outcome at the index of the detected adaptor point which was used.

Some options:
1. Store the outcome in `DLCDb` (the global table) as an Option so that it still needs to be computed, but only once so that all future calls will just do a database read instead of an expensive computation. I personally think this is the biggest bang for our buck as it will effectively solve the problem and is a minimal addition of a nullable column.
2. Store the outcome for every CETSig/Adaptor point. This requires a significant increase in data to be stored in the DB, but removes the problem here entirely.

Curious to hear @benthecarman's thoughts?

Generally I will note however that short of storing a linked structure (a binary trie in this case) of adaptor points, there is no particularly nice way to handle this problem which is why I'm in favor of just storing the executed outcome in the DLCDb at the moment.

**Comment by benthecarman** [comment]
Yeah we should just store it in the global table
