### ISSUE TITLE
Mac builds appear to be broken

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3266]
https://github.com/bitcoin-s/bitcoin-s/runs/2819195908#step:7:609

![Screenshot from 2021-06-14 13-07-16](https://user-images.githubusercontent.com/3514957/121938490-7f5ef600-cd11-11eb-8654-ce069f4ffbb4.png)

First seen on 4f936b2cbf857934d6370ec6d8a055d9ee632444

**Comment by benthecarman** [comment]
> Your Apple ID account is attached to other providers. You will need to specify which provider you intend to submit content to. Please contact us if you have questions or need help. (1627)

**Comment by benthecarman** [comment]
Maybe from the atomic finance beta?
