### ISSUE TITLE
Preview graph during offer fails when using a contract template from the contract explorer

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3288]
https://test.oracle.suredbits.com/contract/numeric/1970e511b89f1e0d051d098704334fb183a6dec9bb65f5bb1ce1214ffb77e7df/db9b8cde0d6b8e89d91b28b1d405bcd52e94b41ff7adfeca4bafe8396bae557a

version: 5fbdf829

>2021-06-17T15:31:24UTC INFO [BitcoinSServerMain] version=1.6.0-145-5fbdf829-SNAPSHOT

If i paste this in and click preview graph on this screen 

![Screenshot from 2021-06-17 10-36-49](https://user-images.githubusercontent.com/3514957/122428905-f2f24480-cf57-11eb-9db4-2e936a8b6e3f.png)

I get this exception

>[error] java.lang.IndexOutOfBoundsException: 2 is out of bounds (min 0, max 1)
[error]         at scala.collection.immutable.Vector.ioob(Vector.scala:274)
[error]         at scala.collection.immutable.Vector1.apply(Vector.scala:380)
[error]         at org.bitcoins.core.protocol.dlc.models.DLCPayoutCurve.componentFor(DLCPayoutCurve.scala:47)
[error]         at org.bitcoins.core.protocol.dlc.models.DLCPayoutCurve.getPayout(DLCPayoutCurve.scala:59)
[error]         at org.bitcoins.core.protocol.dlc.models.DLCPayoutCurve.apply(DLCPayoutCurve.scala:76)
[error]         at org.bitcoins.gui.dlc.DLCPlotUtil$.$anonfun$plotCETsWithOriginalCurve$1(DLCPlotUtil.scala:50)
[error]         at scala.runtime.java8.JFunction1$mcII$sp.apply(JFunction1$mcII$sp.scala:17)
[error]         at scala.collection.immutable.VectorStatics$.mapElemsRest(Vector.scala:1886)
[error]         at scala.collection.immutable.VectorStatics$.mapElems(Vector.scala:1901)
[error]         at scala.collection.immutable.Vector4.map(Vector.scala:1899)
[error]         at scala.collection.immutable.Vector4.map(Vector.scala:643)
[error]         at org.bitcoins.gui.dlc.DLCPlotUtil$.plotCETsWithOriginalCurve(DLCPlotUtil.scala:50)
[error]         at org.bitcoins.gui.dlc.DLCPlotUtil$.plotCETsWithOriginalCurve(DLCPlotUtil.scala:24)
[error]         at org.bitcoins.gui.dlc.dialog.CreateDLCOfferDialog$$anon$25.$anonfun$new$4(CreateDLCOfferDialog.scala:263)
[error]         at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
[error]         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
[error]         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
[error]         at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
[error]         at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
[error]         at javafx.event.Event.fireEvent(Event.java:198)
[error]         at javafx.scene.Node.fireEvent(Node.java:8792)
[error]         at javafx.scene.control.Button.fire(Button.java:203)
[error]         at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
[error]         at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
[error]         at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
[error]         at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
[error]         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
[error]         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
[error]         at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
[error]         at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
[error]         at javafx.event.Event.fireEvent(Event.java:198)
[error]         at javafx.scene.Scene$MouseHandler.process(Scene.java:3861)
[error]         at javafx.scene.Scene.processMouseEvent(Scene.java:1854)
[error]         at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2587)
[error]         at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
[error]         at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
[error]         at java.base/java.security.AccessController.doPrivileged(Native Method)
[error]         at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
[error]         at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:413)
[error]         at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
[error]         at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
[error]         at com.sun.glass.ui.View.notifyMouse(View.java:942)
[error]         at com.sun.glass.ui.gtk.GtkApplication.enterNestedEventLoopImpl(Native Method)
[error]         at com.sun.glass.ui.gtk.GtkApplication._enterNestedEventLoop(GtkApplication.java:347)
[error]         at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:513)
[error]         at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
[error]         at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:636)
[error]         at javafx.stage.Stage.showAndWait(Stage.java:465)
[error]         at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
[error]         at javafx.scene.control.Dialog.showAndWait(Dialog.java:346)
[error]         at scalafx.scene.control.Dialog.showAndWait(Dialog.scala:107)
[error]         at org.bitcoins.gui.dlc.dialog.CreateDLCOfferDialog.showAndWait(CreateDLCOfferDialog.scala:528)
[error]         at org.bitcoins.gui.dlc.DLCPaneModel.onOffer(DLCPaneModel.scala:108)
[error]         at org.bitcoins.gui.dlc.DLCPane$$anon$3$$anon$4.handle(DLCPane.scala:37)
[error]         at org.bitcoins.gui.dlc.DLCPane$$anon$3$$anon$4.handle(DLCPane.scala:36)
[error]         at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
[error]         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
[error]         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
[error]         at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
[error]         at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
[error]         at javafx.event.Event.fireEvent(Event.java:198)
[error]         at javafx.scene.Node.fireEvent(Node.java:8792)
[error]         at javafx.scene.control.Button.fire(Button.java:203)
[error]         at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
[error]         at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
[error]         at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
[error]         at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
[error]         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
[error]         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
[error]         at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[error]         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[error]         at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
[error]         at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
[error]         at javafx.event.Event.fireEvent(Event.java:198)
[error]         at javafx.scene.Scene$MouseHandler.process(Scene.java:3861)
[error]         at javafx.scene.Scene.processMouseEvent(Scene.java:1854)
[error]         at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2587)
[error]         at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
[error]         at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
[error]         at java.base/java.security.AccessController.doPrivileged(Native Method)
[error]         at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
[error]         at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:413)
[error]         at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
[error]         at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
[error]         at com.sun.glass.ui.View.notifyMouse(View.java:942)
[error]         at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
[error]         at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by benthecarman** [comment]
The error here was that all the potential outcomes were not covered, we should fix this with a better error message when this occurs

**Comment by Christewart** [comment]
As @benthecarman notes, this is likely being caused by #3296
