### ISSUE TITLE
Add missing LND gRPC Services

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-s/bitcoin-s#3291]
Guide on how to add/update the LndRpcClient is here: https://bitcoin-s.org/docs/rpc/lnd-rpc#updating-to-a-new-lnd-version

We are missing the following:

- [ ] autopilotrpc
- [ ] chainrpc
- [ ] routerrpc
- [ ] watchtowerrpc
- [ ] wtclientrpc
- [ ] verrpc

**Comment by Christewart** [comment]
done in #5554
