### ISSUE TITLE
Neutrino Config tab does not auto-populate Peer Address field on testnet

### ISSUE THREAD

**Issue by user411** [bitcoin-s/bitcoin-s#3301]
**Describe the bug**
Neutrino Config tab does not auto-populate Peer Address field on testnet

**To Reproduce**
Checkout bitcoin-s repo
Run sbt bundle/compile with network = testnet3 set in bitcoin-s.conf
Notice that there is nothing pre-populated in the Peer Address field

**Expected behavior**
There is a default value in the Peer Address field

**Logs**

**Platform (please complete the following information):**
 - OS: macOS
 - Version: top of tree

**Additional context**

**Comment by benthecarman** [comment]
This isn't totally doable as we currently populate the peer address field based on what is in the config, which defaults to the suredbits mainnet node. To make this work for testnet we would have to either have a separate config option for each network (bad/ugly), or hardcode in the peer addresses (also bad imo).

Imo it should be up to the user to correctly choose a peer. Most likely if you are using testnet you are more technically inclinded and should be able to figure out a testnet peer.
