### ISSUE TITLE
testnet3 logging broken

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3304]
i am currently doing IBD, logging is working to stdout, but not being written to `$HOME/.testnet3/bitcoin-s.log`

This is on  97785561bad24a802cecfcd099706a602912a177

![Screenshot from 2021-06-21 11-41-41](https://user-images.githubusercontent.com/3514957/122798007-b428fb00-d285-11eb-80b9-c188263846d4.png)

**Comment by benthecarman** [comment]
Working for me on fafc564da81cf3fcdc739299a215f0a139dbcb7c

this was when I did

`sbt bundle/universal:stage` and then `./app/bundle/target/universal/stage/bin/bitcoin-s-bundle`

**Comment by Christewart** [comment]
FWIW, testnet3 logging did seem to be working on  5f40d5ddf3bc3fef09a269ca28f954d697ff881b

I just did some DLCs when testing that commit using `sbt bundle/run`

**Comment by Christewart** [comment]
So since neither of us can reproduce, closing.

**Comment by Christewart** [comment]
I just reproduced this on  53cafa789847a3d1a18279aff2aabe9fa4e35f08 when trying to get to the bottom of what is going on in #3337 


On the top is `appServer/run` and on the bottom is `tail -F ~/.bitcoin-s/testnet3/bitcoin-s.log` 

![Screenshot from 2021-06-29 13-13-01](https://user-images.githubusercontent.com/3514957/123847246-fd0f2e00-d8db-11eb-8ffe-cbaca233591d.png)

**Comment by benthecarman** [comment]
Can reproduce locally too, looks like they are being logged in my mainnet log file

**Comment by benthecarman** [comment]
I think this is being caused by a combination of #3285 and #3327

We read the network config on the bundle startup based on what is in the `bitcoin-s.conf` file and set our log location to that. However, if bitcoind is using a different network, we will switch to say testnet and not be able to update our log location.

I am not sure the best way to resolve this, besides making a single log file for all networks

**Comment by benthecarman** [comment]
> I think this is being caused by a combination of #3285 and #3327
> 
> We reading the network config on the bundle startup based on what is in the `bitcoin-s.conf` file and setting our log location to that. However, if bitcoind is using a different network, we will switch to say testnet and not be able to update our log location.

**Comment by Christewart** [comment]
> However, if bitcoind is using a different network, we will switch to say testnet and not be able to update our log location.


FWIW, i was experiencing this with a neutrino backend not bitcoind

**Comment by Christewart** [comment]
Just to document a conversation @benthecarman and I had, we now think his analysis is possibly wrong as he was assuming i was doing `bundle/run`. 

In reality, these logs are not being displayed when i'm using headless bitcoin-s with `appServer/run`

**Comment by Christewart** [comment]
Mainnet is not working either for me on  78e2fceb908a5cff1d4cdee7b759c78bd9aca88d

![Screenshot from 2021-06-30 10-57-12](https://user-images.githubusercontent.com/3514957/123993406-04910e80-d992-11eb-9812-29862c2da3ad.png)

**Comment by benthecarman** [comment]
I can reproduce, this only happens when using the app server

**Comment by Christewart** [comment]
Yeah but why?
