### ISSUE TITLE
Overpaying fee by 4122% on testnet3

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3306]
https://blockstream.info/testnet/tx/536982efee1e20650b3620e004ebd2e3865cd7a30207ac297e268753b1d08a5b

Obviously this isn't a huge deal since it is testnet, but i would like to keep my testnet coins too. We should double check that this is what the default fee estimator is actually recommending us. I have not set any custom configurations for fee estimation

occurred on 3ef842eca51c58c103c56034d1f1fe100439f7be

**Comment by benthecarman** [comment]
We default to the mempool.space 6 block target fee provider

https://github.com/bitcoin-s/bitcoin-s/blob/master/app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala#L98

**Comment by Christewart** [comment]
So i don't see any network specific configuration there, does mempool.space not have a different api for testnet?

**Comment by benthecarman** [comment]
I don't think any fee rate apis do

**Comment by Christewart** [comment]
https://api.bitgo.com/docs/#section/Environments 

bitcoin core obviously does

i don't see one here https://bitcoiner.live/doc/api

I don't see on mempool.space https://mempool.space/api

I personally don't think we should support apis that doesn't support testnet. It goes to show how seriously they take their service IMO.

**Comment by benthecarman** [comment]
> I personally don't think we should support apis that doesn't support testnet. It goes to show how seriously they take their service IMO.

imo supporting shitcoins is worse lol

**Comment by benthecarman** [comment]
Looks like mempool.space does

https://mempool.space/testnet/api
