### ISSUE TITLE
Make file reading happen on client side rather than server side

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3307]
For DLCs, we should read the the contents of files attached to the GUI flow on the client side, and then send them over to the server as bytes rather than sending the reference to the file to the server.

This makes it so that you don't necessarily need to be on the same machine to execute large accepts/signs/broadcasts

**Comment by benthecarman** [comment]
After starting on this I realized that if we do this then we'd have to get rid of the destination file, I am not sure that is exactly what we want.

**Comment by Christewart** [comment]
> After starting on this I realized that if we do this then we'd have to get rid of the destination file, I am not sure that is exactly what we want.

Hmm, could you link to what you mean? If I understand what you are saying, we should definitely get rid of it. This should be something handled on the client side I think rather than server side. If we still want to right the result to a file on the client side, that is ok. 

If we were to deploy the wallet to the cloud, we probably don't want to have the destination file written to the server side. We want it written on the client's host so they can then share it with their counterparty. In the context of a local development environment, i don't think this really affects things as the client can still write to the same underlying OS as the server is running on.

**Comment by benthecarman** [comment]
Yeah currently it writes to file from the server side. This was done because the reason we added files was because of the cli timing out. If the cli times out then it can't write the output to a file.

**Comment by Christewart** [comment]
A couple of points 

1. With @user411 joining us, we likely are moving away from `bitcoin-s-cli` into what his preferred tooling is client side that won't have such restrictions on it. 
2. We put a ton of performance improvements into 1.7 (#3089 , #3067, #3046). Maybe this isn't as large of concern now? I guess we haven't tested multi oracle stuff though, which i think is probably the problem? cc @nkohen

**Comment by benthecarman** [comment]
1. Agreed, however, I thought this issue was for the current Gui
2. I think it's still a concern for less powerful machines.

**Comment by Christewart** [comment]
>     1. Agreed, however, I thought this issue was for the current Gui
> 
>     2. I think it's still a concern for less powerful machines.

Yeah, you are right. I definitely wasn't clear on 1. I guess we need to have some sort of solution in place for @user411 so he can actually send requests and receive responses from the server. I guess the rpcs we use in the GUI currently do have the `file` nameinside the rpc method. Do we have any alternatives for him to use?

And yeah, (2) is most definitely still a concern. Maybe we need to start discussing your rounding mode pr more seriously (#3259).

**Comment by benthecarman** [comment]
For 1 everything should be good to go. 

For 2, yeah rounding mode and finding other optimizations is all we can do.

**Comment by Christewart** [comment]
Ok, yeah i think we should try a couple of these using other endpoints to make sure ivan doesn't run into any surprises. If it is `bitcoin-s-cli` timing out i guess that is ok, but we want to make sure those rpcs actually work since it seems we might not be testing them too heavily currently?

**Comment by benthecarman** [comment]
They are currently used whenever you don't use a file, which is most of the time at least for me

**Comment by Christewart** [comment]
> They are currently used whenever you don't use a file, which is most of the time at least for me

Hmm, ok. I use files most of the time unless it is a small enum

**Comment by Christewart** [comment]
> > They are currently used whenever you don't use a file, which is most of the time at least for me
> 
> Hmm, ok. I use files most of the time unless it is a small enum

I tell users to use the file flow too rather than copy pasting large messages.

**Comment by Christewart** [comment]
I'm moving this to 0.8 as I would like to figure out how to add tests for regressions on performance. This seems like a good place to e2e test performance on low resource machines like CI to see how long it takes to create these things?
