### ISSUE TITLE
Cannot resolve new javafx dependencies

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3326]
i'm not sure why, but we haven't updated our javafx in quite awhile because the builds won't resolve

See #3318 

https://github.com/bitcoin-s/bitcoin-s/pull/3318/checks?check_run_id=2900682378#step:5:239

**Comment by Christewart** [comment]
Filed issue on sbt repo: https://github.com/sbt/sbt/issues/6564

**Comment by benthecarman** [comment]
I wonder if this has to do with how we resolve them, ie:

```
    lazy val javaFxMedia =
      "org.openjfx" % s"javafx-media" % V.javaFxV classifier osName withSources () withJavadoc ()
```

**Comment by Christewart** [comment]
I can manually fetch this with a `wget` command.

**Comment by Christewart** [comment]
fixed now
