### ISSUE TITLE
Network specific `View on Oracle Explorer`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3331]
This might be a nice feature for @user411 to implement. It is pretty small in scope, should be easy to view on his local wallet too. 

If we think this is a good idea, we should merge this PR, and file an issue for him to implement the testnet3 feature. Thoughts?

_Originally posted by @Christewart in https://github.com/bitcoin-s/bitcoin-s/pull/3328#discussion_r658739866_

**Comment by user411** [comment]
Addressed with https://github.com/bitcoin-s/bitcoin-s/pull/3332
