### ISSUE TITLE
Issue with negative values in numeric contract UI?

### ISSUE THREAD

**Issue by user411** [bitcoin-s/bitcoin-s#3375]
**Describe the bug**
Seems like having negative values in a numeric contract may be causing an issue at the frontend. I make one contract with -127 bound and one with -255 and got this type of behavior locally.

**To Reproduce**
1. Make a contract with negative Min Value
2. Copy contract announcement into a new Offer
3. Notice lines up to 'Event Id' render and contract details do not
4. No error seems to print

**Expected behavior**
Full UI to show up or error line prints

![Screen Shot 2021-07-07 at 1 40 08 PM](https://user-images.githubusercontent.com/22351459/124818978-e47cc480-df28-11eb-91eb-8d40169a5848.png)
<img width="407" alt="Screen Shot 2021-07-07 at 1 40 15 PM" src="https://user-images.githubusercontent.com/22351459/124818980-e6468800-df28-11eb-87da-9d73668549a7.png">

**Comment by Christewart** [comment]
fixed in #3376
