### ISSUE TITLE
Get started on implementing seed derivation

### ISSUE THREAD

**Issue by torkelrogstad** [bitcoin-s/bitcoin-s#342]
Alternatives:

## LND seed/aezeed
[AEZ site](http://web.cs.ucdavis.edu/~rogaway/aez/)
[LND subproject](https://github.com/lightningnetwork/lnd/tree/master/aezeed)  
[LND PR](https://github.com/lightningnetwork/lnd/pull/773) introducing the cipher seed scheme
[aezeed online demo](https://gugger.guru/blockchain-demo/#!/aezeed) (_NOTE:_ don't know who made this)
[AEZ lib used by LND](https://git.schwanenlied.me/yawning/aez/src/master/aez.go)

### Pros

- Birthdate, allowing for much faster sync
- Has versioning
- Password can be changed
- Uses the same word list as BIP39

### Cons

- Not widely used
- Requires using AEZ crypto, would require us to introduce a new dependency?

### Pros:
- Used by the big majority of SPV wallets 
- Easy to implement

### Cons: 

- No birthdate
- No version number

## Electrum seeds
[Electrum docs](http://docs.electrum.org/en/latest/seedphrase.html)

### Pros: 

- Has version number

### Cons: 
- Only used by Electrum
- No birthdate

**Comment by Christewart** [comment]
We ended up using BIP39 #353
