### ISSUE TITLE
Investigate `DLCOracle.createNewEvent()` for reusing key indexes that could result in nonce leakage

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3428]
https://github.com/bitcoin-s/bitcoin-s/blob/78e2fceb908a5cff1d4cdee7b759c78bd9aca88d/dlc-oracle/src/main/scala/org/bitcoins/dlc/oracle/DLCOracle.scala#L180

I'm wondering if there are certain situations where this could result in reusage of a nonce. Maybe to be more defensive we shoudl throw and error if we can't retrieve an index from `RValueDAO`? 

In general, I think we should add methods to `RValueDAO` that works like `incrementAndGet()` inside of `java.util.concurrent.atomic.AtomicInteger`

It seems like us automatically incrementing indices ourselves in various places throughout the application code seems likely to lead to nonce reusage. Thankfully we have a unique property at the sql level to prevent this from happening in #3415

**Comment by benthecarman** [comment]
We should be safe from nonce reuse because `nonce` is the primary key in the database and `keyIndex` is also unique

**Comment by Christewart** [comment]
> We should be safe from nonce reuse because `nonce` is the primary key in the database and `keyIndex` is also unique

So this make sense, but still is not very friendly. Now you can call `.createNewEvent()` from two separate threads in two separate places in your application and have one of them fail randomly because they were both trying to use the same key index
