### ISSUE TITLE
Implement ability to connect to a bitcoin node and determine if they support blockfilter services

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3450]
https://github.com/bitcoin/bips/blob/master/bip-0157.mediawiki#node-operation

If we connect to a bitcoin node, but they don't support blockfilters over p2p, we shouldn't use that node for initial block download as they can't serve us block filters.

In the future, we may way want to connect to some nodes that don't serve block filters as they can still be used to retrieve full blocks.

**Comment by benthecarman** [comment]
This was removed in #2938 (I forget why) https://github.com/bitcoin-s/bitcoin-s/pull/2938/files#diff-749e6f2f9a4cbd0e78f58a0c4ee2a2ff4871c16ac6856d807cc2d37e7b94fa3eL166

but in #2949 I started adding the ability to save and filter peers by their service identifiers
