### ISSUE TITLE
Automate/document the setup process for the control port on tor

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3458]
With DLC p2p on #3402 we need to have a control port for tor

We need to either automate the configuration (best option) or document the need for the control port on our site.

These are the instructions needed to do this 

![Screenshot from 2021-07-28 10-20-30](https://user-images.githubusercontent.com/3514957/127349261-81039009-a456-4baa-b152-f2e9ef063d2a.png)

![Screenshot from 2021-07-28 10-20-50](https://user-images.githubusercontent.com/3514957/127349260-c0a6244f-681a-40c7-af38-40e8931caa10.png)

**Comment by benthecarman** [comment]
Also need to have the user add themselves to the tor user group

`sudo usermod -a -G debian-tor $USER`

then restart

**Comment by Christewart** [comment]
Related to #3483 and #3495

**Comment by benthecarman** [comment]
In #3483 the control port will be set for the user unless they already have tor running under a different configuration setting

**Comment by Christewart** [comment]
Taken care of in #3483
