### ISSUE TITLE
Rework how `Client.start()` works

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3465]
https://github.com/bitcoin-s/bitcoin-s/blob/e2c2798e60ac26728c6f42d9c49a59d4745dd5e3/app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala#L162

This will not work with cookie based authentication (#2891) since we try to call `startBinary()` everytime bitcoind is started

https://github.com/bitcoin-s/bitcoin-s/blob/78f4dfb8c66eedc9c5b758ae5880274bf74571d2/bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/Client.scala#L134

This leads to an error that looks like this:

>[error] Error: Cannot obtain a lock on data directory /home/chris/.bitcoin. Bitcoin Core is probably already running.
[info] 2021-08-02T12:51:49UTC INFO [BitcoindV21RpcClient] Could not start bitcoind instance! Message: No content to map due to end-of-input
[info]  at [Source: (String)""; line: 1, column: 0]
[info] 2021-08-02T12:51:49UTC ERROR [BitcoinSServerMain] Failed to initialize configuration for BitcoinServerMain
[info] com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
[info]  at [Source: (String)""; line: 1, column: 0]
[info]  at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
[info]  at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4360)
[info]  at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4176)
[info]  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2476)
[info]  at play.api.libs.json.jackson.JacksonJson$.parseJsValue(JacksonJson.scala:282)
[info]  at play.api.libs.json.StaticBinding$.parseJsValue(StaticBinding.scala:17)
[info]  at play.api.libs.json.Json$.parse(Json.scala:173)
[info]  at org.bitcoins.rpc.client.common.Client.$anonfun$getPayload$1(Client.scala:340)
[info]  at scala.util.Success.map(Try.scala:262)

Since we error there, we never get to run this code which actually does the cookie authentication

https://github.com/bitcoin-s/bitcoin-s/blob/78f4dfb8c66eedc9c5b758ae5880274bf74571d2/bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/Client.scala#L156

## What needs to be done

We need to think about the various scenarios we need to handle to start bitcoind. There are two useful scenarios I can think of for the case that you want run bitcoind _locally_ as a backend to your bitcoin-s wallet

1. Your bitcoind is _not_ running, so bitcoin-s needs to start it and then authenticate with it
2. Your bitcoind _is_ running locally, so all you need to is authenticate with it.

It seems to me we handle case 1, but do not handle case 2. So we need to implement that.

**Comment by benthecarman** [comment]
This makes sense, we could probably call `bitcoin-cli ping` to see if bitcoind is running or not.

**Comment by Christewart** [comment]
Done in #3600
