### ISSUE TITLE
Add notification for user when funding tx is broadcast

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3486]
It seems like we can make a cooler notification when a funding txid is broadcast. Maybe something like 

>You successfully entered a DLC with your counterparty :tada: :tada: :tada:
>The funding txid is [txid-here]
>You can execute the refund clause of your DLC @ [insert-date-here]
> The oracle for your DLC is [insert oracle link here]

or something like that.

**Comment by user411** [comment]
Could approach this with a message/alert area over the regular DLC view in the right pane and transition to the DLC view once the funding tx is broadcast with status message.
