### ISSUE TITLE
Exception: class java.net.URISyntaxException

### ISSUE THREAD

**Issue by mattfaltyn** [bitcoin-s/bitcoin-s#3490]
**Describe the bug**
When trying to accept a DLC offer from Chris on the bitcoin-s wallet (**Version:** Bitcoin-S v1.7.0-53-831e0fd9-SNAPSHOT), I ran into this bug:
```
Exception: class java.net.URISyntaxException
Illegal character in path at index 69:
tcp://dmqnyzfhdeq4tdgnl7jtnrmwsklyzh4lsbmwufmz3pzzongzxd3ilyd.onion/<unresolved>:2862
```

**To Reproduce**
1. Open DLC offer via `Accept` button
2. Enter DLC Offer and Peer Address
3. Click `OK`

**Expected behavior**
I expected to accept the DLC offer when clicking the `OK` button.

**Logs**
See screenshot.
![Issue](https://user-images.githubusercontent.com/76570855/128403244-e06b7832-1d9a-465f-a903-d8f1e19262cf.png)

**Platform (please complete the following information):**
 - OS: macOS
 - Version 11.5.1
 - 1.8 GHz Dual-Core Intel Core i5

**Additional context**
Have I misconfigured Tor? May be worth reconfiguring Tor at our next demo meeting @Christewart.

**Comment by Christewart** [comment]
>Have I misconfigured Tor? May be worth reconfiguring Tor at our next demo meeting @Christewart.

I think this is a good guess but haven't looked into it personally. I ran through a demo on this commt (831e0fd96d19f75a45238be046fe605fd1531ec5) with @shreyanshyad this morning and didn't have issues

Either way, we either need to 

1. Fix the bug (if there is one)
2. Give a better error message if it a configuration error on the users part

**Comment by benthecarman** [comment]
It looks to me like a parsing bug because of the `Exception: class java.net.URISyntaxException`, however, unsure until we have the logs
