### ISSUE TITLE
Implement funding/closing txid fetching for DLC wallet for offerer now that we have `bitcoin-s.node.relay`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3510]
#3416 we should be able to find transactions for opening/closing of a DLC now that we can see unconfirmed txs gossiped on the network. 

This means I don't have to ask my acceptor what the txid to see it on a block explorer.

**Comment by benthecarman** [comment]
this should happen automicallty so long as we process the transaction

**Comment by Christewart** [comment]
Ok that is awesome! Let's just confirm at some point and then close this issue

**Comment by Christewart** [comment]
This worked out of the box :tada:
