### ISSUE TITLE
View on oracle explorer gives scala.MatchError exception

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3513]
A user reported that when they try do `View on Oracle Explorer` from the table view, they get a `scala.MatchError`

![Screenshot from 2021-08-10 10-46-56](https://user-images.githubusercontent.com/3514957/128894531-24781c5e-1614-49d4-bb63-9042463bab3b.png)

**Comment by user411** [comment]
Fixed by #3541
