### ISSUE TITLE
New GUI layout doesn't make it clear where to create an offer

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3519]
We need to make a big button that says "create offer" or something like that, I get where we need to paste the event hex currently, but I just think it isn't obvious where a user should be doing this ATM

![Screenshot from 2021-08-11 08-15-00](https://user-images.githubusercontent.com/3514957/129035345-7a3a332e-71eb-46f3-8b4a-fdcb962a8197.png)

**Comment by user411** [comment]
Addressed by #3567
