### ISSUE TITLE
Sending a tx in the new GUI doesn't seem to display the txid anywhere

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3538]
Notice that the address appears in the bottom left hand corner, but AFAICT the txid isn't displayed anywhere? 

![Screenshot from 2021-08-12 15-50-11](https://user-images.githubusercontent.com/3514957/129267917-ac5c9732-2dd8-47d1-9905-19ae56631857.png)

**Comment by user411** [comment]
Fixed by #3570
