### ISSUE TITLE
Reevaluate cors policy before releasing 1.8

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3614]
As discussed via Slack, we may not want this here. Probably want to bubble up to a NodeJS 'proxy server' that can handle calls from the frontend and act as a dev server on localhost.

But this works for testing oracle-server-ui now.

_Originally posted by @user411 in https://github.com/bitcoin-s/bitcoin-s/issues/3612#issuecomment-906734203_

**Comment by benthecarman** [comment]
what lnd has is you can whitelist who can make these kinds of requests, bitcoin-s could copy this and make it off by default and whitelist the proper address in the docker config for the umbrel apps
