### ISSUE TITLE
Bitcoind binaries have incorrect path on windows

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3626]
https://github.com/bitcoin-s/bitcoin-s/pull/3609/checks?check_run_id=3456501791#step:6:2873

This was found on #3609

<img width="1431" alt="Screen Shot 2021-08-29 at 5 01 46 PM" src="https://user-images.githubusercontent.com/3514957/131266733-2007ddc3-5f6d-4647-9017-1cb88af40b9b.png">

**Comment by benthecarman** [comment]
I am guessing the `downloadBitcoind` command failed

**Comment by Christewart** [comment]
fixed in #3609
