### ISSUE TITLE
Don't run oracleServer as root on docker

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3643]
I'm looking through the Dockerfile generated by sbt on dockerhub

https://hub.docker.com/layers/bitcoinscala/bitcoin-s-server/latest/images/sha256-1e35e7baeaa39b0c70c5a5f205cd1482d2fd9055a9da325d8f7368dc2d778e19?context=repo

The line in particular i'm concerned about is line 15

<img width="1431" alt="Screen Shot 2021-09-02 at 11 03 35 AM" src="https://user-images.githubusercontent.com/3514957/131878132-a9b47238-b128-4388-8415-55670a62a71f.png">

From the umbrel documentation it says that the service should not be run as root

https://github.com/getumbrel/umbrel/blob/master/apps/README.md#a-good-dockerfile

>Doesn't run the service as root.

**Comment by rorp** [comment]
Does it run the service or simply copies the artifacts?

**Comment by Christewart** [comment]
> Does it run the service or simply copies the artifacts?

We do have this line which registers the `bitcoin-s` user 

https://github.com/bitcoin-s/bitcoin-s/blob/114fbf35fe3582db595eab8768b4e69dd4d83c09/project/CommonSettings.scala#L183

and i think it may be switching to that user on line 16 with 

>/bin/sh -c id -u bitcoin-s
