### ISSUE TITLE
Wallet not finding funds from seed on fresh IBD

### ISSUE THREAD

**Issue by nkohen** [bitcoin-s/bitcoin-s#3688]
I was having issues with my db state and wanted to test just deleting my mainnet folder inside of bitcoin-s datadir (I zipped a backup first) and running from scratch (seeds dir untouched).

After finishing syncing, my balance from `cli getbalance` is `0` and so it would appear that my addresses are not being properly generated or else not properly found during sync.

Log file attached
[bitcoin-s.log](https://github.com/bitcoin-s/bitcoin-s/files/7220448/bitcoin-s.log)

**Comment by Christewart** [comment]
So I misunderstood you on the call. If you are doing a fresh IBD, the wallet will NOT generate a pool of addresses to check. You need to `rescan` to generate the pool of addresses. You can rescan with the commands available here: https://bitcoin-s.org/docs/next/wallet/wallet-rescan#rescan-from-cli

**Comment by nkohen** [comment]
Ah cool, I have all my funds now :) we might want to consider having some way of telling whether a seed is new or old when starting a fresh node so that the rescan can be automatic? Either way, I'll close this issue
