### ISSUE TITLE
`bitcoin-s.tor.enabled=false` does not work when used in a `bitcoin-s.conf` file

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3696]
**Describe the bug**
I am running on 698fe9e8 with sqlite. Here are is the `bitcoin-s.conf` i am running with 

```
bitcoin-s.datadir="/tmp/multi-peer/"
bitcoin-s.network = "mainnet"
bitcoin-s.node.mode = "neutrino"
bitcoin-s.node.peers =["neutrino.suredbits.com:8333"]
bitcoin-s.node.relay=true

bitcoin-s.tor.enabled = false
bitcoin-s.control.enabled = false
```

I'm starting the server with 

> ./bitcoin-s-server --conf /tmp/multi-peer/bitcoin-s.conf 

and then i see things like this in the logs

>2021-09-28T13:25:23UTC INFO [TorAppConfig] Starting Tor daemon
2021-09-28T13:25:23UTC INFO [TorClient$] Using prepackaged Tor from bitcoin-s resources, /tmp/multi-peer/tor/linux_64/tor
2021-09-28T13:25:23UTC INFO [TorClient$] Using tor daemon already written to datadir=/tmp/multi-peer/tor
2021-09-28T13:25:26UTC INFO [TorAppConfig] Tor daemon is fully started, it took=3047ms
2021-09-28T13:25:26UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/tmp/multi-peer/mainnet/nodedb.sqlite (SQLite 3.36)

and here is an image

![Screenshot from 2021-09-28 08-26-41](https://user-images.githubusercontent.com/3514957/135097131-655f0c31-9b55-4e85-823f-871b01902289.png)

**Comment by benthecarman** [comment]
if you have `bitcoin-s.tor.proxy = true` it will still start up tor

**Comment by Christewart** [comment]
Yeah, i think this is the issue

https://github.com/bitcoin-s/bitcoin-s/blob/704b02ae6c0c5628e1628768fcd391f53964c9e3/tor/src/main/scala/org/bitcoins/tor/config/TorAppConfig.scala#L100

Don't we need both tor params defined AND the proxy ? 

I think you are slightly wrong on your configuration though, i think it is `bitcoin-s.proxy.enabled` 

https://github.com/bitcoin-s/bitcoin-s/blob/704b02ae6c0c5628e1628768fcd391f53964c9e3/tor/src/main/scala/org/bitcoins/tor/config/TorAppConfig.scala#L47

**Comment by benthecarman** [comment]
> I think you are slightly wrong on your configuration though, i think it is bitcoin-s.proxy.enabled

oh woops

> Don't we need both tor params defined AND the proxy ?

I think OR is correct here. If either is enabled we will need tor running or else we will get errors
