### ISSUE TITLE
Changing seed under oracleServer does not throw an error

### ISSUE THREAD

**Issue by user411** [bitcoin-s/bitcoin-s#3708]
**Describe the bug**
Changing the .bitcoin-s/seeds/encrypted-bitcoin-s-seed.json for a new one does not throw an error. I am told it should per https://github.com/bitcoin-s/bitcoin-s/pull/3451

**To Reproduce**
mv ~/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json ~/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json.bak
sbt oracleServer/run

**Expected behavior**
Was told this should cause an error on starting oracleServer

**Platform (please complete the following information):**
 - macOS 11.6

**Comment by Christewart** [comment]
I can reproduce this behavior, working on a fix
