### ISSUE TITLE
pre-packaged chaindb.sqlite doesn't seem to work on testnet3

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3730]
From a user on telegram referring to this seciton on the website: 

https://bitcoin-s.org/docs/next/getting-setup#step-6-optional-moving-to-testnet

![Screenshot from 2021-10-06 13-38-25](https://user-images.githubusercontent.com/3514957/136263293-bea79c7c-35a0-4f3e-a558-3055028dd8ae.png)

**Comment by benthecarman** [comment]
This file is old, was made before the chain work migration

**Comment by Christewart** [comment]
Seems like i have the chain work

![Screenshot from 2021-10-07 05-09-48](https://user-images.githubusercontent.com/3514957/136364662-0a76728c-d30f-4945-a172-a74d41dacd71.png)
