### ISSUE TITLE
Schnorr sig implementation diverges from the BIP340 standard

### ISSUE THREAD

**Issue by nkohen** [bitcoin-s/bitcoin-s#3806]
At TabConf I was made aware of [this PR](https://github.com/bitcoin/bitcoin/pull/22934) and the [corresponding issue](https://github.com/bitcoin/bitcoin/issues/22435) with detail and discussion of the missing verification step in secp256k1 schnorr signing (an optional but recommended part of the standard that adds extra protection in certain data corruption edge cases), this should be implemented in bitcoin-s as well.

This shouldn't happen in the actual sign functions as this would lead to two verifications (one being unnecessary) when running secp after the PR is merged, but rather in the bouncy-castle impl (and js if the verification is not begin done) directly.

**Comment by nkohen** [comment]
After looking into this again, it seems that the extra verification step is actually happening inside of bitcoin, not secp, so it will actually be sufficient to add this verification step once to the top-level interface rather than some implementations and not others.

**Comment by nkohen** [comment]
I've decided to add this verification step to normal Schnorr and ECDSA signing but not to adaptor signing as I believe this would incur to high a cost when constructing DLCs, and the spec says "it is recommended, but can be omitted if the computation cost is prohibitive".

**Comment by Christewart** [comment]
Done in #4214
