### ISSUE TITLE
[question] is this a fully working bitcoin client?

### ISSUE THREAD

**Issue by piu130** [bitcoin-s/bitcoin-s#383]
or more a collection of libraries to build one?

**Comment by torkelrogstad** [comment]
This is not currently a fully working Bitcoin client. We are working on it however. We are creating a light client, not a fully verifying node. 

We do have sub projects for interacting with Bitcoin Core and Eclair, though. The `bitcoind-rpc` project is a strongly typed way of interacting with `bitcoind`, and `eclair-rpc` is a strongly typed way of interacting with the Eclair REST API.
