### ISSUE TITLE
`lndRpcTest` hangs on mac 

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3878]
I'm running on 9c9a0a618f09523e0637b701e59a890f4e2cbdff and `lndRpcTest/test` seems to hang

<img width="1432" alt="Screen Shot 2021-12-06 at 5 27 54 PM" src="https://user-images.githubusercontent.com/3514957/144938982-e93e9f97-ae6f-470c-b710-20c3cf56cbf4.png">

it does seem like binaries are started on the underlying OS

<img width="1432" alt="Screen Shot 2021-12-06 at 5 28 37 PM" src="https://user-images.githubusercontent.com/3514957/144939067-41f53819-3dda-4db8-a924-4d58425d74a4.png">

**Comment by benthecarman** [comment]
Weird, it is tested on mac in the CI

**Comment by Christewart** [comment]
> Weird, it is tested on mac in the CI

I'm wondering if it is m1 related

**Comment by benthecarman** [comment]
Maybe need to use the arm64 binaries
