### ISSUE TITLE
Single UTXO wallet spending error / DLC accounting error

### ISSUE THREAD

**Issue by user411** [bitcoin-s/bitcoin-s#3888]
**Describe the bug**
I started with a wallet with a single reserved UTXO. I try to create a new DLC Offer, but cannot until the UTXO gets its first confirm at 38:08. Then I make a 7 digit numeric offer at 39:15 and a enum offer at 49:15 before another block clears. At 51:19 a block is received and there is an error processing it with "requirement failed: If we have spent a spendinginfodb, the spendingTxId must be defined.". Then I try to sign an 18 digit Accept message made earlier and get an "Error fetching accounting" at 55:47.

One thing to note is that the 7 digit numeric DLC stayed stuck in Broadcasted state even after 6 confirmations. I had previously seen DLCs stuck in Broadcasted state on initiator and non-initiator wallets.

Doing a `rescan --force` updated the Broadcasted DLC to Confirmed state, but oddly did not change the Last Updated date on the contract or on the 18 digit DLC in Signed state. All other contracts had their Last Updated date overwritten with current time even though they did not ultimately have their state changed by the rescan.

This was all done on a Neutrino connected wallet. The bitcoin-s implementation running was commit d393848cc204b92edc3c200faab05c1f72bf3e75

**Logs**
Attached
[1 utxo wallet, make 7 digit numeric, then make enum, then receive block.txt](https://github.com/bitcoin-s/bitcoin-s/files/7679005/1.utxo.wallet.make.7.digit.numeric.then.make.enum.then.receive.block.txt)

**Platform (please complete the following information):**
 - Ubuntu Linux x64

**Comment by Christewart** [comment]
Other issues that have this same error are #3182 and #2917

>[info] 2021-12-08T18:51:19UTC INFO [DLCWallet$DLCWalletImpl] Processing block=000000000000000fed6e60a14d420f1e35e3a2fc16c393bb3bf00e54c7a8b73e
[info] 2021-12-08T18:51:19UTC ERROR [DLCWallet$DLCWalletImpl] Error processing of block=000000000000000fed6e60a14d420f1e35e3a2fc16c393bb3bf00e54c7a8b73e.
[info] java.lang.IllegalArgumentException: requirement failed: If we have spent a spendinginfodb, the spendingTxId must be defined. Outpoint=TransactionOutPoint(8f00808ae851a78b1c15d91c8694f6cdb99a95baee759080b49a90b68e15b4a6:1)
[info] 	at scala.Predef$.require(Predef.scala:337)
[info] 	at org.bitcoins.core.api.wallet.db.SpendingInfoDb.$init$(SpendingInfoDb.scala:126)
[info] 	at org.bitcoins.core.api.wallet.db.SegwitV0SpendingInfo.<init>(SpendingInfoDb.scala:33)
[info] 	at org.bitcoins.core.api.wallet.db.SegwitV0SpendingInfo.copy(SpendingInfoDb.scala:32)
[info] 	at org.bitcoins.core.api.wallet.db.SegwitV0SpendingInfo.copyWithState(SpendingInfoDb.scala:41)
[info] 	at org.bitcoins.core.api.wallet.db.SegwitV0SpendingInfo.copyWithState(SpendingInfoDb.scala:24)
[info] 	at org.bitcoins.wallet.internal.TransactionProcessing.processExistingReceivedTxo(TransactionProcessing.scala:471)
[info] 	at org.bitcoins.wallet.internal.TransactionProcessing.$anonfun$processReceivedUtxos$2(TransactionProcessing.scala:281)

**Comment by Christewart** [comment]
> 8f00808ae851a78b1c15d91c8694f6cdb99a95baee759080b49a90b68e15b4a6

One weird thing about the utxo that is allegedly being spent is that it wasn't spent on the test network? The utxo [8f00808ae851a78b1c15d91c8694f6cdb99a95baee759080b49a90b68e15b4a6:1](https://mempool.space/testnet/tx/8f00808ae851a78b1c15d91c8694f6cdb99a95baee759080b49a90b68e15b4a6) is still funded according to mempool.space, so idk how a block could have come in spending this?

**Comment by Christewart** [comment]
Fixed by #3909
