### ISSUE TITLE
Remove the $ sign from doc for installing cli

### ISSUE THREAD

**Issue by LilMonk** [bitcoin-s/bitcoin-s#3901]
There is a **'$'** sign in the doc for installing the cli. ```$ sbt cli/universal:stage``` This **'$'** sign is also getting copied along with the command when you click on the copy command button. 

This is the doc link: https://github.com/bitcoin-s/bitcoin-s/blob/6c67e83d3f209722a78e94b4b9f32e1da0e53479/docs/applications/cli.md?plain=1#L15

**Comment by LilMonk** [comment]
Can I edit the doc? Will just editing that file work?

**Comment by Christewart** [comment]
This the file/line you need to modify. https://github.com/Christewart/bitcoin-s-core/blob/f4d0f369ec423b4fdc7e5eedf07cc4043521f8c7/docs/applications/cli.md#L15

you can open a PR then, once we merge it, the preview site will get updated with the change (https://bitcoin-s.org/docs/next/applications/cli)
