### ISSUE TITLE
`zipdatadir` needs to create target directory on backups

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3958]
reported by @user411 , as a hack for now he is creating the `target` directory himself, but this should really be created by the backend.

Here is the stack trace seen from the front end

```
2022-01-04T15:44:33.503Z error: /downloadBackup backupPath is not accessible
ZipDataDir() /Users/user411/.bitcoin-s/backup2/bitcoin-s-backup.zip
SendServerMessage() error Request failed: /Users/ivan/.bitcoin-s/backup2/bitcoin-s-backup.zip (No such file or directory)
2022-01-04T15:44:33.851Z error: uncaught rejection
```

**Comment by user411** [comment]
The path being used to make backups is ~/.bitcoin-s/backup/ . If /backup does not exist, backup zips cannot be saved.
