### ISSUE TITLE
`estimatefee` endpoint returns a 500 internal server error in some cases

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3972]
This was reported by @user411 when he is running on `umbrel-dev`. 

>I don’t know technically, but on regtest umbrel-dev by default “there’s not enough data for fee estimation” per @rorp 

>You are getting this in response to the estimatefee endpoint right? https://bitcoin-s.org/docs/applications/server#util - @Christewart 

>Yes, I get a 500 from that endpoint in this scenario @user411

Maybe there is some sort of IBD going on with bitcoind and we cannot get fee estimates? :man_shrugging:

**Comment by Christewart** [comment]
Work around on the UI for now: https://github.com/bitcoin-s/bitcoin-s-ts/pull/53

**Comment by benthecarman** [comment]
Yeah bitcoin core needs to see a sufficient amount of txs through its mempool to estimate fees. Maybe give it a backup to one of the web fee providers
