### ISSUE TITLE
Wallet is not showing balance 'The supplied authentication is invalid'

### ISSUE THREAD

**Issue by user411** [bitcoin-s/bitcoin-s#3984]
**Describe the bug**
In my dev environment on Mac running on bitcoin-s master e520b4 I currently cannot see my wallet balance with a server password set or not.

I turned off all proxy and frontend projects to make sure they were not hitting the server with any requests while it starts up and this behavior persists.

I have not done any transactions on the wallet since we added authorization. I have started and stopped it with and without a password many times.

**To Reproduce**
1. I don't know how to reproduce, but you might try setting and unsetting the password on the server and running a number of times. I have been running with `bundle/run`.

**Expected behavior**
That I can see my balances.

**Logs**
[cannotSeeBalances.txt](https://github.com/bitcoin-s/bitcoin-s/files/7873953/cannotSeeBalances.txt)
![Screen Shot 2022-01-14 at 5 45 49 PM](https://user-images.githubusercontent.com/22351459/149602304-845a72c1-6efa-41e5-b5ad-32df8c3be803.png)
```
    server {
        # The port we bind our rpc server on
        rpcport = 9999

        # The ip address we bind our server too
        rpcbind = "127.0.0.1"

        password = "password"

        wsport = 19999
        wsbind = "127.0.0.1"
    }
```

**Platform (please complete the following information):**
 - OS: macOS

**Comment by benthecarman** [comment]
Maybe the bundle doesn't have the password so every rpc cli fails

**Comment by user411** [comment]
It has worked after adding the API auth previously.

**Comment by benthecarman** [comment]
> It has worked after adding the API auth previously.

was the rpc password set?

**Comment by user411** [comment]
It has worked set and not, though there seemed to be occasionally flaky behavior. Right now it does not work set or unset.

**Comment by user411** [comment]
It appears I may have made it to this state in my Docker env as well. The bitcoin-s server no longer responds to `getversion`, which is used for a heartbeat though all the passwords / auth are in alignment.

**Comment by user411** [comment]
started with `bundle/run --data-dir ~/.bitcoin-s-temp` after copying my .confs and testnet3 directory over and I see the same behavior as previously with ‘The supplied authentication is invalid’ in my dev env.

**Comment by Christewart** [comment]
I am running e520b492

I'm able to reproduce the behavior with a password set. The GUI cannot query the backend at all.

I cannot reproduce the behavior you are seeing _without_ a password set. Everything works for me when a password is not set.

**Comment by user411** [comment]
I'm glad you are able to reproduce. My guess is if you played with it some more the non-password case could crop up (just from the "spotty" behavior it seemed like I was getting doing just that), but if we can fix the password case that will move us along and maybe fix what I'm seeing in the other case.

For me, now that it is in this state, when I comment out the password in the conf, I get the same behavior.
