### ISSUE TITLE
DLCs in my database in an `Accepted` state with no associated DLC data.

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4001]
I have a few wallets that have this problem. There is a row in `global_dlc_data` that indicates we have a DLC in an `Accepted` state, but we do not any data in my `offer_dlc_data` or `accept_dlc_data` tables. For a DLC to be in an `Accepted` state, I would expect their at least to be data in the `offer_dlc_data` table, and probably in the `accept_dlc_data` table? 

This is super apparent in one of my testnet3 wallet databases. There was only one DLC done in this wallet before I manged to get into this corrupt state. The event name for this DLC was `Deribit-BTC-24JUL21` so I must have created this a long time ago.

There is the possibility that we have sinced fixed the bugs that lead to this corrupted state. This issue is for the case where we haven't so that we have documented with this issue. 

This database state is blocking me from completing #3992 as when I try to read DLCs out of the database to update contractIds, i cannot find offer or accept messages associated with the DLC. We need the offer message to re-compute `tempContractId` and the accept message to calcululate `contractId`. We have neither.

```
sqlite> select * from global_dlc_data ;
dlc_id|temp_contract_id|contract_id|protocol_version|state|is_initiator|account|change_index|key_index|fee_rate|fund_output_serial_id|funding_outpoint|funding_tx_id|closing_tx_id|aggregate_signature|last_updated|serialization_version
eafc75a2253898d60bc56900d3048aa774ffa49eb9bcfd0fe84d5740ca8c60c5|3c2bd89e62d147278ea00a14ce5b15ef42f77bf27a3135cc31db42d013d19646||0|Accepted|0|m/84'/1'/0'|0|0|0100000000000000|7114b14b9119fe34|||||1630083535311|ALPHA
sqlite> select * from oracle_announcement_data  ;
id|announcement_signature|pub_key|signing_pub_key|event_maturity|event_id|event_descriptor
1|6eef775e7383717b27b6ef72424d628fb0ba8bde2759330c818835083841b1a6674a13dfe38e1690dd9072fcb8ced1be32477cf0a02fd10d5cb3a91871eebdee|15e1fb66db56ba64646760cc773dea8977b8bccb986baeb582d266c7d03c5857|15e1fb66db56ba64646760cc773dea8977b8bccb986baeb582d266c7d03c5857|1627113600|Deribit-BTC-24JUL21|fdd80a1000020006425443555344000000000012
sqlite> select * from offer_dlc_data;
sqlite> select * from accept_dlc_data ;
```
![Screenshot from 2022-01-21 11-08-47](https://user-images.githubusercontent.com/3514957/150569857-9e7e69f8-3d4a-4284-ba2f-74b4e82cc50b.png)

**Comment by Christewart** [comment]
Here is another instance of this I have on my mainnet wallet. The event name is `Coinbase BTCUSD 2021-05-27 2PM Chicago Time` so it does appear to be an older DLC as of the time of this writing, maybe we have fixed this bug :crossed_fingers: 

```
sqlite> select * from global_dlc_data where dlc_id='48c8fe360f09964920232452a315f7c621d9ebb602d19a22c2787ec6a7350958';
dlc_id|temp_contract_id|contract_id|protocol_version|state|is_initiator|account|change_index|key_index|fee_rate|fund_output_serial_id|funding_outpoint|funding_tx_id|closing_tx_id|aggregate_signature|last_updated|serialization_version
48c8fe360f09964920232452a315f7c621d9ebb602d19a22c2787ec6a7350958|3aecb6c6229e8a6a399111f04987613571b86e668653acf2af477c190a7bc2fa||0|Accepted|0|m/84'/0'/0'|0|14|4b00000000000000|214ca1e0dcf295df|||||0|ALPHA
sqlite> select * from offer_dlc_data where dlc_id='48c8fe360f09964920232452a315f7c621d9ebb602d19a22c2787ec6a7350958';
sqlite> select * from accept_dlc_data where dlc_id='48c8fe360f09964920232452a315f7c621d9ebb602d19a22c2787ec6a7350958';
sqlite> select * from dlc_announcements where dlc_id='48c8fe360f09964920232452a315f7c621d9ebb602d19a22c2787ec6a7350958';
dlc_id|announcement_id|index|used
48c8fe360f09964920232452a315f7c621d9ebb602d19a22c2787ec6a7350958|1|0|1
sqlite> select * from oracle_announcement_data  where id=1;
id|announcement_signature|pub_key|signing_pub_key|event_maturity|event_id|event_descriptor
1|c8d2d5c1eb034d2cf0e7fcdf72c8eea514c50ee35df3aefe4d97f5747ea3bf147ac94f7d60b83a63fa5c683d770af81afe6f02a63af2f25e022599e5cbde4a0a|5d1bcfab252c6dd9edd7aea4c5eeeef138f7ff7346061ea40143a9f5ae80baa9|5d1bcfab252c6dd9edd7aea4c5eeeef138f7ff7346061ea40143a9f5ae80baa9|1622160000|Coinbase BTCUSD 2021-05-27 2PM Chicago Time|fdd80a1000020006425443555344000000000011
```

![Screenshot from 2022-01-21 11-21-47](https://user-images.githubusercontent.com/3514957/150571726-69661e6a-ee24-4f8b-834b-e24cc4572fe4.png)

**Comment by benthecarman** [comment]
Maybe something was wrong with canceling DLCs?

**Comment by Christewart** [comment]
I'm going to close this and assume the bug was fixed some where. I have not seen this in a few months.
