### ISSUE TITLE
getversion message needs unprotected on bitcoin-s server

### ISSUE THREAD

**Issue by user411** [bitcoin-s/bitcoin-s#4002]
**Describe the bug**
I moved the frontend About page outside of the authorization so we have a chance to debug based on version number if we need it. I think we want to unprotect that message for the bitcoin-s server.

**To Reproduce**
1. Send a `getversion` message to appServer with a password set and no authorization headers.

**Expected behavior**
`getversion` returns a response regardless of authorization.

**Comment by Christewart** [comment]
I think we decided to go another direction this
