### ISSUE TITLE
Rescan bug occuring on unit tests on CI

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4035]
This occured on the postgres test suite, i'm unsure if it is postgres related or a more general bug. Occurred on 7040114866015a1e4dd04995b817e862ffed724a , but i'm pretty certain this is an old bug.

https://github.com/bitcoin-s/bitcoin-s/runs/5023307378?check_suite_focus=true#step:5:368

![Screenshot from 2022-02-01 09-24-24](https://user-images.githubusercontent.com/3514957/151997288-d24a2f04-28bc-4087-b9f8-602bc683aee2.png)

**Comment by benthecarman** [comment]
This is just due to the false positive rate in block filters
