### ISSUE TITLE
Offerer and Accept payouts not symmetrical when the offerer doesn't fill an outcome `totalCollateral`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4070]
I'm not sure if this is a bug or not, but it is worth discussing.

When doing a DLC with a user today, they intended to create a DLC with `150,000 sats` total in it, and each side of the bet puts up half the collateral `75,000` sats. 

The user forgot he had `150,000 sats` as collateral, and filled out the contract as if there were _only_ `100,000 sats` in total collateral. This is what his contract looked like

![Screenshot from 2022-02-10 11-00-37](https://user-images.githubusercontent.com/3514957/153457997-7ce31115-7104-49ef-96c6-0bc57c602c4d.png)

I was the acceptor of this bet, when i went to accept the offer, this is what it looked like

![Screenshot from 2022-02-10 10-20-03](https://user-images.githubusercontent.com/3514957/153458082-043343d8-61c5-49b9-9a8e-1950460d64d9.png)

I then told the user this looks wrong, and we should make another offer and correct his error. For one, we aren't getting refunded our initial collateral in a `TIE` or `act of god` case. 

My question is, is there anything intelligent we can do to prevent situations like this?

**Comment by user411** [comment]
We could have validation or a warning like on the numeric contracts, but you may not want to prevent the option of building a contract like this.

**Comment by user411** [comment]
A warning message for this case has been merged on bitcoin-s-ts https://github.com/bitcoin-s/bitcoin-s-ts/pull/105
