### ISSUE TITLE
Implement offer mailbox

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4102]
We also currently blindly accept an offer message by the looks of it

https://github.com/bitcoin-s/bitcoin-s/blob/019c9b26442d3ecb1761d3e152b9d79da4bfc9e3/dlc-node/src/main/scala/org/bitcoins/dlc/node/DLCDataHandler.scala#L48

We should remove this functionality and replace it with a "mailbox" concept. We should store offers that our node sees, and then display them on the UI for the user to determine if they want to accept them or not. The user can accept the offer on the UI if they want. We should ideally store the tor address that the node sent the offer from so we can accept it with a button click.

Features needed from the front end: 

- Get mailbox contents 
- websocket event for when a new offer enters the mailbox
- delete mailbox offer

**Comment by user411** [comment]
There is currently no way to do this from the UI if I'm understanding correctly. You explicitly accept an offer in the UI and then Tor negotiation fires up to complete.

This feature makes sense with the UI supporting offer forwarding over Tor, we would not want to auto-accept. I don't know if we would also want to support clawback of offers so a user could "unsend" an errant offer or allow them to broadcast to multiple potential takers and then invalidate the offer once one taker has accepted.

**Comment by Christewart** [comment]
> There is currently no way to do this from the UI if I'm understanding correctly. You explicitly accept an offer in the UI and then Tor negotiation fires up to complete.
:+1: 

> This feature makes sense with the UI supporting offer forwarding over Tor, we would not want to auto-accept. I don't know if we would also want to support clawback of offers so a user could "unsend" an errant offer or allow them to broadcast to multiple potential takers and then invalidate the offer once one taker has accepted.

Yeah, as talked about on the call we should probably look at integrating a "filled" message similar to what an exchange would send you when a trading order is filled. We also probably need a cancel message with the `tempContractId` or `contractId` inside of it.
