### ISSUE TITLE
funding_inputs.out_point database constraint violated after negotiation fails for dlc and we try to create a 2nd offer 

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4145]
Seen on 54e18e6

It seems when a DLC fails to negotiate, and we go to create a 2nd offer, we can get a `funding_inputs.out_point` exception as seen in #3846

![Screenshot from 2022-03-01 09-51-24](https://user-images.githubusercontent.com/3514957/156201810-5896b44e-471b-4177-bb70-5779a68a605d.png)

![Screenshot from 2022-03-01 09-55-50](https://user-images.githubusercontent.com/3514957/156202598-6ef18925-9f61-406a-9c2a-088f55b3ff5d.png)

A stack trace for why the negotiation failed, this should be looked into as a second issue likely: 

```
[info] 2022-03-01T15:35:54UTC INFO [DLCDataHandler] Received LnMessage DLCAcceptTLV
[info] 2022-03-01T15:35:54UTC INFO [DLCWallet$DLCWalletImpl] Verifying 2 CET Signatures
[info] 2022-03-01T15:35:55UTC ERROR [DLCDataHandler] Failed to process lnMessage=LnMessage(DLCAcceptTLV(Sha256DigestImpl(8e8a505bdbfc999a916b3e51e053c3e684748a2b9b8d482cedbb565bd02d37b2),5004 sats,ECPublicKey(03724568c894e0208834acad80bbd6a2cd96af059ba949253f3da89a3f91a159aa),wpkh(f09db6b9ac1c63309c7fce33032e51772db75962),UInt64Impl(1426905864216218808),Vector(FundingInputV0TLV(UInt64Impl(16942658377146260480),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(88d15aa93b9ca25cb15548e18315cbf6440e7b86f5a72f92a62dcc6c8baf7ac8:2),EmptyScriptSignature,UInt32Impl(0))),Vector(TransactionOutput(11566 sats,wpkh(7e27faeae8093d0fff8a1f6aacd84af9e5bc0452))),UInt32Impl(0),IndexedSeq(P2WPKHWitnessV0(List(02f8f996d444e520905fdaed1fc19aded6ba41aa19dfc22ef1e53d1dcbd17e55ea, 304402201d406fdaa6c8e9e38aae83ff81c9d71f283166afdf97e98a1bcc91294d4dd2a20220083a2880eaa66965287d8cc2f9119b1cf0ee24e9b031db9e999ffe21599f046d01)))),UInt32Impl(0),UInt32Impl(4294967293),UInt16Impl(107),None), FundingInputV0TLV(UInt64Impl(13788524009869675315),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(88d15aa93b9ca25cb15548e18315cbf6440e7b86f5a72f92a62dcc6c8baf7ac8:0),EmptyScriptSignature,UInt32Impl(4294967294))),Vector(TransactionOutput(5003 sats,wpkh(8148e8d74c3592ab53635b8b163a8c2de055d592)), TransactionOutput(5004 sats,wpkh(7c08bc38aa5cbabdf284d92bcaa40b5a68a2cd4e))),UInt32Impl(1645574400),IndexedSeq(P2WSHWitnessV0(List(5221027b9a7546cacea3e854fdfd58f11623edd53ebaf0c0ae33ed6e58690d106ab6802103d789351bb299f5b27a6c6f141f009fb598059d07bc532add2c45066e294ee8b852ae, 304402201435ad848b20725f223d5284365b18eb161be504bec064ba43aef05368381ec00220069138a48eca29a9ce6edb0819ac6cef66dd173e6a66ffce8e22ba68c135db2001, 30440220334cb2e24ae926fdcaca369df48aee936c1e3082bebe358ab6011595e5d389e802201b44d62396d750407c138624854ad426d071e30690dec3c793da6c3ec4d5455401, )))),UInt32Impl(0),UInt32Impl(4294967293),UInt16Impl(107),None)),wpkh(771277da6a619dd5f3c673fcc959b8a7da36e930),UInt64Impl(6592266299397277244),org.bitcoins.core.protocol.tlv.CETSignaturesV0TLV@b92e70bd,ECDigitalSignature(3044022061b85a01e855c7a9ed39bc3dc1832efeea76f097e5aeda6212ed7b0e7e88770f0220737a10f41e6d35a98d2b6467285b022e314bb814e374a9098373c3b6885021fb),NoNegotiationFieldsTLV)) 
[info] java.lang.IllegalArgumentException: requirement failed: Funding ScriptSignatureParams did not match offer funding inputs
[info] 	at scala.Predef$.require(Predef.scala:337)
[info] 	at org.bitcoins.core.protocol.dlc.sign.DLCTxSigner.<init>(DLCTxSigner.scala:61)
[info] 	at org.bitcoins.dlc.wallet.internal.DLCDataManagement.$anonfun$signerFromDb$3(DLCDataManagement.scala:504)
[info] 	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
[info] 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
[info] 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
[info] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info] 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
[info] 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
[info] 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
[info] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[info] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[info] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[info] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[info] 2022-03-01T15:44:30UTC INFO [DLCWallet$DLCWalletImpl] Creating DLC Offer
[info] 2022-03-01T15:44:30UTC INFO [DLCWallet$DLCWalletImpl] Attempting to fund a tx for amt=5005 sats with feeRate=1 sats/vbyte
[info] 2022-03-01T15:44:30UTC INFO [DLCWallet$DLCWalletImpl] Reserving utxos=Vector(TransactionOutPoint(e8d34ebda977425a3256d34b300407f53e7560679a4e62cf3901ea43accb8b77:1), TransactionOutPoint(908efd0c9f08cd07ac18ba73cd99897c59bfa370f69ba4fec86b667572678251:1))
[info] 2022-03-01T15:44:30UTC INFO [DLCWallet$DLCWalletImpl] Generated new address=tb1qj7xfnm3cmqk3m2lvc4uxexv8346lwzcyhn5nwd isChange=true
[info] 2022-03-01T15:44:31UTC INFO [DLCWallet$DLCWalletImpl] Spending UTXOs: Vector(TransactionOutPoint(e8d34ebda977425a3256d34b300407f53e7560679a4e62cf3901ea43accb8b77:1) state=ConfirmedReceived, TransactionOutPoint(908efd0c9f08cd07ac18ba73cd99897c59bfa370f69ba4fec86b667572678251:1) state=ConfirmedReceived)
[info] 2022-03-01T15:44:31UTC INFO [DLCWallet$DLCWalletImpl] UTXO 0 details: TransactionOutput(6388 sats,wpkh(949703e0a1982bf4062f907e78f909488a4d7942))
[info] 2022-03-01T15:44:31UTC INFO [DLCWallet$DLCWalletImpl] UTXO 1 details: TransactionOutput(5004 sats,wpkh(7c08bc38aa5cbabdf284d92bcaa40b5a68a2cd4e))
[info] 2022-03-01T15:44:31UTC INFO [DLCWallet$DLCWalletImpl] Created offer with tempContractId 4c3600e9e7411b9de823cb8a38181ed7a3b7d5c062ed941a37cd5d3061c151f2
[info] 2022-03-01T15:44:31UTC ERROR [SafeDatabase] Error when executing query flatMap slick.dbio.DBIOAction$$Lambda$1736/0x0000000800b3d040@4471753d
[info] 2022-03-01T15:44:31UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: funding_inputs.out_point)
[info] 2022-03-01T15:44:31UTC INFO [Server] Unhandled error in server:
[info] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: funding_inputs.out_point)
[info] 	at org.sqlite.core.DB.newSQLException(DB.java:1030)
[info] 	at org.sqlite.core.DB.newSQLException(DB.java:1042)
[info] 	at org.sqlite.core.DB.throwex(DB.java:1007)
[info] 	at org.sqlite.core.DB.executeBatch(DB.java:832)
[info] 	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
[info] 	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
[info] 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
[info] 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
[info] 	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
[info] 	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
[info] 	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
[info] 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
[info] 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
[info] 	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
[info] 	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
[info] 	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
[info] 	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
[info] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info] 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Yuxanju** [comment]
You have to make sure your wallet is synchronize and then debug with bech13

**Comment by Christewart** [comment]
I'm seeing this today on  5113cac6c2f75129b5985e85e69facbcef038421 

```
2022-03-03T19:13:22UTC INFO [BitcoinSServerMain] Done start BitcoinSServerMain, it took=9932ms
2022-03-03T19:13:22UTC INFO [DataMessageHandler] Received headers message with 0 headers
2022-03-03T19:13:26UTC INFO [DLCClient] connecting to SOCKS5 proxy localhost/127.0.0.1:1644
2022-03-03T19:13:26UTC INFO [DLCClient] connected to SOCKS5 proxy localhost/127.0.0.1:1644
2022-03-03T19:13:26UTC INFO [DLCClient] connecting to 4z6nao57xrqgli7cuztqqnmtrmyvgzq7gnlga2pghu63vvoml5jk3uid.onion/<unresolved>:2862 via SOCKS5 localhost/127.0.0.1:1644
2022-03-03T19:13:31UTC INFO [DLCClient] connected to 4z6nao57xrqgli7cuztqqnmtrmyvgzq7gnlga2pghu63vvoml5jk3uid.onion/<unresolved>:2862 via SOCKS5 proxy localhost/127.0.0.1:1644
2022-03-03T19:13:31UTC INFO [DLCWallet$DLCWalletImpl] Creating DLC Accept for tempContractId 2396dbfafffc00af71e07dbf62ab036dbfdbc92b6bf095f4a18336aebf8dbb64
2022-03-03T19:13:31UTC INFO [DLCWallet$DLCWalletImpl] Initializing DLC from received offer with tempContractId 2396dbfafffc00af71e07dbf62ab036dbfdbc92b6bf095f4a18336aebf8dbb64
2022-03-03T19:13:31UTC INFO [DLCWallet$DLCWalletImpl] Attempting to fund a tx for amt=50000 sats with feeRate=1 sats/vbyte
2022-03-03T19:13:31UTC INFO [DLCWallet$DLCWalletImpl] Reserving utxos=Vector(TransactionOutPoint(c4698bf9afad0714f3cd8704a154985e3193cbfcc8cdaf754a806cacabed7fd8:1), TransactionOutPoint(9974b0465681e3f77a02da23e8ef0a2b0703faf5ca248e5389b9d85afd41ff1f:0), TransactionOutPoint(a6c234254db35502465f6119ad033f7e1965ab8fcf253a0fc7b15df5b5c3862d:1))
2022-03-03T19:13:31UTC INFO [DLCWallet$DLCWalletImpl] Generated new address=bc1qaemxjseh03hj7qst9t8srac9e8g3qszwcjdudd isChange=true
2022-03-03T19:13:32UTC INFO [DLCWallet$DLCWalletImpl] Spending UTXOs: Vector(TransactionOutPoint(c4698bf9afad0714f3cd8704a154985e3193cbfcc8cdaf754a806cacabed7fd8:1) state=ConfirmedReceived, TransactionOutPoint(9974b0465681e3f77a02da23e8ef0a2b0703faf5ca248e5389b9d85afd41ff1f:0) state=ConfirmedReceived, TransactionOutPoint(a6c234254db35502465f6119ad033f7e1965ab8fcf253a0fc7b15df5b5c3862d:1) state=ConfirmedReceived)
2022-03-03T19:13:32UTC INFO [DLCWallet$DLCWalletImpl] UTXO 0 details: TransactionOutput(1179 sats,wpkh(52584eb56f12d421e5efc49ecddc5eb873958cc0))
2022-03-03T19:13:32UTC INFO [DLCWallet$DLCWalletImpl] UTXO 1 details: TransactionOutput(36435 sats,wpkh(b70b54c77a527367690435f0539728b06b548e0a))
2022-03-03T19:13:32UTC INFO [DLCWallet$DLCWalletImpl] UTXO 2 details: TransactionOutput(30000 sats,wpkh(d2800b88aa1a03312c5983f4fe2f7ba487fb4ec1))
2022-03-03T19:13:32UTC INFO [DLCWallet$DLCWalletImpl] Creating CET Sigs for e936d0371342dcc38716efc8547dd7a55a1f424861a32c5f44d249b3c66fbd3d
2022-03-03T19:13:32UTC ERROR [SafeDatabase] Error when executing query flatMap slick.dbio.DBIOAction$$Lambda$1204/0x0000000801169288@2df7f32b
2022-03-03T19:13:32UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: funding_inputs.out_point)
2022-03-03T19:13:32UTC INFO [Server] Unhandled error in server:
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: funding_inputs.out_point)
	at org.sqlite.core.DB.newSQLException(DB.java:1030)
	at org.sqlite.core.DB.newSQLException(DB.java:1042)
	at org.sqlite.core.DB.throwex(DB.java:1007)
	at org.sqlite.core.DB.executeBatch(DB.java:832)
	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... //a bunch of None.get errors below here due to polling from the frontend ....
```

**Comment by Christewart** [comment]
The outpoints that my wallet is attempting to reserve are fully spent. It seems all of them were spent in between 

>2022-03-03T19:13:31UTC INFO [DLCWallet$DLCWalletImpl] Reserving utxos=Vector(TransactionOutPoint(c4698bf9afad0714f3cd8704a154985e3193cbfcc8cdaf754a806cacabed7fd8:1), TransactionOutPoint(9974b0465681e3f77a02da23e8ef0a2b0703faf5ca248e5389b9d85afd41ff1f:0), TransactionOutPoint(a6c234254db35502465f6119ad033f7e1965ab8fcf253a0fc7b15df5b5c3862d:1))

These utxos were spent on
- `2021-11-19 13:16`
- `2021-12-13 09:07`
- `2021-08-11 16:45`

So it seems like my wallet got corrupted somehow with bad utxos.

**Comment by Yuxanju** [comment]
Sorry to hear that.
You will need to synchronize your wallet and then you debug it ..your
wallet might be corrupted..

**Comment by Christewart** [comment]
> I'm seeing this today on [5113cac](https://github.com/bitcoin-s/bitcoin-s/commit/5113cac6c2f75129b5985e85e69facbcef038421)
> 
> ```
> 2022-03-03T19:13:22UTC INFO [BitcoinSServerMain] Done start BitcoinSServerMain, it took=9932ms
> 2022-03-03T19:13:22UTC INFO [DataMessageHandler] Received headers message with 0 headers
> 2022-03-03T19:13:26UTC INFO [DLCClient] connecting to SOCKS5 proxy localhost/127.0.0.1:1644
> 2022-03-03T19:13:26UTC INFO [DLCClient] connected to SOCKS5 proxy localhost/127.0.0.1:1644
> 2022-03-03T19:13:26UTC INFO [DLCClient] connecting to 4z6nao57xrqgli7cuztqqnmtrmyvgzq7gnlga2pghu63vvoml5jk3uid.onion/<unresolved>:2862 via SOCKS5 localhost/127.0.0.1:1644
> 2022-03-03T19:13:31UTC INFO [DLCClient] connected to 4z6nao57xrqgli7cuztqqnmtrmyvgzq7gnlga2pghu63vvoml5jk3uid.onion/<unresolved>:2862 via SOCKS5 proxy localhost/127.0.0.1:1644
> 2022-03-03T19:13:31UTC INFO [DLCWallet$DLCWalletImpl] Creating DLC Accept for tempContractId 2396dbfafffc00af71e07dbf62ab036dbfdbc92b6bf095f4a18336aebf8dbb64
> 2022-03-03T19:13:31UTC INFO [DLCWallet$DLCWalletImpl] Initializing DLC from received offer with tempContractId 2396dbfafffc00af71e07dbf62ab036dbfdbc92b6bf095f4a18336aebf8dbb64
> 2022-03-03T19:13:31UTC INFO [DLCWallet$DLCWalletImpl] Attempting to fund a tx for amt=50000 sats with feeRate=1 sats/vbyte
> 2022-03-03T19:13:31UTC INFO [DLCWallet$DLCWalletImpl] Reserving utxos=Vector(TransactionOutPoint(c4698bf9afad0714f3cd8704a154985e3193cbfcc8cdaf754a806cacabed7fd8:1), TransactionOutPoint(9974b0465681e3f77a02da23e8ef0a2b0703faf5ca248e5389b9d85afd41ff1f:0), TransactionOutPoint(a6c234254db35502465f6119ad033f7e1965ab8fcf253a0fc7b15df5b5c3862d:1))
> 2022-03-03T19:13:31UTC INFO [DLCWallet$DLCWalletImpl] Generated new address=bc1qaemxjseh03hj7qst9t8srac9e8g3qszwcjdudd isChange=true
> 2022-03-03T19:13:32UTC INFO [DLCWallet$DLCWalletImpl] Spending UTXOs: Vector(TransactionOutPoint(c4698bf9afad0714f3cd8704a154985e3193cbfcc8cdaf754a806cacabed7fd8:1) state=ConfirmedReceived, TransactionOutPoint(9974b0465681e3f77a02da23e8ef0a2b0703faf5ca248e5389b9d85afd41ff1f:0) state=ConfirmedReceived, TransactionOutPoint(a6c234254db35502465f6119ad033f7e1965ab8fcf253a0fc7b15df5b5c3862d:1) state=ConfirmedReceived)
> 2022-03-03T19:13:32UTC INFO [DLCWallet$DLCWalletImpl] UTXO 0 details: TransactionOutput(1179 sats,wpkh(52584eb56f12d421e5efc49ecddc5eb873958cc0))
> 2022-03-03T19:13:32UTC INFO [DLCWallet$DLCWalletImpl] UTXO 1 details: TransactionOutput(36435 sats,wpkh(b70b54c77a527367690435f0539728b06b548e0a))
> 2022-03-03T19:13:32UTC INFO [DLCWallet$DLCWalletImpl] UTXO 2 details: TransactionOutput(30000 sats,wpkh(d2800b88aa1a03312c5983f4fe2f7ba487fb4ec1))
> 2022-03-03T19:13:32UTC INFO [DLCWallet$DLCWalletImpl] Creating CET Sigs for e936d0371342dcc38716efc8547dd7a55a1f424861a32c5f44d249b3c66fbd3d
> 2022-03-03T19:13:32UTC ERROR [SafeDatabase] Error when executing query flatMap slick.dbio.DBIOAction$$Lambda$1204/0x0000000801169288@2df7f32b
> 2022-03-03T19:13:32UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: funding_inputs.out_point)
> 2022-03-03T19:13:32UTC INFO [Server] Unhandled error in server:
> org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: funding_inputs.out_point)
> 	at org.sqlite.core.DB.newSQLException(DB.java:1030)
> 	at org.sqlite.core.DB.newSQLException(DB.java:1042)
> 	at org.sqlite.core.DB.throwex(DB.java:1007)
> 	at org.sqlite.core.DB.executeBatch(DB.java:832)
> 	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
> 	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
> 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
> 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
> 	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
> 	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
> 	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
> 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
> 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
> 	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
> 	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
> 	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
> 	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> ... //a bunch of None.get errors below here due to polling from the frontend ....
> ```

In my case this is because we transition to state `AcceptComputingAdaptorSigs` without updating the contractId in the database. This leads to the exception in `DLCStatusBuilder$.buildInProgressDLCStatus`

![Screenshot from 2022-03-04 11-04-27](https://user-images.githubusercontent.com/3514957/156807994-9cbf9a18-2fc9-469b-969b-ab5f50415a66.png)

**Comment by Yuxanju** [comment]
You we I’ll have to synchronize your wallet and then you debug

**Comment by Christewart** [comment]
Now that i think about this a bit more, I think this might be happening

1. Alice sends Bob an `offer1`
2. Bob sends Alice an `accept1`
3. Alice decides to not continue building the DLC for whatever reason (internal wallet error, bad terms etc)
4. Alice sends `offer2`
5. Bob sends `accept2` to Alice. This `accept2` uses the same utxos used to fund `accept1`.

This should cause this error message.

I suspect it is ocuring here: https://github.com/bitcoin-s/bitcoin-s/blob/a747f84bbb4f051b82df62b5cf3dd62ed751ec87/dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala#L918
