### ISSUE TITLE
Remove `Spv` code. 

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4215]
I don't think this is necessary anymore and just adds dead weight to the codebase. I dont believe bitcoin core even recommends spv anymore.

**Comment by solo1g** [comment]
You can leave this to me. My PR #4155 had everything done only for neutrino node anyway (SPV and its failed tests were a todo after review) so I would gladly remove it all now :wink:.

**Comment by Christewart** [comment]
that would be great
