### ISSUE TITLE
Blockchain builder

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#428]
The current [`Blockchain`](https://github.com/bitcoin-s/bitcoin-s-core/blob/node/chain/src/main/scala/org/bitcoins/chain/blockchain/Blockchain.scala#L22) implementation is extremely bare bones. We should expand this to conform to normal builder apis in Scala like 

```scala

val builder = Blockchain.newBuilder

builder.+=(header1)
builder.+=(header2)
.
.
.
builder.result()
```

There is a question where validation should occur, it can happen either on `+=()` or `.result()`. What i mean by this is where show we indicate that you building a blockchain that is not valid (for instance, a bad previous block hash).

**Comment by torkelrogstad** [comment]
An alternative to the collections-like builder is to  make the blockchain builder and ADT that includes both the error and success case, and then add `map`/`flatMap` to the ADT, making it possible to use it in a for expression.

If we're doing the builder way, I'm thinking it makes sense for `result` to return an ADT. Easier to handle the error in just one place, IMO
