### ISSUE TITLE
lnd test suite consistently timing out on mac

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4360]
This seems to happen 50% of the time, no idea why though. Any ideas @benthecarman ?

https://github.com/bitcoin-s/bitcoin-s/runs/6689180395?check_suite_focus=true#step:5:767

![Screenshot from 2022-06-01 08-36-19](https://user-images.githubusercontent.com/3514957/171417549-94634971-bbed-49d4-a5d1-66553f6e4cbd.png)

**Comment by benthecarman** [comment]
Looks like either lnd is taking a while to start up or it is deleting the data dir too early. Will look into it
