### ISSUE TITLE
Nested configurations seems to lead to invalid network in `bitcoin-s.conf`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4716]
I've attached images of the bitcoin-s.conf . This occurred on the 1.9.3 release of bitcoin-s

![Screenshot from 2022-09-06 12-44-08](https://user-images.githubusercontent.com/3514957/188703910-48db281d-2950-4b17-a9af-c7f53fc91758.png)
 

![Screenshot from 2022-09-06 12-44-19](https://user-images.githubusercontent.com/3514957/188703908-75b90de4-8a5c-4aef-a868-975f3dcab2ce.png)

**Comment by benthecarman** [comment]
I think this is because  the `"testnet3"` has the wrong kind of `"` around it and it is including the quotes so it fails the match.

You can see your IDE is highlighting the other strings in green

**Comment by Christewart** [comment]
> I think this is because the `"testnet3"` has the wrong kind of `"` around it and it is including the quotes so it fails the match.
> 
> You can see your IDE is highlighting the other strings in green

Wow, nice catch

**Comment by CypherPoet** [comment]
@Christewart @benthecarman Changing the quote formatting did, indeed, solve this 👍
