### ISSUE TITLE
`1.9.3` did not publish all jars to sonatype

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4725]
It appears we ran into a bug

https://github.com/bitcoin-s/bitcoin-s/runs/8228079009?check_suite_focus=true#step:5:3625

possibly related to: https://github.com/sbt/sbt-ci-release/issues/87

**Comment by benthecarman** [comment]
I think it's because the release is marked as pre release

**Comment by Christewart** [comment]
> I think it's because the release is marked as pre release

I don't think this makes sense. Why it would be publish at but 3 jars if that was the case?

For instance, we have a 1.9.3 for `bitcoin-s-server`

https://repo1.maven.org/maven2/org/bitcoin-s/bitcoin-s-server_2.13/

but we do not have a 1.9.3 for `bitcoin-s-testkit-core`

https://repo1.maven.org/maven2/org/bitcoin-s/bitcoin-s-testkit-core_2.13/

![Screenshot from 2022-09-07 12-22-26](https://user-images.githubusercontent.com/3514957/188940717-5a91c9a2-81c3-47b8-a93e-62310f8127dc.png)
![Screenshot from 2022-09-07 12-21-48](https://user-images.githubusercontent.com/3514957/188940720-d1085a53-566b-4e71-93db-692cc8b37335.png)

**Comment by Christewart** [comment]
fixed in 1.9.4
