### ISSUE TITLE
featuring Bitcoin-Scala in Docusaurus

### ISSUE THREAD

**Issue by nickbui729** [bitcoin-s/bitcoin-s#477]
Hello, we would like to feature your project to the Docusaurus [users](https://docusaurus.io/en/users) 

This has the benefits of giving projects recognition and also lets the community and new users reference the creative ways of using Docusaurus!

If you are okay with it, are you able to provide a logo we can use? Additional information can be found [here](https://github.com/facebook/Docusaurus/issues/1437)

**Comment by torkelrogstad** [comment]
We just published the Docusaurus website at https://bitcoin-s.org. 

You can use this logo: https://github.com/bitcoin-s/bitcoin-s/blob/master/website/static/img/bitcoin-s-logo.svg. If it's more preferable to have a logo with a dark background I can provide that as well

**Comment by torkelrogstad** [comment]
Closing this, made a PR to the Docusaurus repo: https://github.com/facebook/docusaurus/pull/1635
