### ISSUE TITLE
Payments not transitioning from unconfirmed -> confirmed

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4815]
The user reported this on 42ef5d15b6569208f4aa6502a262188d11e1df45 (1.9.3)

![Screenshot from 2022-10-04 10-38-24](https://user-images.githubusercontent.com/3514957/193863792-9a5c7a46-a222-42cf-bd9c-082f851d5574.png)

**Comment by houghvanwyk** [comment]
Some additional info. This only appears to be a problem when I have node.relay = true set in my bitcoin-s.conf file. If I run it with false and only receive transactions with at least one confirmation, it seems to behave as expected.
