### ISSUE TITLE
Bump `bitcoind` minor releases

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4932]
- https://bitcoincore.org/en/2022/12/21/release-23.1/
- https://bitcoincore.org/en/2022/12/12/release-24.0.1/
- https://bitcoincore.org/en/2022/12/15/release-22.1/

**Comment by Burnleydev1** [comment]
Hello @Christewart, Please I would like to ask if this has been taken, if not then I would like to ask if I can take it.

**Comment by Christewart** [comment]
> Hello @Christewart, Please I would like to ask if this has been taken, if not then I would like to ask if I can take it.

this has not been taken by anyone

**Comment by Burnleydev1** [comment]
Please i wish to ask for the steps to take to fix this issue

**Comment by fanquake** [comment]
Not sure I can properly implement / test this, but would be great to see this happen.
Note that the current minor release versions are:
* 23.2: https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-23.2.md
* 24.1: https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-24.1.md

**Comment by Christewart** [comment]
> Not sure I can properly implement / test this, but would be great to see this happen. Note that the current minor release versions are:
> 
>     * 23.2: https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-23.2.md
> 
>     * 24.1: https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-24.1.md

Opened #5088 . We have a `testkit` project that we use extensively to test our `wallet`, `node`, `chain` modules against on every CI run. If everything ✔️ I doubt there is any regressions hidden somewhere in these minor releases. Is there any regressions you are concerned about in particular?
