### ISSUE TITLE
CI: The http server closed the connection unexpectedly before delivering responses for 1 outstanding requests

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#531]
https://travis-ci.org/bitcoin-s/bitcoin-s/jobs/546758099#L640

This seems to be a re-occurring theme on our CI that is causing spurious failures. Investigate what root cause is and fix it

**Comment by Christewart** [comment]
This is reproducible locally and seems to be an actual akka http bug: https://github.com/akka/akka-http/issues/1459

https://github.com/akka/akka-http/issues/768

**Comment by xubofei1983** [comment]
We start seeing this error recently, after some infrastructure changes (bump kubernetes version 1.11->1.14, and introduce Istio). I tried to recover with "Http().shutdownAllConnectionPools()", but problem still persists.  Only restart works.

Not sure what is the root cause.

**Comment by Christewart** [comment]
@xubofei1983 It seems we haven't seen this as of late, but we have had other issues on our CI.

**Comment by Christewart** [comment]
Closing this as we will track this on #2701 now
