### ISSUE TITLE
Make RPC `sendToAddress` take `CurrencyUnit`

### ISSUE THREAD

**Issue by torkelrogstad** [bitcoin-s/bitcoin-s#539]
Current method definition: https://bitcoin-s.org/api/org/bitcoins/rpc/client/common/BitcoindRpcClient.html#sendToAddress(address:org.bitcoins.core.protocol.BitcoinAddress,amount:org.bitcoins.core.currency.Bitcoins,localComment:String,toComment:String,subractFeeFromAmount:Boolean):scala.concurrent.Future[org.bitcoins.core.crypto.DoubleSha256DigestBE]

Would be more ergonomic if the signature looked like this instead: 

```scala
 sendToAddress(address: BitcoinAddress, amount: CurrencyUnit, localComment: String = "", toComment: String = "", subractFeeFromAmount: Boolean = false): Future[DoubleSha256DigestBE] 
```

**Comment by cwaldron97** [comment]
Currently looks like we implement it like this 
```
def sendToAddress(
      address: BitcoinAddress,
      amount: CurrencyUnit,
      feeRate: FeeUnit,
      fromAccount: AccountDb): Future[Transaction]
```
does that mean CurrencyUnit was already taken care of and we just need to add the comments?

**Comment by torkelrogstad** [comment]
You're looking at the [`sendToAddress`](https://github.com/bitcoin-s/bitcoin-s/blob/9101aece9b9e48df741e668fce66edbf02f59afc/wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala#L38) method in our wallet (`Wallet.scala`/`WalletApi.scala`), but I'm talking atbout [`sendToAddress`](https://github.com/bitcoin-s/bitcoin-s/blob/4dbb57467ce3b469268b7ddb9faecfc736a87d08/bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/TransactionRpc.scala#L149) in our RPC client.
