### ISSUE TITLE
Create a type for PSBTs

### ISSUE THREAD

**Issue by cwaldron97** [bitcoin-s/bitcoin-s#551]
Currently `PSBT`s are just handled as a `String` want to make sure they are base64
Effects `V17PsbtRpc.scala` and `V18RsbtRpc.scala`

**Comment by torkelrogstad** [comment]
To properly address this issue we would also have to implement proper parsing of PSBTs. I have an initial attempt at this (although it is pretty old by now): https://github.com/torkelrogstad/bitcoin-s/tree/2019-03-02-initial-psbt. See the two latest commits
