### ISSUE TITLE
Starting a bitcoin node cannot find path on Windows 

### ISSUE THREAD

**Issue by cwaldron97** [bitcoin-s/bitcoin-s#562]
When running `bloop run node` discovered that the `Bitcoindconfig` in `bitcoind-rpc` tries to find `.bitcoin` in the `C:\users\{current_user}\.bitcoin` folder by default. I'll write a default case for Windows users.

```
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: C:\Users\rocky\.bitcoin does not exist!  
```

**Comment by torkelrogstad** [comment]
The offending `val` is here: https://github.com/bitcoin-s/bitcoin-s/blob/24016b6e22711dd66415ab0ceb32f3af8bbdbab9/bitcoind-rpc/src/main/scala/org/bitcoins/rpc/config/BitcoindConfig.scala#L325-L338
