### ISSUE TITLE
Remove cli and walletServer from testKit's dependecy list.

### ISSUE THREAD

**Issue by rorp** [bitcoin-s/bitcoin-s#619]
Current build configuration prevents` bitcon-s-testkit` being used in thrid-party applications, because it depends on `cli `and `walletServer` subpojects, but publishing for both subpojects is disabled.

It's a conceptual issue: a library should not depend on its apps.

**Comment by Christewart** [comment]
So it does seem that the wallet server needs testkit, but the cli does not. I removed the cli dependency in #625
