### ISSUE TITLE
Bloom filter test case failure

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#644]
**Describe the bug**

It appears that a test case is _meant_ to insert a public key into the bloom filter, but we are asserting that it _isn't_ contained, which is confusing. I was thinking this test case could be related to a false positive, but it is best to investigate. This occurred on PR #637 

https://travis-ci.org/bitcoin-s/bitcoin-s/jobs/560165268#L2060

**Comment by torkelrogstad** [comment]
This is just a false positive, no? This will happen every 1000 runs or so, as the falsePositiveRate is 0.001. IMO the best solution is to just remove the last two lines
