### ISSUE TITLE
SNAPSHOT not fetchable by `deps.edn`

### ISSUE THREAD

**Issue by ysangkok** [bitcoin-s/bitcoin-s#661]
**Describe the bug**
https://bitcoin-s.org/docs/getting-started details nightly version strings that are not usable. For example, the version string is listed as `0.1.0+45-91633375+20190620-1322-SNAPSHOT`. But on Sonatype, the version is https://oss.sonatype.org/content/repositories/snapshots/org/bitcoin-s/bitcoin-s-secp256k1jni/0.1.0+45-91633375-SNAPSHOT/bitcoin-s-secp256k1jni-0.1.0+45-91633375-SNAPSHOT.pom which doesn't contain the date, so what is the value of the date in the snapshot version, if it is not in the sonatype URL, is it really part of the version? Also, this SNAPSHOT is newer than 0.1.0, so shouldn't it be `0.1.1-SNAPSHOT`?

Here is the `deps.edn` that I am trying:
```
{
 :deps
   {
    org.bitcoin-s/bitcoin-s-secp256k1jni {:mvn/version "0.1.0+45-91633375-SNAPSHOT"}
    org.bitcoin-s/bitcoin-s-core {:mvn/version "0.1.0+45-91633375-SNAPSHOT"}
    org.bitcoin-s/bitcoin-s-bitcoind-rpc {:mvn/version "0.1.0+45-91633375-SNAPSHOT"}
    org.bitcoin-s/bitcoin-s-eclair-rpc {:mvn/version "0.1.0+45-91633375-SNAPSHOT"}
    org.bitcoin-s/bitcoin-s-testkit {:mvn/version "0.1.0+45-91633375-SNAPSHOT"}
    org.bitcoin-s/bitcoin-s-zmq {:mvn/version "0.1.0+45-91633375-SNAPSHOT"}
   }
 :mvn/repos {"sonatype" {:url "https://oss.sonatype.org/content/repositories/snapshots/"}}
}
```

**Expected behavior**

I expected the version in the documentation to be usable in `deps.edn`, the native clojure package manager, which it is not.

**Comment by torkelrogstad** [comment]
Thanks for reporting this. You're absolutely right, our listed nightly version is completely wrong. I tried looking into it this morning, but didn't spot the reason. I'll continue to look into this a bit later, and get back to you.

If you don't need the very latest features, I highly recommend using the 0.1.0 release.

**Comment by ysangkok** [comment]
Closing since I don't know whether this is still a bug.
