### ISSUE TITLE
Instructions for building a JAR file

### ISSUE THREAD

**Issue by ysangkok** [bitcoin-s/bitcoin-s#662]
I tried building a JAR by using `sbt package`, but if I run `unzip -l` on the resulting file, it only contains the manifest, and no class files.

Reading the documentation, I notice that there are instructions for including bitcoin-s as a sbt dependency, but not on how to simply just build a JAR file.

**Comment by ysangkok** [comment]
Seems like `sbt publishLocal` makes a usable JAR file...

**Comment by torkelrogstad** [comment]
Thanks for reporting! Did `sbt publishLocal` fix this issue?

**Comment by ysangkok** [comment]
Well, publishLocal doesn't install secp256k1jni with the native libs (only java class files and manifest) , so I had to mix and match Jars from publishLocal and package. Ideally, no incomplete Jar files should ever be produced. It would be preferable if both methods worked.

**Comment by Christewart** [comment]
I seem to have secp256k1jni in my local ivy repo 

Hmm.. that doesn't seem good. I never noticed that before. If that were the case wouldn't we not be publishing. i also have secp256k1jni in my `~/.ivy2/local`

```
ls ~/.ivy2/local/org.bitcoin-s/bitcoin-s-secp256k1jni/
0.1.0+188-465237d3+20190715-0735-SNAPSHOT  0.1.0+205-970a9a21+20190716-1056-SNAPSHOT
0.1.0+191-0c697243+20190716-0805-SNAPSHOT  0.1.0+205-970a9a21+20190716-1117-SNAPSHOT
0.1.0+198-85659168+20190716-0833-SNAPSHOT  0.1.0+205-970a9a21+20190716-1123-SNAPSHOT
0.1.0+205-970a9a21+20190716-1026-SNAPSHOT  0.1.0+205-970a9a21+20190716-1124-SNAPSHOT
0.1.0+205-970a9a21+20190716-1050-SNAPSHOT  0.1.0+206-3b56c41f+20190716-1446-SNAPSHOT
0.1.0+205-970a9a21+20190716-1055-SNAPSHOT
```

Although admittedly I'm not sure if I understand what is going on here, I'll investigate further later

**Comment by ysangkok** [comment]
Ah, you're right, I was wrong, `sbt publishLocal` in the root directory does write secp256k1jni with native libs. The incomplete one is writtten if you do `sbt publishLocal` in the secp256k1jni subdirectory.
