### ISSUE TITLE
Remove support for bitcoind v16

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#674]
When #550 is merged, we should go through and remove support for bitcoind v16

**Comment by nkohen** [comment]
I think that if there is any version that is not vulnerable (e.g. v0.16.3) then we shouldn't remove support and should instead allow users to specify which versions/binaries are installed on their computer so that only relevant tests run.

**Comment by Christewart** [comment]
Done in #4634
