### ISSUE TITLE
Make a distinction between logging when running standalone binaries vs. using modules as libraries

### ISSUE THREAD

**Issue by torkelrogstad** [bitcoin-s/bitcoin-s#699]
There's two ways of using Bitcoin-S: by running compiled binaries or including specific modules as libraries. Logging should be handled differently in these cases. 

When running as a binary: 
We should log to the users data directory, following our own logging convention/structure. 

When running as a library: 
We should not provide any logging configuration, and leave that to the user through their preferred way of configuring Logback. 

One way of handling this would be to default to "library"-logging, and then somehow flip a switch in main methods of the binaries.

**Comment by benthecarman** [comment]
Closed by #1398
