### ISSUE TITLE
Website not deploying on travis CI

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#816]
https://travis-ci.org/bitcoin-s/bitcoin-s/requests

If you look at `gh-pages` task it seems we are failing for some reason

https://travis-ci.org/bitcoin-s/bitcoin-s/requests

I'm unsure of what the root cause of this is at this time

**Comment by benthecarman** [comment]
It looks like it is because there is no `.travis.yml` file in the commit `8c8283a` that it is trying to deploy
