### ISSUE TITLE
Implement `fundRawTransaction()` on bitcoin-s wallet 

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#896]
Basically select utxos in the bitcoin-s wallet and use them to fund a transactions. Similar to how bitcoin core's [`fundrawtransaction`](https://bitcoin.org/en/developer-reference#fundrawtransaction)

This was found to be needed on  https://github.com/bitcoin-s/bitcoin-s/pull/886#discussion_r350495908

The description of `fundrawtransaction` from the bitcoin developer reference: 

```
The fundrawtransaction RPC add inputs to a transaction until it has enough in value to meet its out value.

This will not modify existing inputs, and will add at most one change output to the outputs.
```

**Comment by benthecarman** [comment]
Don't think this is possible with our neutrino wallet, we will can't know the input values without having access to their previous outputs, we would need the block they are included in (or at least the previous txs).
