### ISSUE TITLE
HDGenerators.hardBip32Child generator is incorrect

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#969]
https://github.com/bitcoin-s/bitcoin-s/blob/d78bcaaae3733b222badc243f5d4f51d8c70cc6d/testkit/src/main/scala/org/bitcoins/testkit/core/gen/HDGenerators.scala#L28

As you can see, we just copy `softBip32Child()` and change the flag to hardened. If I am reading BIP32 correctly, [the index needs to be `>= 0x80000000`](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) 

It's probably worth making soft vs hard bip32 children into an ADT

**Comment by benthecarman** [comment]
https://github.com/bitcoin-s/bitcoin-s/blob/master/core/src/main/scala/org/bitcoins/core/hd/BIP32Path.scala#L176

**Comment by Christewart** [comment]
So it looks like the defintion here is actually correct. I misunderstood how `Bip32Node` works. The parameter passed in is an `index` _relative_ to the hardened flag. Thus the only valid number range is `Int.MinValue` <-> `Int.MaxValue`. With the invariant in `Bip32Node` it must be `>=0`. If you look at how `NumberGenerator.postiveInts` is defined it is `0 <= x <= Int.MaxValue` which makes this generator correct.
